Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2018-09, with the labels that each got.

#897 fixes #496 - add accompanying functions for manual indexes that just return the counts
  docs/fulltext.adoc
  docs/img/apoc.index.between.count.png
  docs/img/apoc.index.in.count.png
  docs/img/apoc.index.nodes.count.png
  docs/img/apoc.index.out.count.png
  docs/img/apoc.index.relationships.count.png
  docs/overview.adoc
  src/main/java/apoc/index/FulltextIndex.java
  src/test/java/apoc/index/FulltextIndexTest.java
Labels: Larus

#900 fixes #833 - Add apoc.load.html to make web-scraping easier
  build.gradle
  docs/img/apoc.load.htmlall.png
  docs/img/apoc.load.htmlconfig.png
  docs/img/apoc.load.htmllinks.png
  docs/index.adoc
  docs/loadhtml.adoc
  docs/overview.adoc
  src/main/java/apoc/load/LoadHtml.java
  src/test/java/apoc/load/LoadHtmlTest.java
  src/test/resources/wikipedia.html
Labels: Larus

#898 Support for both CB Server 4.x and 5.0 fixes #645
  build.gradle
  docs/overview.adoc
  src/main/java/apoc/couchbase/Couchbase.java
  src/main/java/apoc/couchbase/CouchbaseConnection.java
  src/main/java/apoc/couchbase/CouchbaseManager.java
  src/test/java/apoc/couchbase/CouchbaseAbstractTest.java
  src/test/java/apoc/couchbase/CouchbaseConnectionIT.java
  src/test/java/apoc/couchbase/CouchbaseIT.java
  src/test/java/apoc/couchbase/CouchbaseManagerIT.java
  src/test/java/apoc/couchbase/CouchbaseManagerTest.java
  src/test/java/apoc/couchbase/CouchbaseTest.java
Labels: Larus, bug

#901 fixes #591 - Handle zip/tgz/tar.gz (compressed files) with !syntax to identify single files
  docs/overview.adoc
  src/main/java/apoc/util/Util.java
  src/test/java/apoc/load/LoadCsvTest.java
  src/test/java/apoc/load/LoadJsonTest.java
  src/test/java/apoc/load/XmlTest.java
  src/test/resources/testload.tar
  src/test/resources/testload.tar.gz
  src/test/resources/testload.tgz
  src/test/resources/testload.zip
Labels: Larus

#924 fixes #923 - Tests on load csv/xml/json inside a zip by url have wrong url
  src/test/java/apoc/load/LoadCsvTest.java
  src/test/java/apoc/load/LoadJsonTest.java
  src/test/java/apoc/load/XmlTest.java
Labels: Larus, prioritized
