Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2022-03, with the labels that each got.

#2625 Makes the build green
  core/src/test/java/apoc/trigger/TriggerTest.java
Labels: team-cypher-surface

#2614 Checks full API listings and archives more test results. No AUTO cherry-pick
  .github/workflows/CI.yaml
  full/src/main/resources/extended.txt
Labels: 5.0, team-cypher-surface

#2619 Checks full API listings and archives more test results. No AUTO cherry-pick
  .github/workflows/CI.yaml
  full/src/main/resources/extended.txt
Labels: 4.4, team-cypher-surface

#2615 Checks full API listings and archives more test results. No AUTO cherry-pick
  .github/workflows/CI.yaml
  full/src/main/resources/extended.txt
Labels: 4.3, team-cypher-surface

#2616 Checks full API listings and archives more test results. No AUTO cherry-pick
  .github/workflows/CI.yaml
  full/src/main/resources/extended.txt
Labels: 4.2, team-cypher-surface

#2620 Adds a CI. No AUTO cherry-pick
  .github/workflows/CI.yaml
  .travis.yml
  build.gradle
  src/test/java/apoc/bolt/BoltTest.java
  src/test/java/apoc/couchbase/CouchbaseConnectionIT.java
  src/test/java/apoc/couchbase/CouchbaseIT.java
  src/test/java/apoc/couchbase/CouchbaseManagerIT.java
  src/test/java/apoc/couchbase/CouchbaseTest.java
  src/test/java/apoc/custom/CypherProceduresClusterTest.java
  src/test/java/apoc/diff/DiffTest.java
  src/test/java/apoc/es/ElasticSearchTest.java
  src/test/java/apoc/export/ExportS3PerformanceTest.java
  src/test/java/apoc/export/csv/ExportCsvIT.java
  src/test/java/apoc/export/csv/ExportCsvS3Test.java
  src/test/java/apoc/export/cypher/ExportCypherEnterpriseFeaturesTest.java
  src/test/java/apoc/export/cypher/ExportCypherS3Test.java
  src/test/java/apoc/export/graphml/ExportGraphMLS3Test.java
  src/test/java/apoc/export/json/ExportJsonS3Test.java
  src/test/java/apoc/load/CassandraJdbcTest.java
  src/test/java/apoc/load/LoadCsvTest.java
  src/test/java/apoc/load/LoadS3Test.java
  src/test/java/apoc/load/PostgresJdbcTest.java
  src/test/java/apoc/meta/MetaEnterpriseFeaturesTest.java
  src/test/java/apoc/metrics/MetricsTest.java
  src/test/java/apoc/model/ModelTest.java
  src/test/java/apoc/mongodb/MongoDBTest.java
  src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
  src/test/java/apoc/spatial/GeocodeTest.java
  src/test/java/apoc/util/TestUtil.java
  src/test/java/apoc/util/TestcontainersCausalCluster.java
Labels: 3.5, team-cypher-surface

#2621 Uses dev docker container in the dev branch. No AUTO cherry-pick
  .github/workflows/CI.yaml
  build.gradle
  core/build.gradle
  core/src/test/java/apoc/StartupTest.java
  docs/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/couchbase/build.gradle
  extra-dependencies/couchbase/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/email/build.gradle
  extra-dependencies/email/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/mongodb/build.gradle
  extra-dependencies/mongodb/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/nlp/build.gradle
  extra-dependencies/nlp/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/redis/build.gradle
  extra-dependencies/redis/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/xls/build.gradle
  extra-dependencies/xls/gradle/wrapper/gradle-wrapper.properties
  full/build.gradle
  full/src/main/kotlin/apoc/nlp/azure/AzureProcedures.kt
  full/src/main/resources/extended.txt
  full/src/test/java/apoc/CoreExtendedTest.java
  full/src/test/java/apoc/cypher/CypherEnterpriseTest.java
  processor/src/main/java/apoc/processor/ApocProcessor.java
  test-startup/build.gradle
  test-startup/src/test/java/StartupTest.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: 5.0, team-cypher-surface

#2629 Checks whether we are running in TeamCity as CI
  test-utils/src/main/java/apoc/util/TestUtil.java
Labels: bug, team-cypher-surface

#2633 Fixes Kotlin procedures not being listed in full package. No AUTO cherry-pick
  docs/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/couchbase/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/email/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/mongodb/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/nlp/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/redis/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/xls/gradle/wrapper/gradle-wrapper.properties
  full/build.gradle
  full/src/main/kotlin/apoc/nlp/azure/AzureProcedures.kt
  full/src/main/resources/extended.txt
  gradle/wrapper/gradle-wrapper.properties
  test-utils/build.gradle
Labels: bug, cherry-picked, 4.4, team-cypher-surface

#2634 Fixes Kotlin procedures not being listed in full package. No AUTO cherry-pick
  docs/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/couchbase/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/email/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/mongodb/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/nlp/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/redis/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/xls/gradle/wrapper/gradle-wrapper.properties
  full/build.gradle
Labels: bug, cherry-picked, 4.3, team-cypher-surface

#2635 Fixes Kotlin procedures not being listed in full package. No AUTO cherry-pick
  docs/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/couchbase/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/email/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/mongodb/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/nlp/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/redis/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/xls/gradle/wrapper/gradle-wrapper.properties
  full/build.gradle
Labels: bug, cherry-picked, 4.2, team-cypher-surface

#2637 Fixes old gradle version in some files. No AUTO cherry-pick
  docs/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/couchbase/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/email/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/mongodb/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/nlp/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/redis/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/xls/gradle/wrapper/gradle-wrapper.properties
Labels: 5.0, team-cypher-surface

#2636 Bumps gradle version. No AUTO cherry-pick
  docs/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/mongodb/gradle/wrapper/gradle-wrapper.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: 3.5, team-cypher-surface

#2638 Rewrite exists(property) to property IS NOT NULL. No AUTO cherry-pick
  core/src/main/java/apoc/refactor/rename/Rename.java
  core/src/test/java/apoc/refactor/CloneSubgraphTest.java
  core/src/test/java/apoc/refactor/rename/RenameTest.java
  core/src/test/java/apoc/schema/SchemasTest.java
  core/src/test/java/apoc/spatial/SpatialTest.java
  docs/asciidoc/modules/ROOT/pages/export/gephi.adoc
  docs/asciidoc/modules/ROOT/pages/misc/spatial.adoc
  docs/asciidoc/modules/ROOT/partials/periodic-commit.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.periodic.commit.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.schema.relationships.adoc
  docs/guide.html
  docs/index.html
Labels: 5.0, team-cypher-surface

#2622 Remove deprecated query and transaction management procedures and replace with SHOW/TERMINATE TRANSACTION
  core/src/test/java/apoc/periodic/PeriodicTest.java
  docs/asciidoc/modules/ROOT/pages/general-considerations/index.adoc
  full/src/test/java/apoc/cypher/CypherEnterpriseTest.java
  full/src/test/resources/signatures.csv
Labels: team-cypher-surface

#2649 Adds load json ssrf mitigation. No AUTO cherry-pick
  core/build.gradle
  core/src/main/java/apoc/ApocConfig.java
  core/src/main/java/apoc/util/FileUtils.java
  core/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/load/LoadJsonTest.java
  full/src/test/java/apoc/load/LoadHtmlTest.java
  readme.adoc
Labels: cherry-picked, team-cypher-surface

#2658 Revert "Remove deprecated apoc.algo docs and PathFinding code"
  core/src/main/java/apoc/algo/PathFinding.java
  core/src/test/java/apoc/algo/PathFindingTest.java
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.algo-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.algo.aStar-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.algo.aStar.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.algo.aStarConfig-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.algo.aStarConfig.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.algo.allSimplePaths-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.algo.allSimplePaths.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.algo.cover.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.algo.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.algo.dijkstra-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.algo.dijkstra.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.algo.dijkstraWithDefaultWeight-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.algo.dijkstraWithDefaultWeight.csv
  docs/asciidoc/modules/ROOT/nav.adoc
  docs/asciidoc/modules/ROOT/pages/algorithms/centrality.adoc
  docs/asciidoc/modules/ROOT/pages/algorithms/community-detection.adoc
  docs/asciidoc/modules/ROOT/pages/algorithms/index.adoc
  docs/asciidoc/modules/ROOT/pages/algorithms/pagerank.adoc
  docs/asciidoc/modules/ROOT/pages/algorithms/path-finding-procedures.adoc
  docs/asciidoc/modules/ROOT/pages/algorithms/similarity.adoc
  docs/asciidoc/modules/ROOT/pages/index.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.algo/apoc.algo.aStar.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.algo/apoc.algo.aStarConfig.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.algo/apoc.algo.allSimplePaths.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.algo/apoc.algo.cover.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.algo/apoc.algo.dijkstra.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.algo/apoc.algo.dijkstraWithDefaultWeight.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/nav.adoc
  full/import/apoc-core-extended.csv
  full/src/test/java/DocsTest.java
  full/src/test/resources/signatures.csv
Labels: 4.4

#2522 Fixes #2190: apoc.convert.toTree reorders paths
  core/src/main/java/apoc/convert/ConvertConfig.java
  core/src/main/java/apoc/convert/Json.java
  core/src/test/java/apoc/convert/ConvertJsonTest.java
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.convert.toTree.adoc
Labels: 4.3

#2379 neo4j-contrib#2378 Support for UUID encoded in Base64
  core/src/main/java/apoc/ApocConfig.java
  core/src/main/java/apoc/create/Create.java
  core/src/main/java/apoc/uuid/UuidUtil.java
  core/src/test/java/apoc/uuid/UuidUtilTest.java
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.create.uuidBase64.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.create.uuidBase64ToHex.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.create.uuidHexToBase64.adoc
  docs/asciidoc/modules/ROOT/pages/graph-updates/uuid.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.create/apoc.create.uuidBase64.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.create/apoc.create.uuidBase64ToHex.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.create/apoc.create.uuidHexToBase64.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.create.uuidBase64.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.create.uuidBase64ToHex.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.create.uuidHexToBase64.adoc
  full/src/main/java/apoc/uuid/Uuid.java
  full/src/main/java/apoc/uuid/UuidHandler.java
Labels: 4.3

#2650 Fix var tests dev
  core/build.gradle
  core/src/main/java/apoc/util/FileUtils.java
  core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
  core/src/test/java/apoc/trigger/TriggerTest.java
  docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
  docs/asciidoc/modules/ROOT/partials/usage/draft/apoc.trigger.add.adoc
  full/build.gradle
Labels: 5.0

#2670 Use the jackson-databind version from Neo4j.
  core/build.gradle
  full/build.gradle
Labels: 4.4
