Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2022-02, with the labels that each got.

#2492 fixes #2372: apoc.any.isDeleted(node/rel)
  core/src/main/java/apoc/nodes/Nodes.java
  core/src/test/java/apoc/nodes/NodesTest.java
Labels: cla-signed

#2425 Update S3 dependency versions in docs to eliminate CVEs
  docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
Labels: cla-signed

#2426 Update cypher-based-procedures-functions.adoc
  docs/asciidoc/modules/ROOT/pages/cypher-execution/cypher-based-procedures-functions.adoc
Labels: cla-needed

#2564 Uses TeamCity as artifactory
  .github/workflows/CI.yaml
  build.gradle
  teamcity-repository.gradle
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: enhancement
