Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2022-09, with the labels that each got.

#3155 Remove DocsTest
  extended/src/test/java/DocsTest.java
  extended/src/test/java/DocumentationGenerator.java
Labels: 5.0, team-cypher-surface

#3148 Fixes #2605: The apoc.custom.declareProcedure throws exception "Query results do not match requested output" with some queries (#3146)
  full/src/main/java/apoc/custom/CypherProcedures.java
  full/src/test/java/apoc/custom/CypherProceduresTest.java
Labels: cherry-picked, extended-functionality

#3162 vbump to 4.4.0.9
  build.gradle
  docs/asciidoc/antora.yml
  docs/build.gradle
  extra-dependencies/build.gradle
Labels: team-cypher-surface

#3164 respect config.writeNodeProperties when writing node details (#3152)
  core/src/main/java/apoc/export/json/ExportJson.java
  core/src/main/java/apoc/export/json/JsonFormatSerializer.java
  core/src/main/java/apoc/export/util/ExportConfig.java
  core/src/test/java/apoc/export/json/ExportJsonS3Test.java
  core/src/test/java/apoc/export/json/ExportJsonTest.java
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/MapPath.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/all.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/all_array.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/all_fields.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/all_id_as_keys.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/data.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/graph.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/listPath.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/listRel.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/query_nodes_path.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/with_node_properties.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/without_node_properties.json
  docs/asciidoc/modules/ROOT/pages/export/json.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.json.all.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.json.data.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.json.graph.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.json.query.adoc
Labels: bug, cherry-picked, 4.3

#3157 Move over extended-only configuration from core
  .github/workflows/CI.yaml
  build.gradle
  extended/build.gradle
  extended/src/main/java/apoc/ExtendedApocConfig.java
  extended/src/main/java/apoc/ExtendedApocConfigExtensionFactory.java
  extended/src/main/java/apoc/ExtendedApocGlobalComponents.java
  extended/src/main/java/apoc/JdbcRegistererInitFactory.java
  extended/src/main/java/apoc/TTLConfig.java
  extended/src/main/java/apoc/TTLConfigExtensionFactory.java
  extended/src/main/java/apoc/cache/Static.java
  extended/src/main/java/apoc/custom/CypherProceduresHandler.java
  extended/src/main/java/apoc/custom/Signatures.java
  extended/src/main/java/apoc/log/Logging.java
  extended/src/main/java/apoc/util/SimpleRateLimiter.java
  extended/src/main/java/apoc/uuid/Uuid.java
  extended/src/main/java/apoc/uuid/UuidHandler.java
  extended/src/main/resources/apoc.conf
  extended/src/test/java/apoc/ExtendedApocConfigTest.java
  extended/src/test/java/apoc/TTLConfigTest.java
  extended/src/test/java/apoc/dv/DataVirtualizationCatalogTest.java
  extended/src/test/java/apoc/export/ExportExtendedSecurityTest.java
  extended/src/test/java/apoc/export/csv/ExportCsvTest.java
  extended/src/test/java/apoc/export/csv/ExportXlsTest.java
  extended/src/test/java/apoc/load/LoadCsvTest.java
  extended/src/test/java/apoc/load/LoadExtendedSecurityTest.java
  extended/src/test/java/apoc/load/LoadHdfsTest.java
  extended/src/test/java/apoc/load/LoadHtmlTest.java
  extended/src/test/java/apoc/load/LoadHtmlTestParameterized.java
  extended/src/test/java/apoc/load/LoadS3Test.java
  extended/src/test/java/apoc/load/LoadXlsTest.java
  extended/src/test/java/apoc/load/relative/LoadRelativePathTest.java
  extended/src/test/java/apoc/log/LoggingTest.java
  extended/src/test/java/apoc/systemdb/SystemDbTest.java
  extended/src/test/java/apoc/trigger/TriggerExtendedTest.java
  extended/src/test/java/apoc/ttl/TTLTest.java
  extended/src/test/java/apoc/util/SimpleRateLimiterTest.java
  extended/src/test/java/apoc/uuid/UUIDMultiDbTest.java
  extended/src/test/java/apoc/uuid/UUIDTest.java
  teamcity-repository.gradle
Labels: 5.0, team-cypher-surface

#3168 Depend on 5.0.0 core and introduce extended config
  .github/workflows/CI.yaml
  build.gradle
  extended/build.gradle
  extended/src/main/java/apoc/ExtendedApocConfig.java
  extended/src/main/java/apoc/ExtendedApocConfigExtensionFactory.java
  extended/src/main/java/apoc/ExtendedApocGlobalComponents.java
  extended/src/main/java/apoc/JdbcRegistererInitFactory.java
  extended/src/main/java/apoc/TTLConfig.java
  extended/src/main/java/apoc/TTLConfigExtensionFactory.java
  extended/src/main/java/apoc/cache/Static.java
  extended/src/main/java/apoc/custom/CypherProceduresHandler.java
  extended/src/main/java/apoc/custom/Signatures.java
  extended/src/main/java/apoc/log/Logging.java
  extended/src/main/java/apoc/util/SimpleRateLimiter.java
  extended/src/main/java/apoc/uuid/Uuid.java
  extended/src/main/java/apoc/uuid/UuidHandler.java
  extended/src/main/resources/apoc.conf
  extended/src/test/java/apoc/ExtendedApocConfigTest.java
  extended/src/test/java/apoc/TTLConfigTest.java
  extended/src/test/java/apoc/dv/DataVirtualizationCatalogTest.java
  extended/src/test/java/apoc/export/ExportExtendedSecurityTest.java
  extended/src/test/java/apoc/export/csv/ExportCsvTest.java
  extended/src/test/java/apoc/export/csv/ExportXlsTest.java
  extended/src/test/java/apoc/load/LoadCsvTest.java
  extended/src/test/java/apoc/load/LoadExtendedSecurityTest.java
  extended/src/test/java/apoc/load/LoadHdfsTest.java
  extended/src/test/java/apoc/load/LoadHtmlTest.java
  extended/src/test/java/apoc/load/LoadHtmlTestParameterized.java
  extended/src/test/java/apoc/load/LoadS3Test.java
  extended/src/test/java/apoc/load/LoadXlsTest.java
  extended/src/test/java/apoc/load/relative/LoadRelativePathTest.java
  extended/src/test/java/apoc/log/LoggingTest.java
  extended/src/test/java/apoc/systemdb/SystemDbTest.java
  extended/src/test/java/apoc/trigger/TriggerExtendedTest.java
  extended/src/test/java/apoc/ttl/TTLTest.java
  extended/src/test/java/apoc/util/SimpleRateLimiterTest.java
  extended/src/test/java/apoc/uuid/UUIDMultiDbTest.java
  extended/src/test/java/apoc/uuid/UUIDTest.java
  teamcity-repository.gradle
Labels: cherry-picked

#3170 Bump snakeyaml to latest release
  core/build.gradle
Labels: 4.4

#3177 Fix double escaping graphml
  core/src/main/java/apoc/export/util/FormatUtils.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  core/src/test/resources/fileWithUnicode.graphml
Labels: 4.4

#3184 fixes #2934: `apoc.meta.relTypeProperties` doest not return relationship information (#2935)
  core/src/main/java/apoc/cypher/CypherInitializer.java
  core/src/main/java/apoc/meta/Meta.java
  core/src/test/java/apoc/meta/MetaTest.java
Labels: cherry-picked, 4.3
