Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2022-04, with the labels that each got.

#2678 Update junit version to be consistent
  build.gradle
Labels: 3.5

#2676 Update junit version to be consistent
  core/build.gradle
  test-utils/build.gradle
Labels: 5.0

#2496 Fixes #1714: Weirdness around custom functions with node return types (4.3)
  full/src/main/java/apoc/custom/CypherProceduresHandler.java
  full/src/main/java/apoc/custom/Signatures.java
  full/src/test/java/apoc/custom/CypherProceduresStorageTest.java
  full/src/test/java/apoc/custom/CypherProceduresTest.java
Labels: 4.3

#2494 Fixes #2418: "apoc.cypher.runFile" cannot run IN TRANSACTIONS OF successfully
  full/src/main/java/apoc/cypher/CypherExtended.java
  full/src/test/java/apoc/cypher/CypherExtendedTest.java
  full/src/test/resources/in_transaction.cypher
Labels: 4.4

#2521 Fixes #2468: APOC uses Jackson version prior to 2.11 not compatible with latest spring-boot
  core/build.gradle
  full/build.gradle
Labels: 4.4

#2667 Upgrade dependencies to mitigate vulnerabilities
  core/build.gradle
  extra-dependencies/nlp/build.gradle
  full/build.gradle
  test-utils/build.gradle
Labels: cherry-picked, 5.0

#2668 Upgrade dependencies to mitigate vulnerabilities
  build.gradle
  src/test/java/apoc/export/csv/ExportCsvTest.java
  src/test/java/apoc/load/LoadHdfsTest.java
  src/test/java/apoc/load/relative/LoadRelativePathTest.java
  src/test/java/apoc/util/HdfsTestUtils.java
Labels: cherry-picked, 3.5

#2524 apoc.meta.stats() displays incorrect relationship counts with multi-label nodes
  core/src/main/java/apoc/meta/Meta.java
  core/src/test/java/apoc/meta/MetaTest.java
  docs/asciidoc/modules/ROOT/partials/usage/apoc.meta.stats.adoc
Labels: 4.4

#2508 Issue 2174: Add doc description and examples for apoc.cypher.parallel*
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.cypher.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.cypher.parallel.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.cypher.parallel2.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/documentation.csv
  docs/asciidoc/modules/ROOT/pages/cypher-execution/index.adoc
  docs/asciidoc/modules/ROOT/pages/cypher-execution/parallel.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.cypher/apoc.cypher.mapParallel.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.cypher/apoc.cypher.mapParallel2.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.cypher/apoc.cypher.parallel.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.cypher/apoc.cypher.parallel2.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.cypher/index.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
  full/src/main/java/apoc/cypher/CypherExtended.java
  full/src/test/java/apoc/cypher/CypherExtendedTest.java
Labels: 4.3

#2552 use `@ServiceProvider` annotation instead of META-INF/services files
  core/src/main/java/apoc/ApocConfigExtensionFactory.java
  core/src/main/java/apoc/ApocExtensionFactory.java
  core/src/main/java/apoc/PoolExtensionFactory.java
  core/src/main/java/apoc/RegisterComponentFactory.java
  core/src/main/java/apoc/TTLConfigExtensionFactory.java
  core/src/main/resources/META-INF/services/org.neo4j.configuration.SettingsDeclaration
  core/src/main/resources/META-INF/services/org.neo4j.kernel.extension.ExtensionFactory
  full/src/main/resources/META-INF/services/org.neo4j.kernel.extension.ExtensionFactory
Labels: 4.4

#2588 Fixes #2269: apoc.load procedures don't work anymore with urls containing %
  core/src/main/java/apoc/util/FileUtils.java
Labels: 4.3

#2475 Missing ^ in the example for ascending order
  docs/asciidoc/modules/ROOT/partials/usage/apoc.coll.sortNodes.adoc
Labels: docs, 4.4

#2706 Replace db.cluster.role with SHOW DATABASE
  core/src/main/java/apoc/util/Util.java
Labels: 5.0, team-cypher-surface

#2707 Fixes the Cypher files execution not happening sequentially
  full/src/main/java/apoc/cypher/CypherExtended.java
  full/src/test/java/apoc/cypher/CypherExtendedTest.java
  full/src/test/resources/create_delete_with_sleep.cypher
  full/src/test/resources/create_with_sleep.cypher
Labels: bug, to-cherry-pick, 5.0, team-cypher-surface

#2592 Fixes #2325: added config cleanup
  core/src/main/java/apoc/export/json/ImportJsonConfig.java
  core/src/main/java/apoc/export/json/JsonImporter.java
  core/src/test/java/apoc/export/json/ImportJsonTest.java
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.import.json.adoc
Labels: 4.3

#2593 Fixes #2325: added property filters
  core/src/main/java/apoc/export/json/ImportJsonConfig.java
  core/src/main/java/apoc/export/json/JsonImporter.java
  core/src/test/java/apoc/export/json/ImportJsonTest.java
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.import.json.adoc
Labels: 4.3

#2594 Fixes #2013: Move HDFS deps to external-dependencies
  .gitignore
  core/src/main/java/apoc/util/FileUtils.java
  docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
  extra-dependencies/hadoop/build.gradle
  extra-dependencies/hadoop/gradle/wrapper/gradle-wrapper.jar
  extra-dependencies/hadoop/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/hadoop/gradlew
  extra-dependencies/hadoop/gradlew.bat
  extra-dependencies/hadoop/settings.gradle
  extra-dependencies/settings.gradle
Labels: 4.4, extended-functionality

#2751 Bumps version of the cherry-pick action
  .github/workflows/auto-cherry-pick.yml
Labels: bug, to-cherry-pick, team-cypher-surface

#2754 Updates version of the cherry-pick action
  .github/workflows/auto-cherry-pick.yml
Labels: cherry-picked, 4.3, team-cypher-surface

#2752 Uses service account token when cherry-picking
  .github/workflows/auto-cherry-pick.yml
Labels: bug, to-cherry-pick, 5.0, team-cypher-surface

#2756 AUTO: Uses service account token when cherry-picking (#2752)
  .github/workflows/auto-cherry-pick.yml
Labels: autocreated

#2743 Ignores test failures only in TeamCity
  build.gradle
Labels: bug, to-cherry-pick, 5.0, team-cypher-surface

#2757 AUTO: Uses service account token when cherry-picking (#2752) (#2756)
  .github/workflows/auto-cherry-pick.yml
Labels: autocreated

#2758 AUTO: Uses service account token when cherry-picking (#2752) (#2756) (#2757)
  .github/workflows/auto-cherry-pick.yml
Labels: autocreated

#2760 NO AUTO Ignores test failures only in TeamCity
  build.gradle
Labels: cherry-picked, 4.4, team-cypher-surface

#2761 NO AUTO Ignores test failures only in TeamCity
  build.gradle
Labels: cherry-picked, 4.3, team-cypher-surface

#2762 NO AUTO Ignores test failures only in TeamCity
  build.gradle
Labels: cherry-picked, 4.2, team-cypher-surface

#2763 Ignores test failures only in TeamCity
  build.gradle
Labels: cherry-picked, 3.5, team-cypher-surface

#2764 Fix typo
  docs/asciidoc/modules/ROOT/pages/export/csv.adoc
Labels: cherry-picked, 4.2

#2765 AUTO: fix typo (#2708) (#2764)
  docs/asciidoc/modules/ROOT/pages/export/csv.adoc
Labels: autocreated

#2766 AUTO: fix typo (#2708) (#2764) (#2765)
  docs/asciidoc/modules/ROOT/pages/export/csv.adoc
Labels: autocreated

#2767 AUTO: fix typo (#2708) (#2764) (#2765) (#2766)
  docs/asciidoc/modules/ROOT/pages/export/csv.adoc
Labels: autocreated

#2590 apoc.refactor.mergeNodes is not producing desired output
  core/src/main/java/apoc/refactor/util/PropertiesManager.java
  core/src/main/java/apoc/refactor/util/RefactorConfig.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
  docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/merge-nodes.adoc
Labels: 4.3, core-functionality

#2769 AUTO: apoc.refactor.mergeNodes is not producing desired output (#2590)
  core/src/main/java/apoc/refactor/util/PropertiesManager.java
  core/src/main/java/apoc/refactor/util/RefactorConfig.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
  docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/merge-nodes.adoc
Labels: autocreated

#2768 AUTO: apoc.refactor.mergeNodes is not producing desired output (#2590)
  core/src/main/java/apoc/refactor/util/PropertiesManager.java
  core/src/main/java/apoc/refactor/util/RefactorConfig.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
  docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/merge-nodes.adoc
Labels: autocreated

#2770 AUTO: apoc.refactor.mergeNodes is not producing desired output (#2590) (#2769)
  core/src/main/java/apoc/refactor/util/PropertiesManager.java
  core/src/main/java/apoc/refactor/util/RefactorConfig.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
  docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/merge-nodes.adoc
Labels: autocreated

#2728 Schema tests
  core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
Labels: bug, 5.0, team-cypher-surface

#2772 AUTO: Fixes #2607: apoc.export.json.data JSON format missing brace (#2698)
  core/src/main/java/apoc/export/json/JsonFormat.java
  core/src/test/java/apoc/export/json/ExportJsonTest.java
Labels: autocreated

#2773 AUTO: Fixes #2607: apoc.export.json.data JSON format missing brace (#2698)
  core/src/main/java/apoc/export/json/JsonFormat.java
  core/src/test/java/apoc/export/json/ExportJsonTest.java
Labels: autocreated

#2703 Fixes #2645: csv import fails when parse an empty string as a date
  core/src/main/java/apoc/load/Mapping.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
Labels: 4.4, core-functionality

#2775 AUTO: Fixes #2645: csv import fails when parse an empty string as a date (#2703)
  core/src/main/java/apoc/load/Mapping.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
Labels: autocreated

#2774 AUTO: Fixes #2645: csv import fails when parse an empty string as a date (#2703)
  core/src/main/java/apoc/load/Mapping.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
Labels: autocreated

#2776 Fixes #2607: apoc.export.json.data JSON format missing brace (#2698)
  core/src/main/java/apoc/export/json/JsonFormat.java
  core/src/test/java/apoc/export/json/ExportJsonTest.java
Labels: cherry-picked, 4.2

#2777 AUTO: Fixes #2645: csv import fails when parse an empty string as a date (#2703) (#2775)
  core/src/main/java/apoc/load/Mapping.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
Labels: autocreated

#2771 Update setting namespace to be internal instead of unsupported
  core/src/test/java/apoc/export/ExportStreamsStatementsTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  core/src/test/java/apoc/graph/GraphsTest.java
  core/src/test/java/apoc/load/LoadJsonTest.java
  core/src/test/java/apoc/meta/MetaTest.java
  core/src/test/java/apoc/path/LabelSequenceTest.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
  full/src/test/kotlin/apoc/nlp/NLPHelperFunctionsWithDatabaseTest.kt
  full/src/test/kotlin/apoc/nlp/aws/AWSVirtualEntitiesGraphStoreTest.kt
  full/src/test/kotlin/apoc/nlp/gcp/GCPVirtualEntitiesGraphStoreTest.kt
Labels: 5.0

#2720 Make PathExpander return ResourceIterable in readiness for Core API changes
  core/src/main/java/apoc/path/RelationshipSequenceExpander.java
Labels: 5.0, team-cypher-surface

#2648 Fixes #2405: The apoc.schema.assert procedure fails with multi-label fulltext index
  core/src/main/java/apoc/schema/Schemas.java
  core/src/test/java/apoc/schema/SchemasTest.java
  docs/asciidoc/modules/ROOT/partials/usage/apoc.schema.assert.adoc
Labels: 4.3, core-functionality

#2589 Fixes #2402: See if we can make the aStar algorithm support spatial points
  core/src/main/java/apoc/algo/PathFinding.java
  core/src/test/java/apoc/algo/PathFindingTest.java
  docs/asciidoc/modules/ROOT/pages/algorithms/path-finding-procedures.adoc
  full/src/main/java/apoc/algo/PathFindingFull.java
  full/src/main/resources/extended.txt
  full/src/test/java/apoc/algo/PathFindingFullTest.java
  test-utils/src/main/java/apoc/algo/AlgoUtil.java
Labels: 4.4, core-functionality

#2786 AUTO: Fixes #2402: See if we can make the aStar algorithm support spatial points (#2589)
  core/src/main/java/apoc/algo/PathFinding.java
  core/src/test/java/apoc/algo/PathFindingTest.java
  docs/asciidoc/modules/ROOT/pages/algorithms/path-finding-procedures.adoc
  full/src/main/java/apoc/algo/PathFindingFull.java
  full/src/main/resources/extended.txt
  full/src/test/java/apoc/algo/PathFindingFullTest.java
  test-utils/src/main/java/apoc/algo/AlgoUtil.java
Labels: autocreated

#2787 Fix apoc.schema tests
  core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
Labels: bug, cherry-picked, 4.4

#2785 AUTO: Fixes #2402: See if we can make the aStar algorithm support spatial points (#2589)
  core/src/main/java/apoc/algo/PathFinding.java
  core/src/test/java/apoc/algo/PathFindingTest.java
  docs/asciidoc/modules/ROOT/pages/algorithms/path-finding-procedures.adoc
  full/src/main/java/apoc/algo/PathFindingFull.java
  full/src/main/resources/extended.txt
  full/src/test/java/apoc/algo/PathFindingFullTest.java
  test-utils/src/main/java/apoc/algo/AlgoUtil.java
Labels: autocreated

#2386 Update readme.adoc
  readme.adoc
Labels: docs, cla-signed, 4.3

#2795 AUTO: Bump ansi-regex from 3.0.0 to 3.0.1 in /docs/antora (#2734)
  docs/antora/package-lock.json
Labels: autocreated

#2794 AUTO: Bump ansi-regex from 3.0.0 to 3.0.1 in /docs/antora (#2734)
  docs/antora/package-lock.json
Labels: autocreated

#2792 AUTO: Update readme.adoc
  readme.adoc
Labels: autocreated

#2783 AUTO: Fixes #2405: The apoc.schema.assert procedure fails with multi-label fulltext index (#2648)
  core/src/main/java/apoc/schema/Schemas.java
  core/src/test/java/apoc/schema/SchemasTest.java
  docs/asciidoc/modules/ROOT/partials/usage/apoc.schema.assert.adoc
Labels: autocreated

#2796 AUTO: Bump ansi-regex from 3.0.0 to 3.0.1 in /docs/antora (#2734) (#2795)
  docs/antora/package-lock.json
Labels: autocreated

#2798 AUTO: Bump normalize-url from 4.5.0 to 4.5.1 in /docs/antora
  docs/antora/package-lock.json
Labels: autocreated

#2799 AUTO: Fix apoc.convert.toTree reorders paths
  core/src/main/java/apoc/convert/ConvertConfig.java
  core/src/main/java/apoc/convert/Json.java
  core/src/test/java/apoc/convert/ConvertJsonTest.java
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.convert.toTree.adoc
Labels: autocreated

#2800 AUTO: Support for UUID encoded in Base64
  core/src/main/java/apoc/ApocConfig.java
  core/src/main/java/apoc/create/Create.java
  core/src/main/java/apoc/uuid/UuidUtil.java
  core/src/test/java/apoc/uuid/UuidUtilTest.java
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.create.uuidBase64.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.create.uuidBase64ToHex.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.create.uuidHexToBase64.adoc
  docs/asciidoc/modules/ROOT/pages/graph-updates/uuid.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.create/apoc.create.uuidBase64.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.create/apoc.create.uuidBase64ToHex.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.create/apoc.create.uuidHexToBase64.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.create.uuidBase64.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.create.uuidBase64ToHex.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.create.uuidHexToBase64.adoc
  full/src/main/java/apoc/uuid/Uuid.java
  full/src/main/java/apoc/uuid/UuidHandler.java
Labels: autocreated

#2801 AUTO: Bump simple-get from 3.1.0 to 3.1.1 in /docs/antora
  docs/antora/package-lock.json
Labels: autocreated

#2802 AUTO: Bump minimist from 1.2.5 to 1.2.6 in /docs/antora
  docs/antora/package-lock.json
Labels: autocreated

#2809 Attempt to fix TeamCity build
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: bug, cherry-picked, 5.0

#2810 Attempt to fix TeamCity build
  build.gradle
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: bug, cherry-picked, 4.4

#2808 AUTO: APOC uses Jackson version prior to 2.11 not compatible with latest spring-boot
  core/build.gradle
  full/build.gradle
Labels: autocreated

#2812 AUTO: apoc.meta.stats() displays incorrect relationship counts with multi-label nodes
  core/src/main/java/apoc/meta/Meta.java
  core/src/test/java/apoc/meta/MetaTest.java
  docs/asciidoc/modules/ROOT/partials/usage/apoc.meta.stats.adoc
Labels: autocreated

#2813 AUTO: Missing ^ in the example for ascending order
  docs/asciidoc/modules/ROOT/partials/usage/apoc.coll.sortNodes.adoc
Labels: autocreated

#2806 Adjust APOC docs to removals in Cypher
  docs/asciidoc/modules/ROOT/pages/graph-updates/periodic-execution.adoc
  docs/asciidoc/modules/ROOT/pages/import/load-csv.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.create.virtual.fromNode.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.schema.nodes.adoc
  docs/asciidoc/modules/ROOT/partials/usage/draft/apoc.cypher.mapParallel2.adoc
Labels: docs, 5.0, team-cypher-surface

#2811 Attempt to fix TeamCity build
  build.gradle
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: bug, cherry-picked, 4.2
