Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2022-12, with the labels that each got.

#3351 [eOxJMLMv] Checks redirects for blocked IPs instead of just final location.
  core/src/main/java/apoc/ApocConfig.java
  core/src/main/java/apoc/util/FileUtils.java
  core/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/load/XmlTest.java
  core/src/test/java/apoc/util/UtilIT.java
Labels: cherry-picked, 4.3

#3350 [eOxJMLMv] Checks redirects for blocked IPs instead of just final location.
  core/src/main/java/apoc/ApocConfig.java
  core/src/main/java/apoc/util/FileUtils.java
  core/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/load/XmlTest.java
  core/src/test/java/apoc/util/UtilIT.java
Labels: cherry-picked, 4.4

#3175 Fixes #2895: update apoc.custom.* documentation (#2937)
  docs/asciidoc/modules/ROOT/pages/cypher-execution/cypher-based-procedures-functions.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.declareFunction.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.declareProcedure.adoc
Labels: cherry-picked, 5.0, extended-functionality

#3325 [gRNAet7B] added documentation about new trigger procedures and deprecated ones
  core/src/main/java/apoc/trigger/TriggerNewProcedures.java
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.trigger-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.trigger.add.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.trigger.drop.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.trigger.dropAll.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.trigger.install.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.trigger.start.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.trigger.stop.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/documentation.csv
  docs/asciidoc/modules/ROOT/images/apoc.trigger.pause.png
  docs/asciidoc/modules/ROOT/images/apoc.trigger.resume.png
  docs/asciidoc/modules/ROOT/images/apoc.trigger.start.png
  docs/asciidoc/modules/ROOT/images/apoc.trigger.stop.png
  docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.add.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.drop.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.dropAll.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.install.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.list.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.pause.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.remove.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.removeAll.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.resume.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.start.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.stop.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/index.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/nav.adoc
  docs/asciidoc/modules/ROOT/partials/triggers/deprecated.adoc
  docs/asciidoc/modules/ROOT/partials/triggers/triggersConfig.adoc
Labels: docs, 4.4

#3300 Fixes #2933: Add configurations for apoc.load.html via selenium browser (#2990)
  full/src/main/java/apoc/load/LoadHtmlBrowser.java
  full/src/main/java/apoc/load/LoadHtmlConfig.java
  full/src/test/java/apoc/load/LoadHtmlTest.java
Labels: cherry-picked, 4.3, extended-functionality

#3357 [qwJFy8pp] Add @Admin to trigger procedures
  core/src/main/java/apoc/trigger/Trigger.java
  core/src/main/java/apoc/trigger/TriggerNewProcedures.java
  core/src/test/java/apoc/trigger/TriggerClusterRoutingTest.java
  docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
Labels: 4.4, core-functionality

#3096 Fixes #1622: Add a traveling salesman procedure to apoc
  core/src/main/java/apoc/algo/PathFinding.java
  docs/asciidoc/modules/ROOT/pages/algorithms/path-finding-procedures.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.algo.travellingSalesman.adoc
  full/src/main/java/apoc/algo/PathFindingFull.java
  full/src/main/java/apoc/algo/TravellingSalesman.java
  full/src/main/resources/extended.txt
  full/src/test/java/apoc/algo/PathFindingFullTest.java
Labels: 4.4, extended-functionality

#3098 Fixes #1582: rebind flag in apoc.periodic.iterate
  docs/asciidoc/modules/ROOT/nav.adoc
  docs/asciidoc/modules/ROOT/pages/operational/index.adoc
  docs/asciidoc/modules/ROOT/pages/operational/rebind.adoc
  full/src/main/java/apoc/nodes/NodesExtended.java
  full/src/main/java/apoc/util/EntityUtil.java
  full/src/main/resources/extended.txt
  full/src/test/java/apoc/nodes/NodesExtendedTest.java
  full/src/test/java/apoc/periodic/PeriodicExtendedTest.java
Labels: extended-functionality

#3335 [gRNAet7B] Added trigger show procedure
  core/src/main/java/apoc/trigger/Trigger.java
  core/src/main/java/apoc/trigger/TriggerHandlerNewProcedures.java
  core/src/main/java/apoc/trigger/TriggerNewProcedures.java
  core/src/test/java/apoc/trigger/TriggerClusterRoutingTest.java
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.trigger-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.trigger.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.trigger.list.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.trigger.list.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.trigger.show.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/documentation.csv
  docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.list.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.show.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/index.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/nav.adoc
  docs/index.html
  full/src/test/java/apoc/trigger/TriggerClusterTest.java
Labels: team-cypher-surface

#3362 [3KXXQazJ] Fix bug with serializing arrays of primitive values for json export query
  core/src/main/java/apoc/export/json/JsonFormat.java
  core/src/main/java/apoc/meta/Meta.java
  core/src/test/java/apoc/export/json/ExportJsonTest.java
Labels: bug, cherry-picked, 4.4, team-cypher-surface

#3363 [3KXXQazJ] Fix bug with serializing arrays of primitive values for json export query
  core/src/main/java/apoc/export/json/JsonFormat.java
  core/src/main/java/apoc/meta/Meta.java
  core/src/test/java/apoc/export/json/ExportJsonTest.java
Labels: bug, cherry-picked, 4.3, team-cypher-surface

#3180 Fixes #2933: Add configurations for apoc.load.html via selenium browser (#2990)
  extended/src/main/java/apoc/load/LoadHtmlBrowser.java
  extended/src/main/java/apoc/load/LoadHtmlConfig.java
  extended/src/test/java/apoc/load/LoadHtmlTest.java
Labels: cherry-picked, 5.0, extended-functionality

#3366 Makes gradle go to Maven Central for extra-dependencies project
  extra-dependencies/build.gradle
Labels: cherry-picked, 4.2, team-cypher-surface

#3369 [coZSswV2] Fixes triggers
  core/src/main/java/apoc/trigger/TriggerNewProcedures.java
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
  core/src/test/java/apoc/trigger/TriggerTest.java
Labels: bug, 4.4, team-cypher-surface

#3371 4.3 export security fix
  core/src/main/java/apoc/export/csv/ExportCSV.java
  core/src/main/java/apoc/util/FileUtils.java
  core/src/test/java/apoc/export/ExportCoreSecurityTest.java
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
Labels: cherry-picked, 4.3, team-cypher-surface

#3370 4.4 export security fix
  core/src/main/java/apoc/export/csv/ExportCSV.java
  core/src/main/java/apoc/util/FileUtils.java
  core/src/test/java/apoc/export/ExportCoreSecurityTest.java
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
Labels: cherry-picked, 4.4, team-cypher-surface

#3376 [rQCxvZ5O] Improved docs and test with user-pass auth
  docs/asciidoc/modules/ROOT/pages/database-integration/elasticsearch.adoc
  extended/src/test/java/apoc/es/ElasticSearchTest.java
Labels: extended-functionality

#3374 Fixes #3358: apoc extended on 5.2 throws errors for missing config values
  extended/src/main/java/apoc/TTLConfig.java
  extended/src/main/java/apoc/uuid/UuidHandler.java
Labels: extended-functionality

#3377 bump version to 5.3.0 - various changes for 5.3.0 release
  .github/workflows/CI.yaml
  .gitmodules
  build.gradle
  docs/asciidoc/antora.yml
  docs/asciidoc/modules/ROOT/pages/database-integration/bolt-neo4j.adoc
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
  docs/build.gradle
  extended/src/test/java/apoc/load/LoadHtmlTest.java
  extra-dependencies/bolt/build.gradle
  extra-dependencies/bolt/gradle/wrapper/gradle-wrapper.jar
  extra-dependencies/bolt/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/bolt/gradlew
  extra-dependencies/bolt/gradlew.bat
  extra-dependencies/bolt/settings.gradle
  extra-dependencies/build.gradle
  extra-dependencies/selenium/build.gradle
  extra-dependencies/xls/build.gradle
  readme.adoc
  teamcity-repository.gradle
Labels: extended-functionality

#3379 [i19tvtq1] Add Trello Traceability GHA to CI
  .github/workflows/traceability.yaml
  readme.adoc
Labels: cherry-picked

#3378 [coZSswV2] Cleanup trigger docs
  core/src/main/java/apoc/trigger/Trigger.java
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.trigger.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.trigger.dropAll.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.trigger.list.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.trigger.list.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/documentation.csv
  docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.list.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/index.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
Labels: 4.4, team-cypher-surface
