Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2022-11, with the labels that each got.

#3264 Add notes to send user to Core docs in 4.x series
  docs/asciidoc/modules/ROOT/pages/index.adoc
  docs/asciidoc/modules/ROOT/pages/overview/index.adoc
Labels: docs, 4.4, team-cypher-surface

#3265 4.3 add note about apoc split
  docs/asciidoc/modules/ROOT/pages/index.adoc
  docs/asciidoc/modules/ROOT/pages/overview/index.adoc
  readme.adoc
Labels: docs, cherry-picked, 4.3, team-cypher-surface

#3266 4.2 add note about apoc split
  docs/asciidoc/modules/ROOT/pages/index.adoc
  docs/asciidoc/modules/ROOT/pages/overview/index.adoc
  readme.adoc
Labels: docs, cherry-picked, 4.2, team-cypher-surface

#3268 4.0 add note about apoc split
  docs/asciidoc/modules/ROOT/pages/index.adoc
  docs/asciidoc/modules/ROOT/pages/overview/index.adoc
  readme.adoc
Labels: docs, 4.0, cherry-picked, team-cypher-surface

#3270 5.0 update docs
  docs/asciidoc/modules/ROOT/pages/config/index.adoc
  docs/asciidoc/modules/ROOT/pages/deprecations-and-additions/index.adoc
  docs/asciidoc/modules/ROOT/pages/index.adoc
  docs/asciidoc/modules/ROOT/pages/introduction/index.adoc
  docs/asciidoc/modules/ROOT/pages/overview/index.adoc
  docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
  readme.adoc
Labels: docs, cherry-picked, 5.0, team-cypher-surface

#3271 Bring over readme updates
  readme.adoc
Labels: docs, cherry-picked, 4.4, team-cypher-surface

#3261 [SXnVeQi9] change ApocStreamHandlerFactory to a service provider to avoid deadlock on startup
  core/src/main/java/apoc/ApocExtensionFactory.java
  core/src/main/java/apoc/util/ApocUrlStreamHandlerFactory.java
  core/src/main/resources/META-INF/services/java.net.spi.URLStreamHandlerProvider
Labels: cherry-picked, 4.4

#3279 Update Antora Dependencies
  docs/antora/package-lock.json
  docs/antora/package.json
Labels: docs, cherry-picked, 4.4, team-cypher-surface

#3280 Update Antora Dependencies
  docs/antora/package-lock.json
  docs/antora/package.json
Labels: docs, cherry-picked, 4.3, team-cypher-surface

#3259 [NOID] Fixes CVE-2022-42889 in transitive dependencies
  core/build.gradle
  core/src/main/java/apoc/export/csv/CsvEntityLoader.java
  full/build.gradle
  full/src/main/java/apoc/load/LoadCsv.java
  full/src/test/java/apoc/load/LoadCsvTest.java
  full/src/test/resources/test-escape.csv
  full/src/test/resources/test-escaped-delimiters.csv
Labels: bug, cherry-picked, 4.3, team-cypher-surface

#3258 [NOID] Fixes CVE-2022-42889 in transitive dependencies
  core/build.gradle
  core/src/main/java/apoc/export/csv/CsvEntityLoader.java
  full/build.gradle
  full/src/main/java/apoc/load/LoadCsv.java
  full/src/test/java/apoc/load/LoadCsvTest.java
  full/src/test/resources/test-escape.csv
  full/src/test/resources/test-escaped-delimiters.csv
Labels: bug, cherry-picked, 4.4

#3282 [NOID] Updates docs for apoc.load.csv new escape + delimiter behaviour
  docs/asciidoc/modules/ROOT/pages/import/load-csv.adoc
Labels: 4.4, team-cypher-surface

#3288 Makes load csv tests less flaky
  full/src/test/java/apoc/load/LoadCsvTest.java
Labels: to-cherry-pick, 4.4, team-cypher-surface

#3289 Solves some problems with the 5.1 build
  .gitmodules
  extended/src/test/java/apoc/systemdb/SystemDbTest.java
  readme.adoc
Labels: extended-functionality

#3287 Makes gradle go to Maven Central for extra-dependencies project
  extra-dependencies/build.gradle
Labels: to-cherry-pick, 4.4, team-cypher-surface

#3291 Makes gradle go to Maven Central for extra-dependencies project
  extra-dependencies/build.gradle
Labels: cherry-picked, 4.3, team-cypher-surface

#3293 Makes gradle go to Maven Central for extra-dependencies project
  extra-dependencies/build.gradle
Labels: cherry-picked, extended-functionality, 5.1

#3286 Try to fix various tests in 5.1
  extended/src/test/java/apoc/couchbase/CouchbaseTestUtils.java
  extended/src/test/java/apoc/load/LoadHtmlTest.java
  extended/src/test/java/apoc/load/LoadHtmlTestParameterized.java
  extended/src/test/java/apoc/ttl/TTLMultiDbTest.java
  extended/src/test/java/apoc/util/s3/S3Container.java
Labels: extended-functionality, 5.1

#3292 Makes gradle go to Maven Central for extra-dependencies project
  extra-dependencies/build.gradle
Labels: cherry-picked, team-cypher-surface, extended-functionality

#3297 [NOID] Bump snakeyaml to latest release
  core/build.gradle
  full/build.gradle
Labels: team-cypher-surface, changelog

#3298 Fix various flaky and local tests in 4.x (#3286)
  full/src/test/java/apoc/couchbase/CouchbaseTestUtils.java
  full/src/test/java/apoc/load/LoadHtmlTest.java
  full/src/test/java/apoc/load/LoadHtmlTestParameterized.java
  full/src/test/java/apoc/ttl/TTLMultiDbTest.java
  full/src/test/java/apoc/util/s3/S3Container.java
Labels: cherry-picked, 4.4, extended-functionality

#3299 Fix various flaky and local tests in 4.x (#3286)
  full/src/test/java/apoc/couchbase/CouchbaseTestUtils.java
  full/src/test/java/apoc/load/LoadHtmlTest.java
  full/src/test/java/apoc/load/LoadHtmlTestParameterized.java
  full/src/test/java/apoc/ttl/TTLMultiDbTest.java
  full/src/test/java/apoc/util/s3/S3Container.java
Labels: cherry-picked, 4.3, extended-functionality

#3302 [NOID] Removes load json test, the data is not in the external API anymore
  core/src/test/java/apoc/load/LoadJsonTest.java
Labels: cherry-picked, 4.4

#3309 Reallocate Youtube tutorial to Appendix page
  docs/asciidoc/modules/ROOT/nav.adoc
  docs/asciidoc/modules/ROOT/pages/appendix/apoc-video-tutorial.adoc
  docs/asciidoc/modules/ROOT/pages/appendix/index.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/load-jdbc.adoc
  docs/asciidoc/modules/ROOT/pages/graph-updates/ttl.adoc
  docs/asciidoc/modules/ROOT/pages/introduction/index.adoc
Labels: team-cypher-surface, 5.3

#3311 Rename APOC library to APOC Extended library (#3308)
  docs/asciidoc/functions.adoc
  docs/asciidoc/jmh.adoc
  docs/asciidoc/modules/ROOT/pages/config/index.adoc
  docs/asciidoc/modules/ROOT/pages/cypher-execution/index.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/bolt-neo4j.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/couchbase.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/index.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/redis.adoc
  docs/asciidoc/modules/ROOT/pages/database-introspection/index.adoc
  docs/asciidoc/modules/ROOT/pages/export/index.adoc
  docs/asciidoc/modules/ROOT/pages/general-considerations/index.adoc
  docs/asciidoc/modules/ROOT/pages/graph-updates/index.adoc
  docs/asciidoc/modules/ROOT/pages/import/index.adoc
  docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
  docs/asciidoc/modules/ROOT/pages/index.adoc
  docs/asciidoc/modules/ROOT/pages/introduction/index.adoc
  docs/asciidoc/modules/ROOT/pages/misc/index.adoc
  docs/asciidoc/modules/ROOT/pages/operational/index.adoc
  docs/asciidoc/modules/ROOT/pages/overview/index.adoc
  docs/asciidoc/modules/ROOT/pages/transaction/index.adoc
  docs/asciidoc/modules/ROOT/pages/virtual-resource/index.adoc
  docs/asciidoc/modules/ROOT/partials/docker.adoc
  docs/asciidoc/modules/ROOT/partials/email-dependencies.adoc
  docs/asciidoc/modules/ROOT/partials/mongodb-dependencies.adoc
  docs/asciidoc/modules/ROOT/partials/nlp-dependencies.adoc
Labels: cherry-picked, 5.0

#3313 Rename APOC library to APOC Extended library (#3308)
  docs/asciidoc/functions.adoc
  docs/asciidoc/jmh.adoc
  docs/asciidoc/modules/ROOT/pages/config/index.adoc
  docs/asciidoc/modules/ROOT/pages/cypher-execution/index.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/bolt-neo4j.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/couchbase.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/index.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/redis.adoc
  docs/asciidoc/modules/ROOT/pages/database-introspection/index.adoc
  docs/asciidoc/modules/ROOT/pages/export/index.adoc
  docs/asciidoc/modules/ROOT/pages/general-considerations/index.adoc
  docs/asciidoc/modules/ROOT/pages/graph-updates/index.adoc
  docs/asciidoc/modules/ROOT/pages/import/index.adoc
  docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
  docs/asciidoc/modules/ROOT/pages/index.adoc
  docs/asciidoc/modules/ROOT/pages/introduction/index.adoc
  docs/asciidoc/modules/ROOT/pages/misc/index.adoc
  docs/asciidoc/modules/ROOT/pages/operational/index.adoc
  docs/asciidoc/modules/ROOT/pages/overview/index.adoc
  docs/asciidoc/modules/ROOT/pages/transaction/index.adoc
  docs/asciidoc/modules/ROOT/pages/virtual-resource/index.adoc
  docs/asciidoc/modules/ROOT/partials/docker.adoc
  docs/asciidoc/modules/ROOT/partials/email-dependencies.adoc
  docs/asciidoc/modules/ROOT/partials/mongodb-dependencies.adoc
  docs/asciidoc/modules/ROOT/partials/nlp-dependencies.adoc
Labels: cherry-picked, 5.2

#3312 Rename APOC library to APOC Extended library (#3308)
  docs/asciidoc/functions.adoc
  docs/asciidoc/jmh.adoc
  docs/asciidoc/modules/ROOT/pages/config/index.adoc
  docs/asciidoc/modules/ROOT/pages/cypher-execution/index.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/bolt-neo4j.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/couchbase.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/index.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/redis.adoc
  docs/asciidoc/modules/ROOT/pages/database-introspection/index.adoc
  docs/asciidoc/modules/ROOT/pages/export/index.adoc
  docs/asciidoc/modules/ROOT/pages/general-considerations/index.adoc
  docs/asciidoc/modules/ROOT/pages/graph-updates/index.adoc
  docs/asciidoc/modules/ROOT/pages/import/index.adoc
  docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
  docs/asciidoc/modules/ROOT/pages/index.adoc
  docs/asciidoc/modules/ROOT/pages/introduction/index.adoc
  docs/asciidoc/modules/ROOT/pages/misc/index.adoc
  docs/asciidoc/modules/ROOT/pages/operational/index.adoc
  docs/asciidoc/modules/ROOT/pages/overview/index.adoc
  docs/asciidoc/modules/ROOT/pages/transaction/index.adoc
  docs/asciidoc/modules/ROOT/pages/virtual-resource/index.adoc
  docs/asciidoc/modules/ROOT/partials/docker.adoc
  docs/asciidoc/modules/ROOT/partials/email-dependencies.adoc
  docs/asciidoc/modules/ROOT/partials/mongodb-dependencies.adoc
  docs/asciidoc/modules/ROOT/partials/nlp-dependencies.adoc
Labels: cherry-picked, 5.1

#3310 Add 5.1.0 package to installation page
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
Labels: team-cypher-surface, 5.3

#3314 Reallocate Youtube tutorial to Appendix page (#3309)
  docs/asciidoc/modules/ROOT/nav.adoc
  docs/asciidoc/modules/ROOT/pages/appendix/apoc-video-tutorial.adoc
  docs/asciidoc/modules/ROOT/pages/appendix/index.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/load-jdbc.adoc
  docs/asciidoc/modules/ROOT/pages/graph-updates/ttl.adoc
  docs/asciidoc/modules/ROOT/pages/introduction/index.adoc
Labels: cherry-picked, 5.0

#3316 Reallocate Youtube tutorial to Appendix page (#3309)
  docs/asciidoc/modules/ROOT/nav.adoc
  docs/asciidoc/modules/ROOT/pages/appendix/apoc-video-tutorial.adoc
  docs/asciidoc/modules/ROOT/pages/appendix/index.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/load-jdbc.adoc
  docs/asciidoc/modules/ROOT/pages/graph-updates/ttl.adoc
  docs/asciidoc/modules/ROOT/pages/introduction/index.adoc
Labels: cherry-picked, 5.2

#3317 Add 5.1.0 package to installation page (#3310)
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
Labels: cherry-picked, 5.0

#3319 Add 5.1.0 package to installation page (#3310)
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
Labels: cherry-picked, 5.2

#3318 Add 5.1.0 package to installation page (#3310)
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
Labels: cherry-picked, 5.1

#3183 [gRNAet7B] Fixes trigger procedures in clusters
  core/src/main/java/apoc/ApocConfig.java
  core/src/main/java/apoc/CoreApocGlobalComponents.java
  core/src/main/java/apoc/trigger/Trigger.java
  core/src/main/java/apoc/trigger/TriggerHandler.java
  core/src/main/java/apoc/trigger/TriggerHandlerWrite.java
  core/src/main/java/apoc/trigger/TriggerNewProcedures.java
  core/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/trigger/TriggerClusterRoutingTest.java
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
  core/src/test/java/apoc/trigger/TriggerRestartTest.java
  core/src/test/java/apoc/trigger/TriggerTestUtil.java
  full/src/test/java/apoc/trigger/TriggerClusterTest.java
  full/src/test/java/apoc/trigger/TriggerExtendedTest.java
  full/src/test/java/apoc/trigger/TriggerNewProceduresExtendedTest.java
  test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java
  test-utils/src/main/java/apoc/util/TestUtil.java
  test-utils/src/main/java/apoc/util/TestcontainersCausalCluster.java
Labels: do_not_merge, 4.4, not-ready-for-merge

#3321 Fix to APOC version table
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
Labels: 5.1

#3322 fix installation page 5.0
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
Labels: 5.0

#3305 [7kTG3Jb3] Upgraded jsoup to v.1.15.3 to mitigate CVE-2022-36033
  full/build.gradle
  full/src/main/java/apoc/load/LoadHtml.java
Labels: 4.4, team-cypher-surface

#3307 [7kTG3Jb3] Upgraded jsoup to v.1.15.3 to mitigate CVE-2022-36033
  full/build.gradle
  full/src/main/java/apoc/load/LoadHtml.java
Labels: cherry-picked, 4.3, team-cypher-surface

#3323 [gRNAet7B] Try fix flaky TriggerClusterRoutingTest
  core/src/test/java/apoc/trigger/TriggerClusterRoutingTest.java
  core/src/test/java/apoc/trigger/TriggerTestUtil.java
  full/src/test/java/apoc/trigger/TriggerNewProceduresExtendedTest.java
Labels: 4.4

#3332 [4Bmcyc2U] Fix ignored ExportCypherTests
  core/src/main/java/apoc/export/cypher/ExportCypher.java
  core/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Labels: cherry-picked, 4.3

#3331 [4Bmcyc2U] Fix ignored ExportCypherTests
  core/src/main/java/apoc/export/cypher/ExportCypher.java
  core/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Labels: cherry-picked, 4.4

#3337 update APOC documentation title (#3334)
  docs/asciidoc/antora.yml
Labels: cherry-picked, 5.0

#3338 update APOC documentation title (#3334)
  docs/asciidoc/antora.yml
Labels: cherry-picked, 5.1

#3328 [4Bmcyc2U] Fix ignored testGeocodeGoogle (neo4j/apoc#239)
  core/src/test/java/apoc/spatial/GeocodeTest.java
Labels: cherry-picked, 4.4

#3327 [4Bmcyc2U] Try fixing flaky testDeadlockException for 4.3 (neo4j/apoc#238)
  core/src/test/java/apoc/refactor/rename/RenameTest.java
Labels: cherry-picked, 4.3

#3329 [4Bmcyc2U] Fix ignored testGeocodeGoogle (neo4j/apoc#239)
  core/src/test/java/apoc/spatial/GeocodeTest.java
Labels: cherry-picked, 4.3

#3342 [4Bmcyc2U] Un-ignore and clean up working test.
  core/src/test/java/apoc/meta/MetaEnterpriseFeaturesTest.java
Labels: cherry-picked, 4.3

#3341 [4Bmcyc2U] Un-ignore and clean up working test.
  core/src/test/java/apoc/meta/MetaEnterpriseFeaturesTest.java
Labels: cherry-picked, 4.4

#3343 [eRGoCYQI] Upgrades dependencies
  build.gradle
  core/build.gradle
  extra-dependencies/hadoop/build.gradle
  full/build.gradle
  test-utils/build.gradle
Labels: 4.3, team-cypher-surface

#3326 [4Bmcyc2U] Try fixing flaky testDeadlockException for 4.4 (neo4j/apoc#238)
  core/src/test/java/apoc/refactor/rename/RenameTest.java
Labels: cherry-picked, 4.4

#3347 Update JaroWinkler examples
  docs/asciidoc/modules/ROOT/partials/usage/apoc.text.jaroWinklerDistance.adoc
Labels: bug, docs, cherry-picked, 4.3, team-cypher-surface

#3346 Update JaroWinkler examples
  docs/asciidoc/modules/ROOT/partials/usage/apoc.text.jaroWinklerDistance.adoc
Labels: bug, docs, cherry-picked, 4.4, team-cypher-surface
