Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2022-08, with the labels that each got.

#3085 NO AUTO Moves coll procedures to core only
  .github/workflows/CI.yaml
  core/build.gradle
  core/src/main/java/apoc/coll/Coll.java
  core/src/test/java/apoc/coll/ArrayListTest.java
  core/src/test/java/apoc/coll/CollTest.java
  core/src/test/java/apoc/coll/EqualityTest.java
  core/src/test/java/apoc/hashing/FingerprintingTest.java
  core/src/test/java/apoc/help/HelpTest.java
  core/src/test/java/apoc/refactor/CloneSubgraphTest.java
  full/src/test/java/apoc/ApocSplitTest.java
Labels: 5.0, team-cypher-surface

#3080 [SECURITY] Fix Partial Path Traversal Vulnerability
  core/src/main/java/apoc/log/Neo4jLogStream.java
Labels: bug, to-cherry-pick, 4.4, team-cypher-surface

#3093 vuln-fix: Partial Path Traversal Vulnerability (#3080)
  core/src/main/java/apoc/log/Neo4jLogStream.java
Labels: bug, cherry-picked, 4.3

#3094 vuln-fix: Partial Path Traversal Vulnerability (#3080)
  common/src/main/java/apoc/log/Neo4jLogStream.java
Labels: bug, cherry-picked, 5.0

#3104 NO AUTO Ignores some container tests until their startup is fixed
  core/src/test/java/apoc/ApocSplitTest.java
  full/src/test/java/apoc/ApocSplitTest.java
Labels: 5.0, team-cypher-surface

#3102 NO AUTO Strips refactor and periodic procedures from full
  .gitignore
  common/src/main/java/apoc/Pools.java
  common/src/main/java/apoc/periodic/PeriodicUtils.java
  core/src/main/java/apoc/periodic/Periodic.java
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/main/java/apoc/refactor/rename/Rename.java
  core/src/test/java/apoc/periodic/BatchModeTest.java
  core/src/test/java/apoc/periodic/PeriodicTest.java
  core/src/test/java/apoc/periodic/PeriodicUtilsTest.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
  core/src/test/java/apoc/refactor/rename/RenameTest.java
  core/src/test/java/apoc/refactor/util/PropertiesManagerTest.java
  full/build.gradle
  full/src/main/java/apoc/uuid/Uuid.java
  full/src/test/java/apoc/ApocSplitTest.java
  full/src/test/java/apoc/uuid/UUIDMultiDbTest.java
  full/src/test/java/apoc/uuid/UUIDTest.java
Labels: 5.0, team-cypher-surface, split

#3086 NO AUTO Moves export procedures to core only
  core/src/main/java/apoc/export/arrow/ArrowConfig.java
  core/src/main/java/apoc/export/arrow/ArrowUtils.java
  core/src/main/java/apoc/export/arrow/ExportArrow.java
  core/src/main/java/apoc/export/arrow/ExportArrowFileStrategy.java
  core/src/main/java/apoc/export/arrow/ExportArrowService.java
  core/src/main/java/apoc/export/arrow/ExportArrowStrategy.java
  core/src/main/java/apoc/export/arrow/ExportArrowStreamStrategy.java
  core/src/main/java/apoc/export/arrow/ExportGraphFileStrategy.java
  core/src/main/java/apoc/export/arrow/ExportGraphStrategy.java
  core/src/main/java/apoc/export/arrow/ExportGraphStreamStrategy.java
  core/src/main/java/apoc/export/arrow/ExportResultFileStrategy.java
  core/src/main/java/apoc/export/arrow/ExportResultStrategy.java
  core/src/main/java/apoc/export/arrow/ExportResultStreamStrategy.java
  core/src/main/java/apoc/export/csv/CsvEntityLoader.java
  core/src/main/java/apoc/export/csv/CsvFormat.java
  core/src/main/java/apoc/export/csv/CsvHeaderField.java
  core/src/main/java/apoc/export/csv/CsvHeaderFields.java
  core/src/main/java/apoc/export/csv/CsvLoaderConfig.java
  core/src/main/java/apoc/export/csv/CsvLoaderConstants.java
  core/src/main/java/apoc/export/csv/CsvPropertyConverter.java
  core/src/main/java/apoc/export/csv/ExportCSV.java
  core/src/main/java/apoc/export/csv/ImportCsv.java
  core/src/main/java/apoc/export/cypher/ExportCypher.java
  core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
  core/src/main/java/apoc/export/graphml/ExportGraphML.java
  core/src/main/java/apoc/export/graphml/XmlGraphMLFormat.java
  core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java
  core/src/main/java/apoc/export/graphml/XmlGraphMLWriter.java
  core/src/main/java/apoc/export/graphml/XmlNodeExport.java
  core/src/main/java/apoc/export/json/ExportJson.java
  core/src/main/java/apoc/export/json/ImportJson.java
  core/src/main/java/apoc/export/json/ImportJsonConfig.java
  core/src/main/java/apoc/export/json/JsonFormat.java
  core/src/main/java/apoc/export/json/JsonFormatSerializer.java
  core/src/main/java/apoc/export/json/JsonImporter.java
  core/src/test/java/apoc/export/ExportCoreSecurityTest.java
  core/src/test/java/apoc/export/ExportS3PerformanceTest.java
  core/src/test/java/apoc/export/ExportStreamsStatementsTest.java
  core/src/test/java/apoc/export/arrow/ArrowTest.java
  core/src/test/java/apoc/export/csv/CsvHeaderFieldTests.java
  core/src/test/java/apoc/export/csv/CsvTestUtil.java
  core/src/test/java/apoc/export/csv/ExportCsvIT.java
  core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java
  core/src/test/java/apoc/export/csv/ExportCsvS3Test.java
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
  core/src/test/java/apoc/export/csv/ImportCsvLdbcTest.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherMultiRelTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherS3Test.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherTestUtils.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLS3Test.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  core/src/test/java/apoc/export/json/ExportJsonS3Test.java
  core/src/test/java/apoc/export/json/ExportJsonTest.java
  core/src/test/java/apoc/export/json/ImportJsonTest.java
  core/src/test/resources/csv-inputs/.gitignore
  full/build.gradle
  full/src/test/java/apoc/ApocSplitTest.java
Labels: 5.0, team-cypher-surface, split

#3087 NO AUTO Moves map, math, text, number agg, convert procedures to core only
  common/src/main/java/apoc/convert/utils/ConvertUtils.java
  common/src/main/java/apoc/graph/document/builder/LabelBuilder.java
  common/src/main/java/apoc/trigger/TriggerMetadata.java
  common/src/main/java/apoc/util/Util.java
  core/src/main/java/apoc/agg/CollAggregation.java
  core/src/main/java/apoc/agg/Graph.java
  core/src/main/java/apoc/agg/MaxAndMinItems.java
  core/src/main/java/apoc/agg/Median.java
  core/src/main/java/apoc/agg/Percentiles.java
  core/src/main/java/apoc/agg/Product.java
  core/src/main/java/apoc/agg/Statistics.java
  core/src/main/java/apoc/convert/Convert.java
  core/src/main/java/apoc/convert/ConvertConfig.java
  core/src/main/java/apoc/convert/Json.java
  core/src/main/java/apoc/map/Maps.java
  core/src/main/java/apoc/math/Maths.java
  core/src/main/java/apoc/math/Regression.java
  core/src/main/java/apoc/number/ArabicRoman.java
  core/src/main/java/apoc/number/Numbers.java
  core/src/main/java/apoc/number/exact/Exact.java
  core/src/main/java/apoc/text/Phonetic.java
  core/src/main/java/apoc/text/SorensenDiceCoefficient.java
  core/src/main/java/apoc/text/Strings.java
  core/src/test/java/apoc/agg/CollAggregationTest.java
  core/src/test/java/apoc/agg/GraphAggregationTest.java
  core/src/test/java/apoc/agg/MaxAndMinItemsAggregationTest.java
  core/src/test/java/apoc/agg/MedianTest.java
  core/src/test/java/apoc/agg/PercentilesTest.java
  core/src/test/java/apoc/agg/ProductAggregationTest.java
  core/src/test/java/apoc/agg/StatisticsTest.java
  core/src/test/java/apoc/convert/ConvertJsonTest.java
  core/src/test/java/apoc/convert/ConvertTest.java
  core/src/test/java/apoc/cypher/CypherTest.java
  core/src/test/java/apoc/load/LoadJsonTest.java
  core/src/test/java/apoc/map/MapsTest.java
  core/src/test/java/apoc/math/MathsTest.java
  core/src/test/java/apoc/math/RegressionTest.java
  core/src/test/java/apoc/number/ArabicRomanTest.java
  core/src/test/java/apoc/number/NumbersTest.java
  core/src/test/java/apoc/number/exact/ExactTest.java
  core/src/test/java/apoc/text/PhoneticTest.java
  core/src/test/java/apoc/text/SorensenDiceCoefficientTest.java
  core/src/test/java/apoc/text/StringCleanTest.java
  core/src/test/java/apoc/text/StringsTest.java
  full/src/test/java/apoc/ApocSplitTest.java
Labels: 5.0, team-cypher-surface, split

#3100 NO AUTO Moves nodes, create, refactor, trigger tests to core only
  build.gradle
  core/src/main/java/apoc/create/Create.java
  core/src/main/java/apoc/nodes/Grouping.java
  core/src/main/java/apoc/nodes/Nodes.java
  core/src/main/java/apoc/nodes/NodesConfig.java
  core/src/main/java/apoc/refactor/NodeRefactorResult.java
  core/src/main/java/apoc/refactor/RefactorResult.java
  core/src/main/java/apoc/refactor/RelationshipRefactorResult.java
  core/src/main/java/apoc/refactor/util/PropertiesManager.java
  core/src/main/java/apoc/refactor/util/RefactorConfig.java
  core/src/main/java/apoc/refactor/util/RefactorUtil.java
  core/src/main/java/apoc/trigger/Trigger.java
  core/src/test/java/apoc/create/CreateTest.java
  core/src/test/java/apoc/diff/DiffTest.java
  core/src/test/java/apoc/nodes/GroupingTest.java
  core/src/test/java/apoc/nodes/NodesTest.java
  core/src/test/java/apoc/trigger/TriggerDisabledTest.java
  core/src/test/java/apoc/trigger/TriggerRestartTest.java
  core/src/test/java/apoc/trigger/TriggerTest.java
  full/src/test/java/apoc/ApocSplitTest.java
Labels: 5.0, team-cypher-surface, not-ready-for-merge, split

#3105 NO AUTO Strips algo, meta, util, path procs from full
  common/src/main/java/apoc/algo/PathFindingUtils.java
  common/src/main/java/apoc/export/util/MetaInformation.java
  common/src/main/java/apoc/load/Mapping.java
  common/src/main/java/apoc/meta/ConstraintTracker.java
  common/src/main/java/apoc/meta/Types.java
  common/src/main/java/apoc/meta/tablesforlabels/PropertyContainerProfile.java
  core/src/main/java/apoc/algo/Cover.java
  core/src/main/java/apoc/algo/PathFinding.java
  core/src/main/java/apoc/convert/Convert.java
  core/src/main/java/apoc/convert/Json.java
  core/src/main/java/apoc/export/arrow/ExportArrowStrategy.java
  core/src/main/java/apoc/export/arrow/ExportResultStrategy.java
  core/src/main/java/apoc/export/csv/CsvHeaderField.java
  core/src/main/java/apoc/export/json/JsonFormat.java
  core/src/main/java/apoc/meta/Meta.java
  core/src/main/java/apoc/path/PathExplorer.java
  core/src/main/java/apoc/util/Utils.java
  core/src/test/java/apoc/algo/CoverTest.java
  core/src/test/java/apoc/algo/PathFindingTest.java
  core/src/test/java/apoc/cypher/CypherInitializerTest.java
  core/src/test/java/apoc/export/csv/CsvHeaderFieldTests.java
  core/src/test/java/apoc/meta/CollEnterpriseTest.java
  core/src/test/java/apoc/meta/MetaEnterpriseFeaturesTest.java
  core/src/test/java/apoc/meta/MetaTest.java
  core/src/test/java/apoc/path/ExpandPathTest.java
  core/src/test/java/apoc/path/LabelSequenceTest.java
  core/src/test/java/apoc/path/NodeFilterTest.java
  core/src/test/java/apoc/path/PathsTest.java
  core/src/test/java/apoc/path/RelSequenceTest.java
  core/src/test/java/apoc/path/SequenceTest.java
  core/src/test/java/apoc/path/SubgraphTest.java
  core/src/test/java/apoc/util/UtilTest.java
  core/src/test/java/apoc/util/UtilsTest.java
  full/src/main/java/apoc/algo/PathFindingFull.java
  full/src/main/java/apoc/load/LoadXls.java
  full/src/test/java/apoc/ApocSplitTest.java
Labels: 5.0, team-cypher-surface, split

#3110 NO AUTO Strips atomic, hashing, temporal, date, index, neighbours, merge from full
  common/src/main/java/apoc/date/DateUtils.java
  common/src/main/java/apoc/result/KernelInfoResult.java
  core/src/main/java/apoc/atomic/Atomic.java
  core/src/main/java/apoc/atomic/util/AtomicUtils.java
  core/src/main/java/apoc/date/Date.java
  core/src/main/java/apoc/hashing/Fingerprinting.java
  core/src/main/java/apoc/hashing/FingerprintingConfig.java
  core/src/main/java/apoc/index/QueuePoisoningCollector.java
  core/src/main/java/apoc/index/SchemaIndex.java
  core/src/main/java/apoc/merge/Merge.java
  core/src/main/java/apoc/neighbors/Neighbors.java
  core/src/main/java/apoc/schema/SchemaConfig.java
  core/src/main/java/apoc/schema/Schemas.java
  core/src/main/java/apoc/spatial/Distance.java
  core/src/main/java/apoc/spatial/Geocode.java
  core/src/main/java/apoc/temporal/TemporalProcedures.java
  core/src/test/java/apoc/atomic/AtomicTest.java
  core/src/test/java/apoc/date/DateTest.java
  core/src/test/java/apoc/index/SchemaIndexTest.java
  core/src/test/java/apoc/merge/MergeTest.java
  core/src/test/java/apoc/neighbors/NeighborsTest.java
  core/src/test/java/apoc/schema/SchemasTest.java
  core/src/test/java/apoc/spatial/DistanceTest.java
  core/src/test/java/apoc/spatial/GeocodeTest.java
  core/src/test/java/apoc/spatial/SpatialTest.java
  core/src/test/java/apoc/temporal/TemporalProceduresTest.java
  full/src/main/java/apoc/ttl/TTL.java
  full/src/test/java/apoc/ApocSplitTest.java
Labels: 5.0, team-cypher-surface, split

#3113 NO AUTO Strips cypher, lock, graph, lock, path, search procedures from full
  common/src/main/java/apoc/cypher/CypherUtils.java
  common/src/main/java/apoc/graph/GraphsUtils.java
  core/src/main/java/apoc/cypher/Cypher.java
  core/src/main/java/apoc/cypher/CypherFunctions.java
  core/src/main/java/apoc/cypher/Timeboxed.java
  core/src/main/java/apoc/graph/Graphs.java
  core/src/main/java/apoc/lock/Lock.java
  core/src/main/java/apoc/path/LabelMatcher.java
  core/src/main/java/apoc/path/LabelMatcherGroup.java
  core/src/main/java/apoc/path/LabelSequenceEvaluator.java
  core/src/main/java/apoc/path/NodeEvaluators.java
  core/src/main/java/apoc/path/Paths.java
  core/src/main/java/apoc/path/RelationshipSequenceExpander.java
  core/src/main/java/apoc/search/ParallelNodeSearch.java
  core/src/test/java/apoc/graph/GraphsTest.java
  core/src/test/java/apoc/lock/LockTest.java
  core/src/test/java/apoc/search/ParallelNodeSearchTest.java
  full/src/main/java/apoc/cypher/CypherExtended.java
  full/src/main/java/apoc/gephi/Gephi.java
  full/src/test/java/apoc/ApocSplitTest.java
Labels: 5.0, team-cypher-surface, split

#3114 NO AUTO Strips load, warmup, stats, bitwise, scoring, log, label from full
  common/src/main/java/apoc/load/LoadJsonUtils.java
  core/databases.xml
  core/src/main/java/apoc/bitwise/BitwiseOperations.java
  core/src/main/java/apoc/data/url/ExtractURL.java
  core/src/main/java/apoc/diff/Diff.java
  core/src/main/java/apoc/label/Label.java
  core/src/main/java/apoc/load/LoadArrow.java
  core/src/main/java/apoc/load/LoadJson.java
  core/src/main/java/apoc/load/SkipWhitespaceInputStream.java
  core/src/main/java/apoc/load/Xml.java
  core/src/main/java/apoc/log/Neo4jLogStream.java
  core/src/main/java/apoc/scoring/Scoring.java
  core/src/main/java/apoc/stats/DegreeDistribution.java
  core/src/main/java/apoc/stats/DegreeUtil.java
  core/src/main/java/apoc/warmup/Warmup.java
  core/src/test/java/apoc/bitwise/BitwiseOperationsTest.java
  core/src/test/java/apoc/data/url/ExtractURLTest.java
  core/src/test/java/apoc/example/Examples.java
  core/src/test/java/apoc/example/ExamplesTest.java
  core/src/test/java/apoc/label/LabelTest.java
  core/src/test/java/apoc/load/LoadCoreSecurityTest.java
  core/src/test/java/apoc/load/SimpleXmlTest.java
  core/src/test/java/apoc/load/SkipWhitespaceInputStreamTest.java
  core/src/test/java/apoc/load/XmlTest.java
  core/src/test/java/apoc/load/relative/LoadRelativePathTest.java
  core/src/test/java/apoc/log/Neo4jLogStreamTest.java
  core/src/test/java/apoc/scoring/ScoringTest.java
  core/src/test/java/apoc/stats/DegreeDistributionTest.java
  core/src/test/java/apoc/warmup/WarmupTest.java
  core/src/test/resources/map.json
  core/src/test/resources/testload.tar
  core/src/test/resources/testload.tar.gz
  core/src/test/resources/testload.tgz
  core/src/test/resources/testload.zip
  core/src/test/resources/xml/books.xml
  core/src/test/resources/xml/booksResult.txt
  core/src/test/resources/xml/databases.xml
  core/src/test/resources/xml/humboldt_soemmering01_1791.TEI-P5-shortened.xml
  core/src/test/resources/xml/missingExternalDTD.xml
  core/src/test/resources/xml/mixedcontent.xml
  core/src/test/resources/xml/singleLine.xml
  core/src/test/resources/xml/xxe.xml
  full/src/main/java/apoc/es/ElasticSearch.java
  full/src/test/java/apoc/ApocSplitTest.java
Labels: do_not_merge, 5.0, team-cypher-surface, split

#3115 NO AUTO Fixes SchemasEnterpriseFeaturesTest wrong assertion and ModelTest protocol
  core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
  full/src/test/java/apoc/model/ModelTest.java
Labels: bug, team-cypher-surface, 4.1

#3116 NO AUTO Adds blocklist for load methods
  core/build.gradle
  core/src/main/java/apoc/ApocConfig.java
  core/src/main/java/apoc/ApocSettings.java
  core/src/main/java/apoc/load/Xml.java
  core/src/main/java/apoc/util/FileUtils.java
  core/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/load/LoadJsonTest.java
  readme.adoc
Labels: cherry-picked, 4.3, team-cypher-surface

#3117 NO AUTO Adds blocklist for load methods
  core/build.gradle
  core/src/main/java/apoc/ApocConfig.java
  core/src/main/java/apoc/ApocSettings.java
  core/src/main/java/apoc/load/Xml.java
  core/src/main/java/apoc/util/FileUtils.java
  core/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/load/LoadJsonTest.java
  readme.adoc
Labels: cherry-picked, 4.2, team-cypher-surface

#3119 NO AUTO Adds blocklist for load methods
  build.gradle
  src/main/java/apoc/ApocConfiguration.java
  src/main/java/apoc/util/FileUtils.java
  src/main/java/apoc/util/Util.java
  src/test/java/apoc/load/LoadJsonTest.java
Labels: cherry-picked, 3.5, team-cypher-surface

#3122 NO AUTO Bumps neo4j and apoc version
  build.gradle
  docs/build.gradle
  extra-dependencies/build.gradle
Labels: team-cypher-surface, 4.1

#3121 NO AUTO Bumps neo4j and apoc version
  build.gradle
  docs/build.gradle
  extra-dependencies/build.gradle
Labels: 4.2, team-cypher-surface

#3120 NO AUTO Bumps neo4j and apoc version
  build.gradle
  docs/build.gradle
  extra-dependencies/build.gradle
Labels: 4.3, team-cypher-surface

#3078 NO AUTO Deprecate apoc.create.uuid and apoc.create.uuids
  core/src/main/java/apoc/create/Create.java
  docs/asciidoc/antora.yml
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.create.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.create.uuid.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.create.uuid.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.create.uuidBase64.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.create.uuidBase64ToHex.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.create.uuidHexToBase64.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/documentation.csv
  docs/asciidoc/modules/ROOT/pages/deprecations-and-additions/index.adoc
  docs/asciidoc/modules/ROOT/pages/graph-updates/uuid.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.create/apoc.create.uuid.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.create/apoc.create.uuidBase64.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.create/apoc.create.uuidBase64ToHex.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.create/apoc.create.uuidHexToBase64.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.create/apoc.create.uuids.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.create/index.adoc
  docs/asciidoc/modules/ROOT/pages/virtual/virtual-graph.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.create.uuidBase64ToHex.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.create.uuidHexToBase64.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.graph.fromDocument.adoc
  docs/guide.html
  docs/index.html
Labels: 5.0, team-cypher-surface

#3123 NO AUTO Does a tidy-up and clean-up after splitting most of the code
  .gitignore
  build.gradle
  common/build.gradle
  common/src/main/java/apoc/convert/ConvertUtils.java
  common/src/main/java/apoc/trigger/TriggerMetadata.java
  common/src/main/java/apoc/util/Util.java
  core/build.gradle
  core/src/main/java/apoc/CoreApocGlobalComponents.java
  core/src/main/java/apoc/convert/Convert.java
  core/src/main/java/apoc/convert/Json.java
  core/src/main/java/apoc/example/Examples.java
  core/src/main/java/apoc/load/LoadJson.java
  full/build.gradle
  full/src/main/java/apoc/export/xls/XlsExportConfig.java
  full/src/main/java/apoc/generate/BaseGraphGenerator.java
  full/src/main/java/apoc/generate/GraphGenerator.java
  full/src/main/java/apoc/generate/Neo4jGraphGenerator.java
  full/src/main/java/apoc/generate/config/BarabasiAlbertConfig.java
  full/src/main/java/apoc/generate/config/BasicGeneratorConfig.java
  full/src/main/java/apoc/generate/config/DistributionBasedConfig.java
  full/src/main/java/apoc/generate/config/ErdosRenyiConfig.java
  full/src/main/java/apoc/generate/config/GeneratorConfiguration.java
  full/src/main/java/apoc/generate/config/NumberOfNodesBasedConfig.java
  full/src/main/java/apoc/generate/config/RelationshipGeneratorConfig.java
  full/src/main/java/apoc/generate/config/WattsStrogatzConfig.java
  full/src/main/java/apoc/generate/distribution/DegreeDistribution.java
  full/src/main/java/apoc/generate/distribution/MutableDegreeDistribution.java
  full/src/main/java/apoc/generate/distribution/MutableSimpleDegreeDistribution.java
  full/src/main/java/apoc/generate/distribution/SimpleDegreeDistribution.java
  full/src/main/java/apoc/generate/node/DefaultNodeCreator.java
  full/src/main/java/apoc/generate/node/NodeCreator.java
  full/src/main/java/apoc/generate/relationship/BarabasiAlbertRelationshipGenerator.java
  full/src/main/java/apoc/generate/relationship/BaseRelationshipGenerator.java
  full/src/main/java/apoc/generate/relationship/CompleteGraphRelationshipGenerator.java
  full/src/main/java/apoc/generate/relationship/DefaultRelationshipCreator.java
  full/src/main/java/apoc/generate/relationship/ErdosRenyiRelationshipGenerator.java
  full/src/main/java/apoc/generate/relationship/RelationshipCreator.java
  full/src/main/java/apoc/generate/relationship/RelationshipGenerator.java
  full/src/main/java/apoc/generate/relationship/SimpleGraphRelationshipGenerator.java
  full/src/main/java/apoc/generate/relationship/SocialNetworkRelationshipCreator.java
  full/src/main/java/apoc/generate/relationship/WattsStrogatzRelationshipGenerator.java
  full/src/main/java/apoc/generate/utils/WeightedReservoirSampler.java
  full/src/main/java/apoc/model/ModelConfig.java
  full/src/test/java/apoc/ApocSplitTest.java
  full/src/test/java/apoc/generate/config/BarabasiAlbertConfigTest.java
  full/src/test/java/apoc/generate/config/ErdosRenyiConfigTest.java
  full/src/test/java/apoc/generate/config/NumberOfNodesBasedConfigTest.java
  full/src/test/java/apoc/generate/config/WattsStrogatzConfigTest.java
  full/src/test/java/apoc/generate/relationship/CompleteGraphRelationshipGeneratorTest.java
  full/src/test/java/apoc/generate/relationship/WattsStrogatzRelationshipGeneratorTest.java
  test-utils/build.gradle
Labels: 5.0, team-cypher-surface

#3129 NO AUTO Brings back jackson databind
  build.gradle
Labels: bug, 3.5

#3135 NO AUTO Adds CODEOWNERS
  .github/CODEOWNERS
Labels: 5.0, team-cypher-surface

#3134 NO AUTO Adds CODEOWNERS
  .github/CODEOWNERS
Labels: 4.4, team-cypher-surface

#3133 NO AUTO Adds CODEOWNERS
  .github/CODEOWNERS
Labels: 4.3, team-cypher-surface

#3132 NO AUTO Removes cherry-pick action
  .github/workflows/auto-cherry-pick.yml
Labels: 4.3, team-cypher-surface

#3131 NO AUTO Removes cherry-pick action
  .github/workflows/auto-cherry-pick.yml
Labels: 4.4, team-cypher-surface

#3130 NO AUTO Removes cherry-pick action
  .github/workflows/auto-cherry-pick.yml
Labels: 5.0, team-cypher-surface

#3128 Make SystemDbTest less fragile
  extended/src/test/java/apoc/systemdb/SystemDbTest.java
Labels: 5.0

#2891 Enable APOC Full Testing in CI
  extended/src/test/java/apoc/ApocSplitTest.java
  extended/src/test/java/apoc/CoreExtendedTest.java
  extended/src/test/java/apoc/bolt/BoltTest.java
  extended/src/test/java/apoc/couchbase/CouchbaseTestUtils.java
  extended/src/test/java/apoc/custom/CypherProceduresClusterTest.java
  extended/src/test/java/apoc/cypher/CypherEnterpriseTest.java
  extended/src/test/java/apoc/dv/DataVirtualizationCatalogTest.java
  extended/src/test/java/apoc/es/ElasticSearchTest.java
  extended/src/test/java/apoc/gephi/GephiMock.java
  extended/src/test/java/apoc/gephi/GephiTest.java
  extended/src/test/java/apoc/load/CassandraJdbcTest.java
  extended/src/test/java/apoc/load/LoadCsvTest.java
  extended/src/test/java/apoc/load/LoadGoogleCloudStorageTest.java
  extended/src/test/java/apoc/load/LoadS3Test.java
  extended/src/test/java/apoc/load/MySQLJdbcTest.java
  extended/src/test/java/apoc/load/PostgresJdbcTest.java
  extended/src/test/java/apoc/metrics/MetricsTest.java
  extended/src/test/java/apoc/model/ModelTest.java
  extended/src/test/java/apoc/mongodb/MongoTestBase.java
  extended/src/test/java/apoc/redis/RedisTest.java
  extended/src/test/java/apoc/trigger/TriggerClusterTest.java
  extended/src/test/java/apoc/ttl/TTLMultiDbTest.java
  extended/src/test/java/apoc/util/s3/S3Container.java
  extended/src/test/java/apoc/uuid/UUIDMultiDbTest.java
  extended/src/test/kotlin/apoc/nlp/NodeMatcher.kt
  extended/src/test/kotlin/apoc/nlp/RelationshipMatcher.kt
  extended/src/test/kotlin/apoc/nlp/aws/AWSProceduresAPITest.kt
  extended/src/test/kotlin/apoc/nlp/aws/AWSProceduresAPIWithDummyClientTest.kt
  extended/src/test/kotlin/apoc/nlp/azure/AzureProceduresAPITest.kt
  extended/src/test/kotlin/apoc/nlp/azure/AzureProceduresAPIWithDummyClientTest.kt
  extended/src/test/kotlin/apoc/nlp/gcp/GCPProceduresAPITest.kt
  extended/src/test/kotlin/apoc/nlp/gcp/GCPProceduresAPIWithDummyClientTest.kt
  test-startup/src/test/java/StartupTest.java
  test-utils/src/main/java/apoc/util/GoogleCloudStorageContainerExtension.java
  test-utils/src/main/java/apoc/util/MySQLContainerExtension.java
  test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: bug, to-cherry-pick, 5.0, team-cypher-surface

#3142 Adapt to breaking changes to SHOW DATABASES
  common/src/main/java/apoc/util/Util.java
  extended/src/test/java/apoc/systemdb/SystemDbTest.java
Labels: 5.0, not-ready-for-merge

#3145 Sanitize back-ticks in strings when there is a possibility of Cypher injection
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/main/java/apoc/refactor/rename/Rename.java
  core/src/main/java/apoc/schema/Schemas.java
  core/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
  core/src/test/java/apoc/refactor/rename/RenameTest.java
  core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
  core/src/test/java/apoc/schema/SchemasTest.java
  core/src/test/java/apoc/util/UtilTest.java
Labels: bug, cherry-picked, 4.4, team-cypher-surface

#3144 Sanitize back-ticks in strings when there is a possibility of Cypher injection
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/main/java/apoc/refactor/rename/Rename.java
  core/src/main/java/apoc/schema/Schemas.java
  core/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
  core/src/test/java/apoc/refactor/rename/RenameTest.java
  core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
  core/src/test/java/apoc/schema/SchemasTest.java
  core/src/test/java/apoc/util/UtilTest.java
Labels: bug, cherry-picked, 4.3, team-cypher-surface

#3146 Fixes #2605: The apoc.custom.declareProcedure throws exception "Query results do not match requested output" with some queries
  full/src/main/java/apoc/custom/CypherProcedures.java
  full/src/test/java/apoc/custom/CypherProceduresTest.java
Labels: extended-functionality

#3089 AUTO: Fixes #2992: apoc.diff.nodes() returns list-type properties as different when they are the same (#3083)
  core/src/main/java/apoc/diff/Diff.java
  core/src/test/java/apoc/diff/DiffTest.java
Labels: autocreated

#3076 AUTO: Upgrade commons-configuration2 to 2.8.0 (#3063) (#3074)
  core/build.gradle
  full/build.gradle
Labels: autocreated

#3154 Add private method removed from APOC core
  extended/src/main/java/apoc/uuid/Uuid.java
Labels: 5.0
