Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2022-05, with the labels that each got.

#2830 Create SECURITY.md
  SECURITY.md
Labels: cherry-picked, 3.5

#2829 Create SECURITY.md
  SECURITY.md
Labels: cherry-picked, 4.2

#2828 Create SECURITY.md
  SECURITY.md
Labels: cherry-picked, 4.3

#2827 Create SECURITY.md
  SECURITY.md
Labels: cherry-picked, 5.0

#2818 Missing documentation for apoc.periodic.iterate, regarding the parallel config
  docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/rename-label-type-property.adoc
  docs/asciidoc/modules/ROOT/partials/periodic-iterate.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.periodic.iterate.adoc
Labels: docs

#2793 AUTO: Update readme.adoc
  readme.adoc
Labels: autocreated

#2807 AUTO: Weirdness around custom functions with node return types
  full/src/main/java/apoc/custom/Signatures.java
Labels: autocreated

#2836 AUTO: Update readme.adoc
  readme.adoc
Labels: autocreated

#2657 Var docs fixes for apoc.path.expand, apoc.ttl, apoc.import.csv and apoc.nodes
  docs/asciidoc/modules/ROOT/pages/graph-querying/config-params.adoc
  docs/asciidoc/modules/ROOT/pages/graph-querying/expand-spanning-tree.adoc
  docs/asciidoc/modules/ROOT/pages/graph-querying/expand-subgraph-nodes.adoc
  docs/asciidoc/modules/ROOT/pages/graph-updates/ttl.adoc
  docs/asciidoc/modules/ROOT/pages/import/import-csv.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.nodes/apoc.nodes.group.adoc
  docs/asciidoc/modules/ROOT/pages/virtual/graph-grouping.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.nodes.group.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.nodes.link.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.path.spanningTree.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.path.subgraphNodes.adoc
Labels: docs, 4.4

#2837 AUTO: Var docs fixes: path.expand, ttl, import.csv and group.nodes
  docs/asciidoc/modules/ROOT/pages/graph-querying/config-params.adoc
  docs/asciidoc/modules/ROOT/pages/graph-querying/expand-spanning-tree.adoc
  docs/asciidoc/modules/ROOT/pages/graph-querying/expand-subgraph-nodes.adoc
  docs/asciidoc/modules/ROOT/pages/graph-updates/ttl.adoc
  docs/asciidoc/modules/ROOT/pages/import/import-csv.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.nodes/apoc.nodes.group.adoc
  docs/asciidoc/modules/ROOT/pages/virtual/graph-grouping.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.nodes.group.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.nodes.link.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.path.spanningTree.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.path.subgraphNodes.adoc
Labels: autocreated

#2591 Fixes #2384: Add Scraper procedures to apoc.load.html
  docs/asciidoc/modules/ROOT/pages/import/html.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.html.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.load.html.adoc
  full/src/main/java/apoc/load/HtmlResultInterface.java
  full/src/main/java/apoc/load/LoadHtml.java
  full/src/main/java/apoc/load/PlainText.java
  full/src/main/java/apoc/load/SelectElement.java
  full/src/main/resources/extended.txt
  full/src/test/java/apoc/load/LoadHtmlTest.java
Labels: 4.3, extended-functionality

#2595 Fixes #1372: apoc.load.html ability to read runtime structure of the structure of the page
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.html.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.load.html.adoc
  extra-dependencies/selenium/build.gradle
  extra-dependencies/selenium/gradle/wrapper/gradle-wrapper.jar
  extra-dependencies/selenium/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/selenium/gradlew
  extra-dependencies/selenium/gradlew.bat
  extra-dependencies/selenium/settings.gradle
  extra-dependencies/settings.gradle
  full/build.gradle
  full/src/main/java/apoc/load/LoadHtml.java
  full/src/main/java/apoc/load/LoadHtmlBrowser.java
  full/src/main/java/apoc/load/LoadHtmlConfig.java
  full/src/test/java/apoc/load/LoadHtmlTest.java
  full/src/test/java/apoc/load/LoadHtmlTestParameterized.java
  full/src/test/resources/html/wikipediaWithJs.html
  full/src/test/resources/loadData.js
  full/src/test/resources/wikipediaWithJs.html
Labels: 4.4, extended-functionality

#2596 Fixes #1152 and #2247: Deleting nodes when having an apoc.trigger registered returns Neo.DatabaseError.Transaction.TransactionCommitFailed
  core/src/main/java/apoc/result/VirtualRelationship.java
  core/src/main/java/apoc/trigger/TriggerMetadata.java
  core/src/test/java/apoc/trigger/TriggerTest.java
  docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
  full/src/main/java/apoc/trigger/TriggerExtended.java
  full/src/main/resources/extended.txt
  full/src/test/java/apoc/trigger/TriggerExtendedTest.java
Labels: 4.2, extended-functionality

#2701 Fixes #2664: The apoc.bolt.* procedures are not recognized
  docs/asciidoc/modules/ROOT/pages/database-integration/bolt-neo4j.adoc
  extra-dependencies/bolt/build.gradle
  extra-dependencies/bolt/gradle/wrapper/gradle-wrapper.jar
  extra-dependencies/bolt/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/bolt/gradlew
  extra-dependencies/bolt/gradlew.bat
  extra-dependencies/bolt/settings.gradle
  extra-dependencies/settings.gradle
  full/src/main/java/apoc/bolt/Bolt.java
  full/src/main/java/apoc/bolt/BoltConnection.java
Labels: 4.4, extended-functionality

#2846 AUTO: Deleting nodes when having an apoc.trigger registered returns Neo.DatabaseError.Transaction.TransactionCommitFailed (#2596)
  core/src/main/java/apoc/result/VirtualRelationship.java
  core/src/main/java/apoc/trigger/TriggerMetadata.java
  core/src/test/java/apoc/trigger/TriggerTest.java
  docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
  full/src/main/java/apoc/trigger/TriggerExtended.java
  full/src/main/resources/extended.txt
  full/src/test/java/apoc/trigger/TriggerExtendedTest.java
Labels: autocreated

#2652 Fixes #2223: Add config option for schema exports to retain the index and/or constraint names
  core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
  core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java
  core/src/main/java/apoc/export/util/ExportConfig.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  docs/asciidoc/modules/ROOT/pages/export/cypher.adoc
Labels: 4.2, core-functionality

#2850 Removes jcenter from the repositories used for dependencies
  extra-dependencies/build.gradle
Labels: 4.4, team-cypher-surface

#2852 AUTO: Removes jcenter from the repositories used for dependencies (#2850)
  extra-dependencies/build.gradle
Labels: autocreated

#2851 AUTO: Removes jcenter from the repositories used for dependencies (#2850)
  extra-dependencies/build.gradle
Labels: autocreated

#2856 Update graphml procedure to support tinkerpop format
  core/src/main/java/apoc/export/graphml/XmlGraphMLWriter.java
  core/src/main/java/apoc/export/util/ExportFormat.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  docs/asciidoc/modules/ROOT/pages/export/graphml.adoc
Labels: cherry-picked, 4.3

#2858 AUTO: Update graphml procedure to support tinkerpop format (#2856)
  core/src/main/java/apoc/export/graphml/XmlGraphMLWriter.java
  core/src/main/java/apoc/export/util/ExportFormat.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  docs/asciidoc/modules/ROOT/pages/export/graphml.adoc
Labels: autocreated

#2876 AUTO: Fix for #2867 (#2868)
  core/src/main/java/apoc/periodic/Periodic.java
Labels: autocreated

#2857 AUTO: Update graphml procedure to support tinkerpop format (#2856)
  core/src/main/java/apoc/export/graphml/XmlGraphMLWriter.java
  core/src/main/java/apoc/export/util/ExportFormat.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  docs/asciidoc/modules/ROOT/pages/export/graphml.adoc
Labels: autocreated

#2877 AUTO: Update graphml procedure to support tinkerpop format (#2856) (#2857)
  core/src/main/java/apoc/export/graphml/XmlGraphMLWriter.java
  core/src/main/java/apoc/export/util/ExportFormat.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  docs/asciidoc/modules/ROOT/pages/export/graphml.adoc
Labels: autocreated

#2865 Fixes #1564: Add Apache arrow read / write support (cherry picks)
  core/build.gradle
  core/src/main/java/apoc/convert/Json.java
  core/src/main/java/apoc/export/arrow/ArrowConfig.java
  core/src/main/java/apoc/export/arrow/ArrowUtils.java
  core/src/main/java/apoc/export/arrow/ExportArrow.java
  core/src/main/java/apoc/export/arrow/ExportArrowFileStrategy.java
  core/src/main/java/apoc/export/arrow/ExportArrowService.java
  core/src/main/java/apoc/export/arrow/ExportArrowStrategy.java
  core/src/main/java/apoc/export/arrow/ExportArrowStreamStrategy.java
  core/src/main/java/apoc/export/arrow/ExportGraphFileStrategy.java
  core/src/main/java/apoc/export/arrow/ExportGraphStrategy.java
  core/src/main/java/apoc/export/arrow/ExportGraphStreamStrategy.java
  core/src/main/java/apoc/export/arrow/ExportResultFileStrategy.java
  core/src/main/java/apoc/export/arrow/ExportResultStrategy.java
  core/src/main/java/apoc/export/arrow/ExportResultStreamStrategy.java
  core/src/main/java/apoc/export/util/CountingInputStream.java
  core/src/main/java/apoc/export/util/ProgressReporter.java
  core/src/main/java/apoc/load/LoadArrow.java
  core/src/main/java/apoc/result/ByteArrayResult.java
  core/src/main/java/apoc/result/MapResult.java
  core/src/test/java/apoc/export/arrow/ArrowTest.java
  core/src/test/java/apoc/load/LoadJsonTest.java
  docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.all.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.graph.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.query.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.stream.all.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.stream.graph.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.stream.query.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.import.arrow.stream.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.arrow.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.arrow.stream.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.arrow.all.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.arrow.graph.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.arrow.query.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.arrow.stream.all.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.arrow.stream.graph.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.arrow.stream.query.adoc
  full/build.gradle
  full/src/test/java/apoc/load/LoadCsvTest.java
  test-utils/build.gradle
Labels: cherry-picked, 4.3

#2881 Bumps json path to 2.7.0
  core/build.gradle
Labels: 4.4, team-cypher-surface

#2888 AUTO: Bumps json path to 2.7.0 (#2881)
  core/build.gradle
Labels: autocreated

#2893 Fixes #2269: (4.2) apoc.load procedures don't work anymore with urls containing %
  core/src/main/java/apoc/util/FileUtils.java
Labels: cherry-picked

#2899 Deleting nodes when having an apoc.trigger registered returns Neo.DatabaseError.Transaction.TransactionCommitFailed (#2596)
  core/src/main/java/apoc/result/VirtualRelationship.java
  core/src/main/java/apoc/trigger/TriggerMetadata.java
  core/src/test/java/apoc/trigger/TriggerTest.java
  docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
  full/src/main/java/apoc/trigger/TriggerExtended.java
  full/src/main/resources/extended.txt
  full/src/test/java/apoc/trigger/TriggerExtendedTest.java
Labels: 5.0

#2821 Fixes #2748: apoc.temporal.toZonedTemporal missing in temporal docs page
  docs/asciidoc/modules/ROOT/pages/temporal/datetime-conversions.adoc
  docs/asciidoc/modules/ROOT/pages/temporal/temporal-conversions.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.nodes.cycles.adoc
Labels: docs, 4.4

#2892 Fixes #2223: Add config option for schema exports to retain the index and/or constraint names (#2652)
  core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
  core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java
  core/src/main/java/apoc/export/util/ExportConfig.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  docs/asciidoc/modules/ROOT/pages/export/cypher.adoc
Labels: cherry-picked

#2915 AUTO: Fixes #2223: Add config option for schema exports to retain the index and/or constraint names (#2892)
  core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
  core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java
  core/src/main/java/apoc/export/util/ExportConfig.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  docs/asciidoc/modules/ROOT/pages/export/cypher.adoc
Labels: autocreated

#2875 Missing documentation for apoc.periodic.iterate, regarding the parallel config for dev (#2818)
  docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/rename-label-type-property.adoc
  docs/asciidoc/modules/ROOT/partials/periodic-iterate.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.periodic.iterate.adoc
Labels: cherry-picked

#2872 Missing documentation for apoc.periodic.iterate, regarding the parallel config for 4.3 (#2818)
  docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/rename-label-type-property.adoc
  docs/asciidoc/modules/ROOT/partials/periodic-iterate.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.periodic.iterate.adoc
Labels: cherry-picked

#2916 Fixes #2223: Add config option for schema exports to retain the index constraint names (#2892)
  core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
  core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java
  core/src/main/java/apoc/export/util/ExportConfig.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  docs/asciidoc/modules/ROOT/pages/export/cypher.adoc
Labels: cherry-picked

#2917 AUTO: Fixes #2817: When importing a string array field with a blank value, the attribute value is interpreted as [''] instead of NULL as expected (#2843)
  core/src/main/java/apoc/export/csv/CsvLoaderConfig.java
  core/src/main/java/apoc/export/csv/CsvPropertyConverter.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.import.csv.adoc
Labels: autocreated

#2918 AUTO: Fixes #2817: When importing a string array field with a blank value, the attribute value is interpreted as [''] instead of NULL as expected (#2843)
  core/src/main/java/apoc/export/csv/CsvLoaderConfig.java
  core/src/main/java/apoc/export/csv/CsvPropertyConverter.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.import.csv.adoc
Labels: autocreated

#2921 AUTO: Fixes #2797 and #2780: Graph Refactoring procedures internally handle errors instead of throwing them, leaving half-created results (#2845)
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/refactor/GraphRefactoringEnterpriseTest.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
Labels: autocreated

#2912 AUTO: Fixes #2748: apoc.temporal.toZonedTemporal missing in temporal docs page (#2821)
  docs/asciidoc/modules/ROOT/pages/temporal/datetime-conversions.adoc
  docs/asciidoc/modules/ROOT/pages/temporal/temporal-conversions.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.nodes.cycles.adoc
Labels: autocreated

#2913 AUTO: Fixes #2654: The custom procedure validation fails with integer input types (#2702)
  full/src/main/java/apoc/custom/CypherProcedures.java
  full/src/test/java/apoc/custom/CypherProceduresTest.java
Labels: autocreated

#2908 AUTO: Fixes #2699: The apoc.refactor.mergeNodes remove entities if a list with 2 equal nodes is passed
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
Labels: autocreated

#2905 AUTO: Fixes #2723: apoc.load.xml on large file generates OoM Errors (#2841)
  core/src/test/java/apoc/load/XmlTest.java
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.xml.adoc
Labels: autocreated

#2906 AUTO: Fixes #2723: apoc.load.xml on large file generates OoM Errors (#2841)
  core/src/test/java/apoc/load/XmlTest.java
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.xml.adoc
Labels: autocreated

#2927 AUTO: Fixes #2723: apoc.load.xml on large file generates OoM Errors (#2841)
  core/src/test/java/apoc/load/XmlTest.java
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.xml.adoc
Labels: autocreated

#2907 AUTO: Fixes #2699: The apoc.refactor.mergeNodes remove entities if a list with 2 equal nodes is passed
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
Labels: autocreated

#2926 AUTO: Fixes #2654: The custom procedure validation fails with integer input types (#2702) (#2913)
  full/src/main/java/apoc/custom/CypherProcedures.java
  full/src/test/java/apoc/custom/CypherProceduresTest.java
Labels: autocreated

#2923 AUTO: Fixes #2797 and #2780: Graph Refactoring procedures internally handle errors instead of throwing them, leaving half-created results (#2845) (#2921)
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/refactor/GraphRefactoringEnterpriseTest.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
Labels: autocreated

#2914 AUTO: Fixes #2824: Extend the error message for export procedures to also point out stream:true (#2887)
  core/src/main/java/apoc/ApocConfig.java
  core/src/test/java/apoc/export/ExportStreamsStatementsTest.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  docs/asciidoc/modules/ROOT/partials/enableFileExport.adoc
  docs/asciidoc/modules/ROOT/partials/enableS3Export.adoc
Labels: autocreated

#2874 Missing documentation for apoc.periodic.iterate, regarding the parallel config for 4.1 (#2818)
  docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/rename-label-type-property.adoc
  docs/asciidoc/modules/ROOT/partials/periodic-iterate.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.periodic.iterate.adoc
Labels: cherry-picked

#2928 AUTO: Fixes #2699: The apoc.refactor.mergeNodes remove entities if a list with 2 equal nodes is passed
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
Labels: autocreated

#2949 AUTO: Add admin check for the stream/read-logs functions (#2919)
  core/src/main/java/apoc/log/Neo4jLogStream.java
  docs/asciidoc/modules/ROOT/partials/usage/apoc.log.stream.adoc
Labels: autocreated

#2948 AUTO: Add admin check for the stream/read-logs functions (#2919)
  core/src/main/java/apoc/log/Neo4jLogStream.java
  docs/asciidoc/modules/ROOT/partials/usage/apoc.log.stream.adoc
Labels: autocreated
