Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2022-06, with the labels that each got.

#2965 AUTO: Fix syntax error in APOC trigger docs (#2959)
  docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
Labels: autocreated

#2969 Remove 'GENERAL' and 'TOKEN' prefixes from test
  core/src/test/java/apoc/schema/SchemasTest.java
Labels: 5.0

#2964 AUTO: Fix syntax error in APOC trigger docs (#2959)
  docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
Labels: autocreated

#2974 AUTO: S3 docs small fixes (#2963)
  docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
  docs/asciidoc/modules/ROOT/partials/enableS3Export.adoc
  docs/asciidoc/modules/ROOT/partials/s3-protocol.adoc
Labels: autocreated

#2973 AUTO: S3 docs small fixes (#2963)
  docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
  docs/asciidoc/modules/ROOT/partials/enableS3Export.adoc
  docs/asciidoc/modules/ROOT/partials/s3-protocol.adoc
Labels: autocreated

#2937 Fixes #2895: update apoc.custom.* documentation
  docs/asciidoc/modules/ROOT/pages/cypher-execution/cypher-based-procedures-functions.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.asFunction.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.asProcedure.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.declareFunction.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.declareProcedure.adoc
Labels: docs

#2976 AUTO: Fixes #2895: update apoc.custom.* documentation (#2937)
  docs/asciidoc/modules/ROOT/pages/cypher-execution/cypher-based-procedures-functions.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.asFunction.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.asProcedure.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.declareFunction.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.declareProcedure.adoc
Labels: autocreated

#2943 AUTO: Added apoc.trigger.refresh note in the trigger adoc initial page (#2940)
  docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
Labels: autocreated

#2944 AUTO: Added apoc.trigger.refresh note in the trigger adoc initial page (#2940)
  docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
Labels: autocreated

#2982 NO AUTO: Bumps json path to 2.7.0 (#2881)
  core/build.gradle
Labels: cherry-picked, 5.0, team-cypher-surface

#2939 AUTO: Fixes neo4j-contrib#2659: Apoc.import.graphml doesn't work for edges (#2853)
  core/src/main/java/apoc/export/graphml/ExportGraphML.java
  core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java
  core/src/main/java/apoc/export/graphml/XmlGraphMLWriter.java
  core/src/main/java/apoc/export/graphml/XmlNodeExport.java
  core/src/main/java/apoc/export/util/ExportConfig.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  docs/asciidoc/modules/ROOT/pages/export/graphml.adoc
  docs/asciidoc/modules/ROOT/partials/roundtripSeparatedGraphml.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.import.graphml.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.import.graphml.adoc
Labels: autocreated

#2938 AUTO: Fixes neo4j-contrib#2659: Apoc.import.graphml doesn't work for edges (#2853)
  core/src/main/java/apoc/export/graphml/ExportGraphML.java
  core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java
  core/src/main/java/apoc/export/graphml/XmlGraphMLWriter.java
  core/src/main/java/apoc/export/graphml/XmlNodeExport.java
  core/src/main/java/apoc/export/util/ExportConfig.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  docs/asciidoc/modules/ROOT/pages/export/graphml.adoc
  docs/asciidoc/modules/ROOT/partials/roundtripSeparatedGraphml.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.import.graphml.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.import.graphml.adoc
Labels: autocreated

#3001 Excludes selenium tests in TeamCity
  build.gradle
Labels: 4.4, team-cypher-surface

#3002 AUTO: Excludes selenium tests in TeamCity (#3001)
  build.gradle
  core/src/main/java/apoc/export/graphml/XmlGraphMLWriter.java
Labels: autocreated

#3015 AUTO: Fix for #2909. (#2996)
  full/src/main/java/apoc/custom/CypherProceduresHandler.java
Labels: autocreated

#3016 AUTO: Fix for #2909. (#2996)
  full/src/main/java/apoc/custom/CypherProceduresHandler.java
Labels: autocreated

#3020 Add wait to create databases
  full/src/test/java/apoc/ttl/TTLMultiDbTest.java
Labels: 5.0, team-cypher-surface

#3025 AUTO: Fix testLoadLDAP (#3022)
  full/src/test/java/apoc/load/LoadLdapTest.java
Labels: autocreated

#3026 AUTO: Fix testLoadLDAP (#3022)
  full/src/test/java/apoc/load/LoadLdapTest.java
Labels: autocreated
