Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2022-10, with the labels that each got.

#3190 [hcaaOlXR] Make XML procedures resistant to XXE (#202)
  core/src/main/java/apoc/load/Xml.java
  core/src/test/java/apoc/load/XmlTest.java
Labels: bug, cherry-picked, 4.3

#3189 [hcaaOlXR] Make XML procedures resistant to XXE (#202)
  core/src/main/java/apoc/load/Xml.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
  core/src/test/java/apoc/load/XmlTest.java
  core/src/test/resources/csv-inputs/largeFile.csv
Labels: bug, cherry-picked, 4.4

#3191 [xa1QAhHL] Update documentation to warn about unpredictable procedures in clusters
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.declareFunction.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.declareProcedure.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.removeFunction.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.removeProcedure.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.dv/apoc.dv.catalog.add.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.dv/apoc.dv.catalog.remove.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.install.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.remove.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.removeAll.adoc
Labels: docs, 5.0, team-cypher-surface

#3193 Fixes neo4j/apoc#25: Incorrect behaviours for format durations (neo4j/docs-apoc#29) (neo4j/apoc#179)
  core/src/main/java/apoc/temporal/TemporalProcedures.java
  core/src/main/java/apoc/util/DateFormatUtil.java
  core/src/main/java/apoc/util/DurationFormatUtil.java
  core/src/test/java/apoc/temporal/TemporalProceduresTest.java
  docs/asciidoc/modules/ROOT/partials/usage/apoc.temporal.formatDuration.adoc
Labels: cherry-picked, 4.3

#3198 [hcaaOlXR] Add warnings about MD5 functionality
  docs/asciidoc/modules/ROOT/pages/comparing-graphs/fingerprinting.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.hashing/apoc.hashing.fingerprint.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.hashing/apoc.hashing.fingerprintGraph.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.hashing/apoc.hashing.fingerprinting.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.hashing/index.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.util/apoc.util.md5.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.util/index.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
Labels: docs, cherry-picked, 4.3

#3197 [hcaaOlXR] Add warnings about MD5 functionality
  docs/asciidoc/modules/ROOT/pages/comparing-graphs/fingerprinting.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.hashing/apoc.hashing.fingerprint.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.hashing/apoc.hashing.fingerprintGraph.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.hashing/apoc.hashing.fingerprinting.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.hashing/index.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.util/apoc.util.md5.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.util/index.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
Labels: docs, cherry-picked, 4.4

#3199 [hcaaOlXR] Protect from Billion Laughs
  core/src/main/java/apoc/load/Xml.java
  core/src/test/java/apoc/load/XmlTest.java
  core/src/test/resources/xml/billion_laughs.xml
Labels: bug, cherry-picked, 4.4

#3200 [hcaaOlXR] Protect from Billion Laughs
  core/src/main/java/apoc/load/Xml.java
  core/src/test/java/apoc/load/XmlTest.java
  core/src/test/resources/xml/billion_laughs.xml
Labels: bug, cherry-picked, 4.3

#3192 Fixes neo4j/apoc#25: Incorrect behaviours for format durations (neo4j/docs-apoc#29) (neo4j/apoc#179)
  core/src/main/java/apoc/temporal/TemporalProcedures.java
  core/src/main/java/apoc/util/DateFormatUtil.java
  core/src/main/java/apoc/util/DurationFormatUtil.java
  core/src/test/java/apoc/temporal/TemporalProceduresTest.java
  docs/asciidoc/modules/ROOT/partials/usage/apoc.temporal.formatDuration.adoc
Labels: cherry-picked, 4.4

#3196 [xa1QAhHL] Add warning about using apoc.triggers in a Clustered environment
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.declareFunction.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.declareProcedure.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.removeFunction.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.removeProcedure.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.dv/apoc.dv.catalog.add.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.dv/apoc.dv.catalog.remove.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.add.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.list.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.pause.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.remove.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.removeAll.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.resume.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.install.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.remove.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.removeAll.adoc
Labels: docs, cherry-picked, 4.3, team-cypher-surface

#3195 [xa1QAhHL] Update documentation to warn about unpredictable procedures in clusters (#3191)
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.declareFunction.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.declareProcedure.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.removeFunction.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.removeProcedure.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.dv/apoc.dv.catalog.add.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.dv/apoc.dv.catalog.remove.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.install.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.remove.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.removeAll.adoc
Labels: docs, cherry-picked, 5.0, team-cypher-surface

#3194 [xa1QAhHL] Add warning about using apoc.triggers in a Clustered environment
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.declareFunction.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.declareProcedure.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.removeFunction.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.removeProcedure.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.dv/apoc.dv.catalog.add.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.dv/apoc.dv.catalog.remove.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.add.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.list.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.nodesByLabel.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.pause.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.propertiesByKey.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.remove.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.removeAll.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.resume.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.install.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.remove.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.removeAll.adoc
Labels: docs, cherry-picked, 4.4, team-cypher-surface

#3201 Fixes neo4j/apoc#11: apoc.load* don't actually support tar and tar.gz (neo4j/apoc#200)
  core/src/main/java/apoc/util/ArchiveType.java
  core/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/load/LoadJsonTest.java
  core/src/test/java/apoc/load/XmlTest.java
  core/src/test/resources/testload.tar
  core/src/test/resources/testload.tar.gz
  core/src/test/resources/testload.tgz
  core/src/test/resources/testloadCompressed.tar
  core/src/test/resources/testloadCompressed.tar.gz
  core/src/test/resources/testloadCompressed.tgz
  full/src/test/java/apoc/load/LoadCsvTest.java
  full/src/test/resources/testload.tar
  full/src/test/resources/testload.tar.gz
  full/src/test/resources/testload.tgz
Labels: cherry-picked, 4.4

#3202 Fixes neo4j/apoc#21: Not able to import 'JSON' data using apoc.import.json procedure
  docs/asciidoc/modules/ROOT/pages/import/load-json.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.import.json.adoc
Labels: cherry-picked, 4.4

#3208 Fixes neo4j/apoc#18: Default parallel concurrency of 50 is too high
  core/src/main/java/apoc/periodic/Periodic.java
  core/src/main/java/apoc/refactor/rename/Rename.java
Labels: cherry-picked, 4.3

#3207 Fixes neo4j/apoc#18: Default parallel concurrency of 50 is too high (…
  core/src/main/java/apoc/periodic/Periodic.java
  core/src/main/java/apoc/refactor/rename/Rename.java
Labels: cherry-picked, 4.4

#3206 Fixes neo4j/apoc#21: Not able to import 'JSON' data using apoc.import.json procedure
  docs/asciidoc/modules/ROOT/pages/import/load-json.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.import.json.adoc
Labels: cherry-picked, 4.3

#3209 [tYbuDF2B] The apoc.export.cypher.* procedures don't create relationships with start/end node without properties
  core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/CreateCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/CypherFormatterUtils.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Labels: cherry-picked, 4.3

#3210 [tYbuDF2B] The apoc.export.cypher.* procedures don't create relationships with start/end node without properties (neo4j/apoc#181)
  core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/CreateCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/CypherFormatterUtils.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Labels: cherry-picked, 4.4

#3205 Fixes #1132: Add ability to all export procedures to compress their data (4.3)
  core/src/main/java/apoc/export/csv/CsvLoaderConfig.java
  core/src/main/java/apoc/export/csv/ExportCSV.java
  core/src/main/java/apoc/export/cypher/ExportCypher.java
  core/src/main/java/apoc/export/cypher/ExportFileManager.java
  core/src/main/java/apoc/export/cypher/FileManagerFactory.java
  core/src/main/java/apoc/export/graphml/ExportGraphML.java
  core/src/main/java/apoc/export/json/ExportJson.java
  core/src/main/java/apoc/export/util/ExportConfig.java
  core/src/main/java/apoc/export/util/ExportUtils.java
  core/src/main/java/apoc/result/ProgressInfo.java
  core/src/main/java/apoc/util/CompressionAlgo.java
  core/src/main/java/apoc/util/CompressionConfig.java
  core/src/main/java/apoc/util/FileUtils.java
  core/src/main/java/apoc/util/StreamConnection.java
  core/src/main/java/apoc/util/Util.java
  core/src/main/java/apoc/util/Utils.java
  core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  core/src/test/java/apoc/export/json/ExportJsonTest.java
  core/src/test/java/apoc/util/BinaryTestUtil.java
  core/src/test/resources/csv-inputs/ignore-relationships.csv.zz
  docs/asciidoc/modules/ROOT/pages/export/csv.adoc
  docs/asciidoc/modules/ROOT/pages/export/cypher.adoc
  docs/asciidoc/modules/ROOT/pages/export/graphml.adoc
  docs/asciidoc/modules/ROOT/pages/export/json.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.export/compression.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.export.xls.all.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.export.xls.data.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.export.xls.graph.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.export.xls.query.adoc
  full/src/main/java/apoc/export/xls/ExportXls.java
  full/src/main/java/apoc/metrics/Metrics.java
  full/src/test/java/apoc/export/csv/ExportCsvTest.java
  full/src/test/java/apoc/export/csv/ExportXlsTest.java
  full/src/test/java/apoc/util/BinaryTestUtil.java
Labels: cherry-picked, 4.3

#3204 Fixes neo4j/apoc#11: apoc.load* don't actually support tar and tar.gz (neo4j/apoc#200)
  core/src/main/java/apoc/util/ArchiveType.java
  core/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/load/LoadJsonTest.java
  core/src/test/java/apoc/load/XmlTest.java
  core/src/test/resources/testload.tar
  core/src/test/resources/testload.tar.gz
  core/src/test/resources/testload.tgz
  core/src/test/resources/testloadCompressed.tar
  core/src/test/resources/testloadCompressed.tar.gz
  core/src/test/resources/testloadCompressed.tgz
  full/src/test/java/apoc/load/LoadCsvTest.java
  full/src/test/resources/testload.tar
  full/src/test/resources/testload.tar.gz
  full/src/test/resources/testload.tgz
Labels: cherry-picked, 4.3

#3213 [UHxIZ8JO] Add CodeQL (#186)
  .github/GH-ROBOTS.txt
  .github/workflows/CI.yaml
  core/src/main/java/apoc/export/util/ElementCounter.java
Labels: cherry-picked, 4.4

#3225 [4zKlPDoa] Remove FIREFOX LoadHtmlTests
  full/src/test/java/apoc/load/LoadHtmlTest.java
  full/src/test/java/apoc/load/LoadHtmlTestParameterized.java
Labels: cherry-picked, 4.3

#3229 [UHxIZ8JO] Grant CodeQL permissions (#212)
  .github/workflows/CI.yaml
Labels: cherry-picked, 4.3

#3228 [UHxIZ8JO] Grant CodeQL permissions (#212)
  .github/workflows/CI.yaml
Labels: cherry-picked, 4.4

#3217 [d7Ivq7cM] Bump snakeyaml in extended APOC
  full/build.gradle
Labels: 4.4

#3231 Update testJaroWinklerDistance test expectation
  core/src/test/java/apoc/text/StringsTest.java
Labels: bug, 4.4

#2957 (NO AUTO) Fix docs cve 2021-27568 (#2953)
  core/build.gradle
  docs/asciidoc/antora.yml
  docs/asciidoc/modules/ROOT/pages/import/includes/jsonpath.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.convert.fromJsonList.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.convert.fromJsonMap.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.convert.getJsonProperty.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.convert.getJsonPropertyMap.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.json.path.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.jsonArray.adoc
  full/build.gradle
Labels: cherry-picked

#3232 Update testJaroWinklerDistance test expectation
  core/build.gradle
  core/src/test/java/apoc/text/StringsTest.java
Labels: bug, 4.3

#3233 5.x update documentation
  docs/asciidoc/modules/ROOT/pages/config/index.adoc
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
  docs/asciidoc/modules/ROOT/pages/introduction/index.adoc
  readme.adoc
Labels: docs, 5.0, team-cypher-surface

#3238 [pDw6xmRG] Fixes neo4j/apoc#26: apoc.refactor.rename.label delets label if oldLabel is equal to newLabel (#209)
  core/src/main/java/apoc/refactor/rename/Rename.java
  core/src/test/java/apoc/refactor/rename/RenameTest.java
Labels: cherry-picked, 4.4

#3240 Update commons-text (#3235)
  core/build.gradle
Labels: cherry-picked, 4.3

#3239 [pDw6xmRG] Fixes neo4j/apoc#26: apoc.refactor.rename.label delets label if oldLabel is equal to newLabel
  core/src/main/java/apoc/refactor/rename/Rename.java
  core/src/test/java/apoc/refactor/rename/RenameTest.java
Labels: cherry-picked, 4.3

#2866 AUTO: Changed shouldTerminateImportWhenTransactionIsTimedOut test (#2862)
  core/src/test/java/apoc/export/json/ImportJsonTest.java
Labels: autocreated

#3242 Fix export to csv docs
  docs/asciidoc/modules/ROOT/pages/export/csv.adoc
Labels: docs, cherry-picked, 4.4, team-cypher-surface

#3243 Fix export to csv docs
  docs/asciidoc/modules/ROOT/pages/export/csv.adoc
Labels: docs, cherry-picked, 4.3, team-cypher-surface

#3244 Fix export to csv docs
  docs/asciidoc/modules/ROOT/pages/export/csv.adoc
Labels: docs, cherry-picked, 4.2, team-cypher-surface

#2520 Fixes #2373 and #218: Schedule task for one-off execution at specified time
  core/src/main/java/apoc/periodic/Periodic.java
  core/src/test/java/apoc/periodic/PeriodicTest.java
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.periodic-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.periodic.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.periodic.repeat-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.periodic.repeat.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/documentation.csv
  docs/asciidoc/modules/ROOT/pages/overview/apoc.periodic/apoc.periodic.repeat.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.periodic/index.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.periodic.cancel.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.periodic.repeat.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.periodic.submit.adoc
  full/src/test/resources/signatures.csv
Labels: 4.3, core-functionality

#3234 Fixes neo4j/apoc#126: apoc.periodic.submit fails with schema operations (neo4j/apoc#208)
  core/src/main/java/apoc/periodic/Periodic.java
  core/src/main/java/apoc/periodic/PeriodicUtils.java
  core/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/periodic/PeriodicTest.java
Labels: cherry-picked, 4.4

#3246 Fixes neo4j/apoc#126: apoc.periodic.submit fails with schema operations (neo4j/apoc#208) (#3234)
  core/src/main/java/apoc/periodic/Periodic.java
  core/src/main/java/apoc/periodic/PeriodicUtils.java
  core/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/periodic/PeriodicTest.java
Labels: cherry-picked, 4.3

#3249 [NOID] Bumps 4.4 version for release
  build.gradle
  docs/asciidoc/antora.yml
  docs/build.gradle
  extra-dependencies/build.gradle
Labels: 4.4, team-cypher-surface

#3250 [NOID] Bumps 4.3 version for release
  build.gradle
  docs/asciidoc/antora.yml
  docs/build.gradle
  extra-dependencies/build.gradle
Labels: 4.3, team-cypher-surface

#3245 [H10zCpAQ] Fix CWE-73: Added check to prevent reading from outside metrics directory
  full/src/main/java/apoc/metrics/Metrics.java
  full/src/test/java/apoc/metrics/MetricsTest.java
Labels: 4.4

#3236 [4HrPR2Rm] Use internal function instead of procedure for compatibility
  core/src/main/java/apoc/cypher/CypherInitializer.java
  core/src/test/java/apoc/cypher/CypherIsVersionDifferentTest.java
  full/src/test/java/apoc/monitor/TransactionProcedureTest.java
Labels: cherry-picked, 4.4, team-cypher-surface

#3255 [NOID] Cherry Pick https update
  readme.adoc
Labels: cherry-picked, 4.3, team-cypher-surface

#3254 [NOID] Cherry Pick https update
  readme.adoc
Labels: cherry-picked, 5.0, team-cypher-surface

#3099 Fixes #2930: The apoc.import.json constraint check should works only when an unique constraint exists
  core/src/main/java/apoc/export/json/JsonImporter.java
  core/src/test/java/apoc/export/json/ImportJsonEnterpriseTest.java
  core/src/test/java/apoc/export/json/ImportJsonTest.java
Labels: 4.3

#3014 Fixes neo4j/apoc#22: Handle incorrect JSON documents in apoc.convert.fromJsonMap
  core/src/main/java/apoc/load/util/ConversionUtil.java
  core/src/main/java/apoc/util/JsonUtil.java
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.json-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.json.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/documentation.csv
  docs/asciidoc/modules/ROOT/pages/overview/apoc.json/apoc.json.validate.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.json/index.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/nav.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.convert.fromJsonList.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.convert.fromJsonMap.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.convert.getJsonProperty.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.convert.getJsonPropertyMap.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.json.path.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.json.validate.adoc
  full/src/main/java/apoc/json/JsonExtended.java
  full/src/main/resources/extended.txt
  full/src/test/java/apoc/json/JsonExtendedTest.java
Labels: 4.4

#3247 Fixes #2395: The apoc.cypher.runSchemaFile doesn't support full text indexes (#3084)
  core/src/main/java/apoc/util/Util.java
  full/src/main/java/apoc/cypher/CypherExtended.java
  full/src/test/java/apoc/cypher/CypherExtendedTest.java
  full/src/test/resources/constraints.cypher
  full/src/test/resources/schema.cypher
Labels: cherry-picked, 4.4
