Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2022-07, with the labels that each got.

#3012 AUTO: Fixes #2932: The apoc.import.csv skipLines config doesn't work correctly (#2984)
  core/src/main/java/apoc/export/csv/CsvEntityLoader.java
  core/src/main/java/apoc/export/csv/CsvLoaderConfig.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
Labels: autocreated

#3011 AUTO: Fixes #2932: The apoc.import.csv skipLines config doesn't work correctly (#2984)
  core/src/main/java/apoc/export/csv/CsvEntityLoader.java
  core/src/main/java/apoc/export/csv/CsvLoaderConfig.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
Labels: autocreated

#3029 AUTO: Fixes #3008: Missing documentation for the apoc.refactor.cloneNodes (#3028)
  docs/asciidoc/modules/ROOT/images/apoc.refactor.cloneNodes.dataset.png
  docs/asciidoc/modules/ROOT/images/apoc.refactor.cloneNodes.png
  docs/asciidoc/modules/ROOT/images/apoc.refactor.cloneNodesWithRelationships.dataset.png
  docs/asciidoc/modules/ROOT/images/apoc.refactor.cloneNodesWithRelationships.png
  docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/clone-nodes.adoc
Labels: autocreated

#3030 AUTO: Fixes #3008: Missing documentation for the apoc.refactor.cloneNodes (#3028)
  docs/asciidoc/modules/ROOT/images/apoc.refactor.cloneNodes.dataset.png
  docs/asciidoc/modules/ROOT/images/apoc.refactor.cloneNodes.png
  docs/asciidoc/modules/ROOT/images/apoc.refactor.cloneNodesWithRelationships.dataset.png
  docs/asciidoc/modules/ROOT/images/apoc.refactor.cloneNodesWithRelationships.png
  docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/clone-nodes.adoc
Labels: autocreated

#3023 AUTO: Added support for Duration to apoc.coll.avg (#2987)
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.coll-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.coll.avgDuration-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.coll.avgDuration.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.coll.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/documentation.csv
  docs/asciidoc/modules/ROOT/pages/overview/apoc.coll/apoc.coll.avgDuration.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.coll/index.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/nav.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.coll.avgDuration.adoc
  full/src/main/java/apoc/coll/CollFull.java
  full/src/main/resources/extended.txt
  full/src/test/java/apoc/coll/CollFullTest.java
Labels: autocreated

#3024 AUTO: Added support for Duration to apoc.coll.avg (#2987)
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.coll-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.coll.avgDuration-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.coll.avgDuration.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.coll.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/documentation.csv
  docs/asciidoc/modules/ROOT/pages/overview/apoc.coll/apoc.coll.avgDuration.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.coll/index.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/nav.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.coll.avgDuration.adoc
  full/src/main/java/apoc/coll/CollFull.java
  full/src/main/resources/extended.txt
  full/src/test/java/apoc/coll/CollFullTest.java
Labels: autocreated

#2991 AUTO: Fixes #2975: No docs for apoc.load.htmlPlainText (#2977)
  docs/asciidoc/modules/ROOT/pages/overview/apoc.load/apoc.load.htmlPlainText.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.load/index.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/nav.adoc
  docs/asciidoc/modules/ROOT/partials/html/query-selectors.adoc
  docs/asciidoc/modules/ROOT/partials/html/runtime.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.html.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.htmlPlainText.adoc
Labels: autocreated

#3034 Add mode to DbmsRule
  test-utils/src/main/java/org/neo4j/test/rule/DbmsRule.java
Labels: 5.0, team-cypher-surface

#3010 AUTO: Fixes #3000: apoc.refactor.cloneNodes withRelationships = true - hangs and does not complete call (#3005)
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
Labels: autocreated

#3009 AUTO: Fixes #3000: apoc.refactor.cloneNodes withRelationships = true - hangs and does not complete call (#3005)
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
Labels: autocreated

#2997 AUTO: Fixes some wrong urls in docs (#2986)
  docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
  docs/asciidoc/modules/ROOT/pages/import/xml.adoc
  docs/asciidoc/modules/ROOT/pages/usage/index.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.import.xml.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.xml.adoc
  readme.adoc
Labels: autocreated

#3007 AUTO: Upgrades packages and adocs for CVE extra-deps (#2989)
  core/build.gradle
  docs/asciidoc/modules/ROOT/pages/database-integration/bolt-neo4j.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/couchbase.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/mongo.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/mongodb.adoc
  docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
  docs/asciidoc/modules/ROOT/partials/mongodb-dependencies.adoc
  extra-dependencies/bolt/build.gradle
  extra-dependencies/couchbase/build.gradle
  extra-dependencies/hadoop/build.gradle
  extra-dependencies/mongodb/build.gradle
  extra-dependencies/nlp/build.gradle
  full/build.gradle
  full/src/main/java/apoc/couchbase/CouchbaseManager.java
  full/src/main/java/apoc/mongodb/MongoDBColl.java
  full/src/main/kotlin/apoc/nlp/aws/AWSVirtualSentimentVirtualGraph.kt
  test-utils/build.gradle
Labels: autocreated

#3039 AUTO: Fixes #2966: apoc.custom.declareProcedure does not accept default float values (#3033)
  full/src/main/java/apoc/custom/Signatures.java
  full/src/test/java/apoc/custom/CypherProceduresTest.java
Labels: autocreated

#3038 AUTO: Fixes #2966: apoc.custom.declareProcedure does not accept default float values (#3033)
  full/src/main/java/apoc/custom/Signatures.java
  full/src/test/java/apoc/custom/CypherProceduresTest.java
Labels: autocreated

#3027 Avoid reusing the AmbientCursor in node.getLabels()
  core/src/main/java/apoc/path/LabelMatcher.java
  core/src/main/java/apoc/path/LabelMatcherGroup.java
  core/src/main/java/apoc/path/PathExplorer.java
Labels: bug, 4.4, team-cypher-surface

#3045 Avoid reusing the AmbientCursor in node.getLabels()
  core/src/main/java/apoc/path/LabelMatcher.java
  core/src/main/java/apoc/path/LabelMatcherGroup.java
  core/src/main/java/apoc/path/PathExplorer.java
Labels: cherry-picked, 5.0

#2832 Fixes #2739: Allow apoc.spatial.geoCodeOnce to also receive config via procedure call
  core/src/main/java/apoc/spatial/Geocode.java
  core/src/test/java/apoc/spatial/GeocodeTest.java
  core/src/test/java/apoc/spatial/SpatialTest.java
  core/src/test/resources/spatial.json
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.spatial-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.spatial.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.spatial.geocode-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.spatial.geocode.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.spatial.geocodeOnce-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.spatial.geocodeOnce.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.spatial.reverseGeocode-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.spatial.reverseGeocode.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.spatial.reverseGeocode.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.spatial.sortByDistance.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/documentation.csv
  docs/asciidoc/modules/ROOT/pages/misc/spatial.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.spatial/apoc.spatial.geocode.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.spatial/apoc.spatial.geocodeOnce.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.spatial/apoc.spatial.reverseGeocode.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.spatial/index.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
Labels: 4.4

#3031 (NO AUTO) Upgrades packages and adocs for CVE extra-deps (#2989)
  core/build.gradle
  docs/asciidoc/modules/ROOT/pages/database-integration/bolt-neo4j.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/couchbase.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/mongo.adoc
  docs/asciidoc/modules/ROOT/pages/database-integration/mongodb.adoc
  docs/asciidoc/modules/ROOT/partials/mongodb-dependencies.adoc
  extra-dependencies/couchbase/build.gradle
  extra-dependencies/hadoop/build.gradle
  extra-dependencies/mongodb/build.gradle
  extra-dependencies/nlp/build.gradle
  full/build.gradle
  full/src/main/java/apoc/couchbase/CouchbaseManager.java
  full/src/main/java/apoc/mongodb/MongoDBColl.java
  full/src/main/kotlin/apoc/nlp/aws/AWSVirtualSentimentVirtualGraph.kt
  test-utils/build.gradle
Labels: cherry-picked

#3052 Update test using ambiguous aggregation expression
  core/src/test/java/apoc/convert/ConvertJsonTest.java
Labels: 5.0

#3053 NO AUTO Bumps version of neo4j, driver and apoc for release
  build.gradle
  docs/build.gradle
  extra-dependencies/build.gradle
  readme.adoc
Labels: 3.5, team-cypher-surface

#3057 Export cypher overwrite relationships in case of merge with multi-rels with the same nodes and type (#3035)
  core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
  core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/CreateCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/CypherFormatterUtils.java
  core/src/main/java/apoc/export/cypher/formatter/UpdateAllCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java
  core/src/main/java/apoc/export/util/ExportConfig.java
  core/src/test/java/apoc/export/cypher/ExportCypherMultiRelTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherTestUtils.java
  docs/asciidoc/modules/ROOT/pages/export/cypher.adoc
Labels: cherry-picked

#3054 Export cypher overwrite relationships in case of merge with multi-rels with the same nodes and type (#3035)
  core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
  core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/CreateCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/CypherFormatterUtils.java
  core/src/main/java/apoc/export/cypher/formatter/UpdateAllCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java
  core/src/main/java/apoc/export/util/ExportConfig.java
  core/src/test/java/apoc/export/cypher/ExportCypherMultiRelTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherTestUtils.java
  docs/asciidoc/modules/ROOT/pages/export/cypher.adoc
Labels: cherry-picked

#3058 Forces dependency to especific version to avoid binary incompatibilities
  core/build.gradle
Labels: to-cherry-pick, 4.4, team-cypher-surface

#3062 NO AUTO Bump neo4j and driver version, force cache refresh in CI
  .github/workflows/CI.yaml
  build.gradle
  full/build.gradle
  test-utils/build.gradle
Labels: 4.4, team-cypher-surface

#3066 NO AUTO Forces cache refresh in the CI
  .github/workflows/CI.yaml
Labels: cherry-picked, 4.3, team-cypher-surface

#3065 NO AUTO Makes container wait for neo4j database ready
  test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: bug, 5.0, team-cypher-surface

#3060 NO AUTO Forces dependency to especific version to avoid binary incompatibilities
  .github/workflows/CI.yaml
  core/build.gradle
Labels: cherry-picked, 5.0, team-cypher-surface

#3071 Upgrades json-smart dependency
  build.gradle
Labels: 3.5, team-cypher-surface

#3068 (NO AUTO) apoc.meta.data count adoc/test for 5.0 (#2904)
  core/src/main/java/apoc/meta/Meta.java
  core/src/test/java/apoc/meta/MetaTest.java
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.meta-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.meta.data-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.meta.data.of-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.meta.data.of.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/documentation.csv
  docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.data.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.data.of.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.meta.data.adoc
Labels: cherry-picked

#3067 (NO AUTO) apoc.meta.data count adoc/test (#2904)
  core/src/main/java/apoc/meta/Meta.java
  core/src/test/java/apoc/meta/MetaTest.java
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.meta-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.meta.data-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.meta.data.of-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.meta.data.of.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/documentation.csv
  docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.data.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.data.of.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.meta.data.adoc
Labels: cherry-picked

#3075 Upgrade commons-configuration2 to 2.8.0 (#3063)
  core/build.gradle
  full/build.gradle
Labels: cherry-picked

#3074 Upgrade commons-configuration2 to 2.8.0 (#3063)
  core/build.gradle
  full/build.gradle
Labels: cherry-picked

#3061 NO AUTO Tries to deflake CREATE DATABASE tests
  full/src/test/java/apoc/ttl/TTLMultiDbTest.java
  full/src/test/java/apoc/uuid/UUIDMultiDbTest.java
Labels: 5.0, team-cypher-surface
