Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2023-09, with the labels that each got.

#3755 [XWc7tBAb] Custom procedures with overload fail after refresh
  extended/src/main/java/apoc/custom/CypherProcedures.java
  extended/src/main/java/apoc/custom/CypherProceduresHandler.java
  extended/src/test/java/apoc/custom/CypherProceduresStorageTest.java
  extended/src/test/java/apoc/custom/CypherProceduresTest.java
Labels: extended-functionality, dev

#3761 [XWc7tBAb] Custom procedures with overload fail after refresh (#3755)
  extended/src/main/java/apoc/custom/CypherProcedures.java
  extended/src/main/java/apoc/custom/CypherProceduresHandler.java
  extended/src/test/java/apoc/custom/CypherProceduresStorageTest.java
  extended/src/test/java/apoc/custom/CypherProceduresTest.java
Labels: cherry-picked, extended-functionality, 5.11

#3762 bump 5.11.1
  build.gradle
  docs/asciidoc/antora.yml
  docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
  docs/build.gradle
  extra-dependencies/build.gradle
  readme.adoc
Labels: extended-functionality, 5.11

#3760 Fixes #3708: Neo4j APOC custom function hangs when nothing is found
  extended/src/main/java/apoc/custom/CypherProceduresHandler.java
  extended/src/test/java/apoc/custom/CypherProceduresTest.java
Labels: extended-functionality, 5.11

#3764 [XWc7tBAb] Custom procedures with overload fail after refresh (#3755)
  full/src/main/java/apoc/custom/CypherProcedures.java
  full/src/main/java/apoc/custom/CypherProceduresHandler.java
  full/src/test/java/apoc/custom/CypherProceduresStorageTest.java
  full/src/test/java/apoc/custom/CypherProceduresTest.java
Labels: cherry-picked, 4.4, extended-functionality

#3765 [NOID] Fixes #3708: Neo4j APOC custom function hangs when nothing is found (#3760)
  full/src/main/java/apoc/custom/CypherProceduresHandler.java
  full/src/test/java/apoc/custom/CypherProceduresTest.java
Labels: cherry-picked, 4.4, extended-functionality

#3763 [YGQfavsP] Remove dependency on external websites in load tests
  core/src/test/java/apoc/load/LoadJsonTest.java
  core/src/test/java/apoc/load/SimpleHttpHandler.java
  core/src/test/java/apoc/load/XmlTest.java
Labels: cherry-picked, 4.4, team-cypher-surface

#3769 Bump version 5.13.0 (#3456) (#3536) (#3658)
  build.gradle
  docs/asciidoc/antora.yml
  docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
  docs/build.gradle
  extra-dependencies/build.gradle
  readme.adoc
Labels: cherry-picked, extended-functionality, dev

#3772 Change 5.11.1 to 5.11.0
  build.gradle
  docs/asciidoc/antora.yml
  docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
  docs/build.gradle
  extra-dependencies/build.gradle
  readme.adoc
Labels: extended-functionality, 5.11

#3776 [I2uYvnlA] Bumps apoc version
  build.gradle
  docs/asciidoc/antora.yml
  docs/build.gradle
  extra-dependencies/build.gradle
  readme.adoc
Labels: 4.4, team-cypher-surface

#3773 [iBQzFOoI] Adds sts to the list of aws extra-dependencies
  extra-dependencies/aws/build.gradle
Labels: team-cypher-surface, dev

#3774 [iBQzFOoI] Adds sts to the list of aws extra-dependencies
  extra-dependencies/aws/build.gradle
Labels: cherry-picked, 4.4, team-cypher-surface

#3778 Release 5.12.0
  .github/workflows/CI.yaml
  .gitmodules
  build.gradle
  docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
  extended/build.gradle
  readme.adoc
Labels: cherry-picked, extended-functionality, 5.12

#3785 [NOID] Bump Neo version
  LICENSES.txt
  NOTICE.txt
  build.gradle
  readme.adoc
Labels: 4.4, team-cypher-surface

#3788 Fixes #3708: Neo4j APOC custom function hangs when nothing is found
  extended/src/main/java/apoc/custom/CypherProceduresHandler.java
  extended/src/test/java/apoc/custom/CypherProceduresTest.java
Labels: cherry-picked, extended-functionality, 5.12

#3791 [rCBSQkmb] recommend using id function in apoc.periodic.iterate
  docs/asciidoc/modules/ROOT/partials/periodic-iterate.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.periodic.iterate.adoc
Labels: 4.4
