Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2023-06, with the labels that each got.

#3604 Updated exteded.txt with vertexai procs
  extended/src/main/resources/extended.txt
Labels: extended-functionality, dev

#3606 [wr4kMP3r] ArithmeticException calling apoc.schema.nodes (neo4j/apoc#364)
  core/src/main/java/apoc/schema/Schemas.java
  core/src/test/java/apoc/schema/SchemasTest.java
Labels: cherry-picked, 4.4

#3612 Fixes #1582: rebind flag in apoc.periodic.iterate (#3098)
  docs/asciidoc/modules/ROOT/nav.adoc
  docs/asciidoc/modules/ROOT/pages/operational/index.adoc
  docs/asciidoc/modules/ROOT/pages/operational/rebind.adoc
  extended/src/main/java/apoc/nodes/NodesExtended.java
  extended/src/main/java/apoc/util/EntityUtil.java
  extended/src/main/resources/extended.txt
  extended/src/test/java/apoc/nodes/NodesExtendedTest.java
  extended/src/test/java/apoc/periodic/PeriodicExtendedTest.java
Labels: cherry-picked, extended-functionality, dev

#3613 [KUEoGBey] Sanitize text input and add quotes to allow special characters in Atomic procedures
  core/src/main/java/apoc/atomic/Atomic.java
  core/src/test/java/apoc/atomic/AtomicTest.java
Labels: cherry-picked, 4.4, team-cypher-surface

#3614 [NOID] apoc.schema.* Fix unique constraint column
  core/src/main/java/apoc/schema/Schemas.java
  core/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
Labels: cherry-picked, 4.4, team-cypher-surface

#3616 [3QAbWQds] apoc.export.arrow.all ignores export file config (neo4j/apoc#349)
  core/src/main/java/apoc/ApocConfig.java
  core/src/main/java/apoc/export/arrow/ExportArrowService.java
  core/src/test/java/apoc/export/ExportCoreSecurityTest.java
  core/src/test/java/apoc/export/arrow/ArrowTest.java
  core/src/test/java/apoc/export/arrow/ExportArrowSecurityTest.java
Labels: cherry-picked, 4.4

#3619 Bump version 5.10.0 (#3456)
  build.gradle
  docs/asciidoc/antora.yml
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
  docs/build.gradle
  extra-dependencies/build.gradle
  readme.adoc
Labels: extended-functionality, dev

#3621 [VpC8nqNz] Fail build on spotless and licence failures
  .github/actions/test-gradle-project/action.yaml
  LICENSES.txt
  NOTICE.txt
  licenses-3rdparties.gradle
Labels: cherry-picked, 4.4, team-cypher-surface

#3622 [tW7Gyubn] Removes javafaker from the project
  LICENSES.txt
  NOTICE.txt
  full/build.gradle
  full/src/main/java/apoc/generate/node/SocialNetworkNodeCreator.java
  full/src/main/java/apoc/util/Faker.java
Labels: 4.4, team-cypher-surface

#3623 [NOID] Release 5.9.0 (#3455)
  .github/workflows/CI.yaml
  .gitmodules
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
  readme.adoc
Labels: extended-functionality, 5.9

#3626 [NOID] DETACH DELETE in TTLLifeCycle.java (#3608)
  full/src/main/java/apoc/ttl/TTLLifeCycle.java
Labels: cherry-picked, 4.4, extended-functionality

#3627 DETACH DELETE in TTLLifeCycle.java (#3608)
  extended/src/main/java/apoc/ttl/TTLLifeCycle.java
Labels: cherry-picked, extended-functionality, 5.9

#3628 [NOID] Small vertexai docs fixes
  docs/asciidoc/modules/ROOT/pages/ml/vertexai.adoc
Labels: extended-functionality, 5.9

#3631 [drqYtb6r] apoc.cypher.run* procedures don't return results
  core-it/src/test/java/apoc/core/it/CypherEnterpriseTest.java
  core-it/src/test/java/apoc/core/it/ExportCypherEnterpriseFeaturesTest.java
  core/src/main/java/apoc/cypher/Cypher.java
  core/src/main/java/apoc/util/EntityUtil.java
  full-it/src/test/java/apoc/full/it/CoreExtendedTest.java
  full-it/src/test/java/apoc/full/it/CypherEnterpriseExtendedTest.java
  full-it/src/test/java/apoc/full/it/CypherEnterpriseTest.java
  full-it/src/test/resources/apoc-core-extended.csv
  full/src/main/java/apoc/cypher/CypherExtended.java
  test-utils/src/main/java/apoc/cypher/CypherTestUtil.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: cherry-picked, 4.4

#3635 [hZww9vSJ] Make the type output of apoc.schema.* procedures more specific (neo4j/apoc#307) (neo4j/docs-apoc#107)
  core-it/src/test/java/apoc/core/it/SchemasEnterpriseFeaturesTest.java
  core/src/main/java/apoc/schema/Schemas.java
  core/src/test/java/apoc/schema/SchemasTest.java
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.schema.nodes.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.schema.relationships.adoc
  docs/asciidoc/modules/ROOT/images/apoc.schema.nodes.png
  docs/asciidoc/modules/ROOT/images/apoc.schema.relationships.png
  docs/asciidoc/modules/ROOT/pages/indexes/schema-index-operations.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.schema/apoc.schema.nodes.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.schema/apoc.schema.relationships.adoc
  docs/asciidoc/modules/ROOT/partials/schema/schema.nodes.type.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.schema.nodes.adoc
  modules/ROOT/partials/usage/apoc.schema.relationships.adoc
  modules/ROOT/partials/usage/partial$schema/schema.relationships.type.adoc
Labels: cherry-picked, 4.4

#3617 [s7Ob7Zm7] Test that all load and import procedures respect security (neo4j/apoc#360) (neo4j/apoc#377)
  core/src/test/java/apoc/export/ExportCoreSecurityTest.java
  core/src/test/java/apoc/export/ImportAndLoadCoreSecurityTest.java
  core/src/test/java/apoc/export/SecurityTestUtil.java
  core/src/test/java/apoc/export/arrow/ExportArrowSecurityTest.java
  core/src/test/java/apoc/load/LoadCoreSecurityTest.java
  core/src/test/java/apoc/load/LoadJsonTest.java
  core/src/test/java/apoc/load/XmlTest.java
  core/src/test/java/apoc/util/FileTestUtil.java
  full/src/test/java/apoc/load/LoadFullSecurityTest.java
  test-utils/src/main/java/apoc/util/SensitivePathGenerator.java
Labels: cherry-picked, 4.4

#3637 [P7cw3Wcj] Fix zip bomb attack (neo4j/apoc#398)
  core-it/src/test/java/apoc/core/it/LoadCoreEnterpriseTest.java
  core/src/main/java/apoc/export/util/CountingInputStream.java
  core/src/main/java/apoc/export/util/LimitedSizeInputStream.java
  core/src/main/java/apoc/load/Xml.java
  core/src/main/java/apoc/util/CompressionAlgo.java
  core/src/main/java/apoc/util/StreamConnection.java
  core/src/main/java/apoc/util/Util.java
  core/src/main/java/apoc/util/s3/S3Aws.java
Labels: cherry-picked, 4.4
