Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2023-04, with the labels that each got.

#3522 [ST3nW88b] Upgrade commons-configuration2 to 2.9.0 to address CVE-2022-42889
  core/build.gradle
  full/build.gradle
Labels: 4.4, team-cypher-surface

#3521 [H5vz3qhy] Prevent cascade trigger transactions (neo4j/apoc#346)
  core/src/main/java/apoc/trigger/TriggerHandler.java
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
Labels: cherry-picked, 4.4, core-functionality

#3527 [NOID] Fix flaky geocode server errors
  core/src/test/java/apoc/spatial/GeocodeTest.java
Labels: to-cherry-pick, 4.4, core-functionality

#3532 [f46vahOr] Fix #345 where exported Cypher constraints had wrong type.
  core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
  core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java
  core/src/main/java/apoc/export/util/NodesAndRelsSubGraph.java
  core/src/main/java/org/neo4j/cypher/export/DatabaseSubGraph.java
  core/src/test/java/apoc/export/cypher/ExportCypherEnterpriseFeaturesTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherS3Test.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherTestUtils.java
  core/src/test/resources/init_neo4j_export_csv.cypher
Labels: bug, cherry-picked, 4.4

#3525 [EV6LG1ZP] Fix mixup of apoc.refactor.rename.label and apoc.refactor.rename.type
  docs/asciidoc/modules/ROOT/partials/usage/apoc.refactor.rename.label.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.refactor.rename.type.adoc
Labels: cherry-picked, 4.4, team-cypher-surface

#3536 Bump version 5.8.0 (#3456)
  build.gradle
  docs/asciidoc/antora.yml
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
  docs/build.gradle
  extra-dependencies/build.gradle
  readme.adoc
Labels: extended-functionality

#3454 [TOQo1n9M] apoc-hadoop dependency is conflicting (#3450)
  extended/src/test/java/apoc/StartupExtendedTest.java
  extended/src/test/java/apoc/util/ExtendedTestContainerUtil.java
  test-startup/src/test/java/StartupTest.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: cherry-picked, extended-functionality, dev

#3539 [VYidKhdO] The required constraint on import key for import.json is unique
  core/src/main/java/apoc/export/json/JsonImporter.java
  core/src/test/java/apoc/export/json/ImportJsonEnterpriseFeaturesTest.java
  core/src/test/java/apoc/export/json/ImportJsonTest.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: cherry-picked, 4.4, team-cypher-surface

#3533 [Fb3ZFQbn] Fixes bug in cypher initializer to wait for systemdb
  core/src/main/java/apoc/cypher/CypherInitializer.java
  test-startup/src/test/java/StartupTest.java
Labels: bug, team-cypher-surface, dev

#3541 [PL7XdSMV] apoc.config.list and apoc.config.map leak evars (#3400)
  docs/asciidoc/modules/ROOT/partials/usage/allowed.configs.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.config.list.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.config.map.adoc
  full/src/main/java/apoc/config/Config.java
  full/src/test/java/apoc/config/ConfigTest.java
Labels: cherry-picked, 4.4, extended-functionality

#3537 Release 5.7.0
  .github/workflows/CI.yaml
  .gitmodules
  readme.adoc
Labels: extended-functionality, 5.7

#3295 Extended changes after fix core ignored s3 tests
  extended/src/test/java/apoc/load/LoadS3Test.java
  extended/src/test/java/apoc/util/s3/S3Container.java
Labels: to-cherry-pick, 5.0, extended-functionality

#3544 [TOQo1n9M] apoc-hadoop dependency is conflicting (#3450) (#3454)
  extended/src/test/java/apoc/StartupExtendedTest.java
  extended/src/test/java/apoc/util/ExtendedTestContainerUtil.java
  test-startup/src/test/java/StartupTest.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: cherry-picked, extended-functionality, 5.7
