Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2023-03, with the labels that each got.

#3479 [NOID] Fix cluster routing conf
  test-utils/src/main/java/apoc/util/TestcontainersCausalCluster.java
Labels: 4.4, extended-functionality

#3482 [ROQ0fkdz] Reduce the number of transactions we use in triggers (neo4j/apoc#303)
  core/src/main/java/apoc/trigger/TriggerHandlerNewProcedures.java
  core/src/main/java/apoc/trigger/TriggerNewProcedures.java
Labels: cherry-picked, 4.4

#3480 [OnEGwZ5A] apoc.hashing.fingerprint can't deal with type byte[]
  core/src/main/java/apoc/hashing/Fingerprinting.java
  core/src/test/java/apoc/hashing/FingerprintingTest.java
Labels: cherry-picked, 4.4

#3481 [iTwFvqQ2] apoc.create.clonePathsToVirtual() returns more relationships than it should (neo4j/apoc#328)
  core/src/main/java/apoc/create/Create.java
  core/src/test/java/apoc/create/CreateTest.java
Labels: cherry-picked, 4.4

#3483 [yHvDctRN] Add tests and docs about $transactionId (neo4j/apoc#289)
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
  docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
Labels: cherry-picked, 4.4

#3470 [NOID] Fix error message for apoc.schema.nodes/relationships with inc…
  core/src/main/java/apoc/schema/SchemaConfig.java
  core/src/test/java/apoc/schema/SchemasTest.java
Labels: cherry-picked, 4.4, core-functionality

#3494 Fix loadJsonStream compiler error in dev
  extended/src/main/java/apoc/es/ElasticSearch.java
Labels: extended-functionality, dev

#3493 Bumps 5.7.0 version
  build.gradle
  docs/asciidoc/antora.yml
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
  docs/build.gradle
  extra-dependencies/build.gradle
  readme.adoc
Labels: extended-functionality, dev

#3486 [NOID] Uses Temurin jdk 11
  .github/workflows/CI.yaml
Labels: 4.4

#3488 [NOID] Uses Temurin jdk 11
  .github/workflows/CI.yaml
Labels: 4.3

#3489 [NOID] Uses Temurin jdk 11
  .github/workflows/CI.yaml
Labels: 4.2

#3490 [NOID] Uses Temurin jdk 11
  .github/workflows/CI.yaml
Labels: 4.1

#3491 [NOID] Uses Temurin jdk 8
  .github/workflows/CI.yaml
Labels: 3.5

#3495 [0L9VOhhh] Bumps apoc version after release
  build.gradle
  docs/asciidoc/antora.yml
  docs/build.gradle
  extra-dependencies/build.gradle
Labels: 4.4, team-cypher-surface

#3478 [NOID] fixes #3477: apoc.load.html does not always report href
  full/src/main/java/apoc/load/LoadHtml.java
  full/src/test/java/apoc/load/LoadHtmlTest.java
Labels: extended-functionality

#3492 Init release 5.6.0
  .github/workflows/CI.yaml
  .gitmodules
Labels: extended-functionality, 5.6

#3502 [NOID] Updates JDK to use Temurin (#3487)
  .github/workflows/CI.yaml
Labels: cherry-picked, extended-functionality, 5.6

#3178 Fixes #2946: Improve apoc.load.directory.* adocs and test (#2988)
  build.gradle
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.load.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.load.directory.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.load.directory.async.add.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.load.directory.async.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.load.directory.async.list.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.load.directory.async.remove.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.load.directory.async.removeAll.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/documentation.csv
  docs/asciidoc/modules/ROOT/nav.adoc
  docs/asciidoc/modules/ROOT/pages/background-operations/apoc-load-directory-async.adoc
  docs/asciidoc/modules/ROOT/pages/background-operations/index.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.load/apoc.load.directory.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.load/apoc.load.directory.async.add.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.load/apoc.load.directory.async.list.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.load/apoc.load.directory.async.remove.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.load/apoc.load.directory.async.removeAll.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.load/index.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.directory.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.directory.async.add.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.directory.async.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.directory.async.directory.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.directory.async.remove.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.directory.async.removeAll.adoc
  extended/src/main/java/apoc/ExtendedApocConfig.java
  extended/src/main/java/apoc/load/LoadDirectory.java
  extended/src/test/java/apoc/load/LoadDirectoryTest.java
  extended/src/test/java/apoc/util/DbmsUtil.java
Labels: cherry-picked, 5.0, extended-functionality

#3506 [NOID] fixes #3477: apoc.load.html does not always report href (#3478)
  extended/src/main/java/apoc/load/LoadHtml.java
  extended/src/test/java/apoc/load/LoadHtmlTest.java
Labels: cherry-picked, extended-functionality, 5.6

#3507 Fixes #2946: Improve apoc.load.directory.* adocs and test (#2988)
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.load.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.load.directory.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.load.directory.async.add.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.load.directory.async.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.load.directory.async.list.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.load.directory.async.remove.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.load.directory.async.removeAll.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/documentation.csv
  docs/asciidoc/modules/ROOT/nav.adoc
  docs/asciidoc/modules/ROOT/pages/background-operations/apoc-load-directory-async.adoc
  docs/asciidoc/modules/ROOT/pages/background-operations/index.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.load/apoc.load.directory.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.load/apoc.load.directory.async.add.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.load/apoc.load.directory.async.list.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.load/apoc.load.directory.async.remove.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.load/apoc.load.directory.async.removeAll.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.load/index.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.directory.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.directory.async.add.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.directory.async.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.directory.async.directory.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.directory.async.remove.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.load.directory.async.removeAll.adoc
  extended/src/main/java/apoc/ExtendedApocConfig.java
  extended/src/main/java/apoc/load/LoadDirectory.java
  extended/src/test/java/apoc/load/LoadDirectoryTest.java
  extended/src/test/java/apoc/util/DbmsUtil.java
Labels: cherry-picked, extended-functionality, 5.6

#3505 [NOID] fixes #3477: apoc.load.html does not always report href (#3478)
  extended/src/main/java/apoc/load/LoadHtml.java
  extended/src/test/java/apoc/load/LoadHtmlTest.java
Labels: cherry-picked, extended-functionality, dev

#3508 Fixes neo4j/apoc#126: apoc.periodic.submit fails with schema operations (extended) (#3211)
  extended/src/main/java/apoc/periodic/PeriodicExtended.java
  extended/src/main/resources/extended.txt
  extended/src/test/java/apoc/periodic/PeriodicExtendedTest.java
Labels: cherry-picked, extended-functionality, 5.6

#3501 [NOID] Changed bolt driver version
  extended/build.gradle
Labels: to-cherry-pick, extended-functionality, 5.6

#3484 [ju7btyJy] APOC UUID Install Failing in Cluster
  core/src/main/java/apoc/SystemLabels.java
  core/src/main/java/apoc/SystemPropertyKeys.java
  core/src/main/java/apoc/uuid/UuidConfig.java
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.drop-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.drop.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.dropAll-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.dropAll.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.setup-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.setup.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.show-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.show.adoc
  docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
  docs/asciidoc/modules/ROOT/pages/graph-updates/uuid.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.drop.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.dropAll.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.install.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.remove.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.removeAll.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.setup.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.show.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/index.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/nav.adoc
  docs/asciidoc/modules/ROOT/partials/systemdbonly.note.adoc
  docs/asciidoc/modules/ROOT/partials/uuid/deprecated.adoc
  full/src/main/java/apoc/ExtendedApocGlobalComponents.java
  full/src/main/java/apoc/util/SystemDbUtil.java
  full/src/main/java/apoc/uuid/UUIDHandlerNewProcedures.java
  full/src/main/java/apoc/uuid/UUIDNewProcedures.java
  full/src/main/java/apoc/uuid/Uuid.java
  full/src/main/java/apoc/uuid/UuidHandler.java
  full/src/main/java/apoc/uuid/UuidInfo.java
  full/src/main/resources/extended.txt
  full/src/test/java/apoc/util/DbmsTestUtil.java
  full/src/test/java/apoc/util/SystemDbTestUtil.java
  full/src/test/java/apoc/uuid/UUIDClusterRoutingTest.java
  full/src/test/java/apoc/uuid/UUIDMultiDbTest.java
  full/src/test/java/apoc/uuid/UUIDNewProceduresTest.java
  full/src/test/java/apoc/uuid/UUIDRestartTest.java
  full/src/test/java/apoc/uuid/UUIDTest.java
  full/src/test/java/apoc/uuid/UUIDTestUtils.java
  test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
  test-utils/src/main/java/apoc/util/TestcontainersCausalCluster.java
Labels: 4.4, extended-functionality

#3512 [ju7btyJy] APOC UUID Install Failing in Cluster (#3484) (#3510)
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.drop-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.drop.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.dropAll-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.dropAll.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.setup-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.setup.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.show-lite.csv
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.uuid.show.adoc
  docs/asciidoc/modules/ROOT/pages/graph-updates/uuid.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.drop.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.dropAll.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.install.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.remove.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.removeAll.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.setup.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/apoc.uuid.show.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/index.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/nav.adoc
  docs/asciidoc/modules/ROOT/partials/systemdbonly.note.adoc
  docs/asciidoc/modules/ROOT/partials/uuid/deprecated.adoc
  extended/src/main/java/apoc/ExtendedApocGlobalComponents.java
  extended/src/main/java/apoc/ExtendedSystemLabels.java
  extended/src/main/java/apoc/ExtendedSystemPropertyKeys.java
  extended/src/main/java/apoc/util/SystemDbUtil.java
  extended/src/main/java/apoc/uuid/UUIDHandlerNewProcedures.java
  extended/src/main/java/apoc/uuid/UUIDNewProcedures.java
  extended/src/main/java/apoc/uuid/Uuid.java
  extended/src/main/java/apoc/uuid/UuidConfig.java
  extended/src/main/java/apoc/uuid/UuidHandler.java
  extended/src/main/java/apoc/uuid/UuidInfo.java
  extended/src/main/resources/extended.txt
  extended/src/test/java/apoc/util/DbmsTestUtil.java
  extended/src/test/java/apoc/util/SystemDbTestUtil.java
  extended/src/test/java/apoc/uuid/UUIDClusterRoutingTest.java
  extended/src/test/java/apoc/uuid/UUIDMultiDbTest.java
  extended/src/test/java/apoc/uuid/UUIDNewProceduresTest.java
  extended/src/test/java/apoc/uuid/UUIDRestartTest.java
  extended/src/test/java/apoc/uuid/UUIDTest.java
  extended/src/test/java/apoc/uuid/UUIDTestUtils.java
Labels: cherry-picked, extended-functionality, dev

#3504 [tq7tdrWZ] Update Hadoop and JsonPath dependencies
  core/build.gradle
  docs/asciidoc/antora.yml
  extra-dependencies/hadoop/build.gradle
  test-utils/build.gradle
Labels: team-cypher-surface, dev

#3518 Adds job to deploy Pages with GitHub Actions
  .github/workflows/gh-pages.yml
Labels: team-cypher-surface
