Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2023-07, with the labels that each got.

#3641 [5LCCVHk4] Bump Neo4j version 4.4.22
  build.gradle
Labels: 4.4, team-cypher-surface

#3646 [VpC8nqNz] Adds license and notice validation to the CI (#451)
  .github/workflows/CI.yaml
  LICENSES.txt
  NOTICE.txt
Labels: 4.4, team-cypher-surface

#3645 [TFMonhHx] Forces new version of netty
  LICENSES.txt
  NOTICE.txt
  core/build.gradle
  core/src/main/java/io/netty/buffer/PooledByteBufAllocatorL.java
Labels: cherry-picked, 4.4

#3630 [5LCCVHk4] Bump APOC version 4.4.0.20
  build.gradle
  docs/asciidoc/antora.yml
  docs/build.gradle
  extra-dependencies/build.gradle
Labels: 4.4, team-cypher-surface, not-ready-for-merge

#3644 [NrNk9YvB] Adds projects to generate AWS and GCS dependencies
  .github/workflows/CI.yaml
  build.gradle
  extended/build.gradle
  extended/src/test/java/apoc/CoreExtendedTest.java
  extended/src/test/java/apoc/load/LoadExtendedSecurityTest.java
  extended/src/test/java/apoc/load/LoadGoogleCloudStorageTest.java
  extended/src/test/java/apoc/util/GoogleCloudStorageContainerExtension.java
  extra-dependencies/aws/build.gradle
  extra-dependencies/aws/gradle/wrapper/gradle-wrapper.jar
  extra-dependencies/aws/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/aws/gradlew
  extra-dependencies/aws/gradlew.bat
  extra-dependencies/couchbase/settings.gradle
  extra-dependencies/email/settings.gradle
  extra-dependencies/gcs/build.gradle
  extra-dependencies/gcs/gradle/wrapper/gradle-wrapper.jar
  extra-dependencies/gcs/gradle/wrapper/gradle-wrapper.properties
  extra-dependencies/gcs/gradlew
  extra-dependencies/gcs/gradlew.bat
  extra-dependencies/hadoop/build.gradle
  extra-dependencies/hadoop/settings.gradle
  extra-dependencies/mongodb/settings.gradle
  extra-dependencies/nlp/settings.gradle
  extra-dependencies/redis/settings.gradle
  extra-dependencies/selenium/settings.gradle
  extra-dependencies/settings.gradle
  extra-dependencies/xls/settings.gradle
Labels: cherry-picked, dev

#3657 [LePmOHly] Fix flakey index test
  core/src/test/java/apoc/schema/SchemasTest.java
Labels: cherry-picked, 4.4, team-cypher-surface

#3662 [GE2QhC9X] Add path traversal vulnerability tests (#3457)
  full/src/test/java/apoc/export/ExportFullSecurityTest.java
Labels: cherry-picked, 4.4, extended-functionality

#3655 [NOID] Release 5.10.0 (#3455)
  .github/workflows/CI.yaml
  .gitmodules
  build.gradle
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
  readme.adoc
Labels: not-ready-for-merge, extended-functionality, 5.10

#3670 [kfkbAyTs] Added Security Guidance docs page
  docs/asciidoc/modules/ROOT/nav.adoc
  docs/asciidoc/modules/ROOT/pages/config/index.adoc
  docs/asciidoc/modules/ROOT/pages/index.adoc
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
  docs/asciidoc/modules/ROOT/pages/security-guidelines/index.adoc
Labels: extended-functionality, dev

#3672 Update installation docs with docker and desktop, created partial and small fixes
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
  docs/asciidoc/modules/ROOT/partials/docker.adoc
  docs/asciidoc/modules/ROOT/partials/neo4j-desktop.adoc
  docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
  readme.adoc
Labels: cherry-picked, extended-functionality, 5.10

#3665 [RY28NjPX] Update installation docs with docker and desktop, created partial and small fixes
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
  docs/asciidoc/modules/ROOT/partials/docker.adoc
  docs/asciidoc/modules/ROOT/partials/neo4j-desktop.adoc
  docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
  readme.adoc
Labels: extended-functionality, dev

#3674 [ld3WXRsV] Fix APOC extended TTL tests
  extended/src/test/java/apoc/ttl/TTLTest.java
Labels: cherry-picked, extended-functionality, 5.10

#3678 Bump semver from 5.7.1 to 5.7.2 in /docs/antora
  docs/antora/package-lock.json
Labels: cherry-picked, extended-functionality, 5.10

#3679 [crGU1Fb4] Remove unused code after git submodule implementation
  full/src/test/resources/constraints.cypher
  full/src/test/resources/schema.cypher
  test-utils/src/main/java/apoc/util/GoogleCloudStorageContainerExtension.java
  test-utils/src/main/java/apoc/util/MySQLContainerExtension.java
  test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: to-cherry-pick, extended-functionality, 5.10

#3676 [drqYtb6r] apoc.cypher.run* procedures don't return results (extended) (#3624)
  extended/src/main/java/apoc/cypher/CypherExtended.java
  extended/src/test/java/apoc/cypher/CypherEnterpriseExtendedTest.java
  extended/src/test/java/apoc/cypher/CypherEnterpriseTest.java
Labels: cherry-picked, extended-functionality, 5.10

#3675 [BqvAC2FK] Update selenium dependencies
  extended/build.gradle
  extended/src/main/java/apoc/load/LoadHtml.java
  extended/src/main/java/apoc/load/LoadHtmlBrowser.java
  extended/src/test/java/apoc/load/LoadHtmlTest.java
  extended/src/test/java/apoc/load/LoadHtmlTestParameterized.java
  extra-dependencies/selenium/build.gradle
Labels: extended-functionality, 5.10

#3681 First LLM prompt for cypher, query and schema in APOC (#3649)
  docs/asciidoc/modules/ROOT/pages/ml/openai.adoc
  extended/src/main/java/apoc/ExtendedApocConfig.java
  extended/src/main/java/apoc/ml/OpenAI.java
  extended/src/main/java/apoc/ml/Prompt.java
  extended/src/main/resources/extended.txt
  extended/src/test/java/apoc/ml/OpenAIIT.java
  extended/src/test/java/apoc/ml/PromptIT.java
Labels: cherry-picked, extended-functionality, 5.10

#3686 [crGU1Fb4] Remove unused code after git submodule implementation (#3679)
  full/src/test/resources/constraints.cypher
  full/src/test/resources/schema.cypher
  test-utils/src/main/java/apoc/util/GoogleCloudStorageContainerExtension.java
  test-utils/src/main/java/apoc/util/MySQLContainerExtension.java
  test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: cherry-picked, extended-functionality, dev

#3668 [V8keNXu0] error details while using apoc.cypher.run* procedures
  docs/asciidoc/modules/ROOT/pages/overview/apoc.cypher/apoc.cypher.runFile.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.cypher/apoc.cypher.runFiles.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.cypher/apoc.cypher.runSchemaFile.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.cypher/apoc.cypher.runSchemaFiles.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.cypher.runExtended.adoc
  extended/src/main/java/apoc/cypher/CypherExtended.java
  extended/src/test/java/apoc/cypher/CypherExtendedTest.java
  extended/src/test/resources/create_delete.cypher
  extended/src/test/resources/long-create.cypher
  extended/src/test/resources/wrong_call_in_transactions.cypher
  extended/src/test/resources/wrong_schema_statements_runtime.cypher
  extended/src/test/resources/wrong_statements.cypher
  extended/src/test/resources/wrong_statements_runtime.cypher
Labels: extended-functionality, dev

#3687 [V8keNXu0] error details while using apoc.cypher.run* procedures (#3668)
  build.gradle
  extended/src/main/java/apoc/cypher/CypherExtended.java
  extended/src/test/java/apoc/cypher/CypherExtendedTest.java
  extended/src/test/resources/long-create.cypher
  extended/src/test/resources/range_in_transaction.cypher
Labels: cherry-picked, extended-functionality, 5.10

#3692 [NOID] lightened tests
  extended/src/test/java/apoc/cypher/CypherExtendedTest.java
  extended/src/test/resources/long-create.cypher
  extended/src/test/resources/range_in_transaction.cypher
Labels: cherry-picked, extended-functionality, dev

#3693 Exclude :core:shadowJar task from extended (#3597)
  settings.gradle
Labels: cherry-picked, extended-functionality, 5.10

#3694 Exclude :core:shadowJar task from extended (#3597)
  settings.gradle
Labels: cherry-picked, extended-functionality, dev

#3690 [NOID] Update license files
  LICENSES.txt
  NOTICE.txt
Labels: 4.4, team-cypher-surface

#3691 [hDJkPkOQ] Fixes neo4j/apoc#126: apoc.periodic.submit fails with schema operations (extended) (#3211) (#3508)
  full/src/main/java/apoc/periodic/PeriodicExtended.java
  full/src/main/resources/extended.txt
  full/src/test/java/apoc/periodic/PeriodicExtendedTest.java
Labels: cherry-picked, 4.4, extended-functionality

#3542 [LMyH0Fi7] apoc.systemdb.graph leaks passwords/hashes (#3414)
  full-it/src/test/java/apoc/full/it/SystemDbEnterpriseTest.java
  full/src/main/java/apoc/systemdb/SystemDb.java
Labels: cherry-picked, 4.4, extended-functionality

#3688 [MqyrvomD] Upgrade lettuce version to 6.2.5 to mitigate CVE-2023-34462
  docs/asciidoc/modules/ROOT/pages/database-integration/redis.adoc
  extra-dependencies/redis/build.gradle
  full/build.gradle
  full/src/main/java/apoc/redis/RedisConfig.java
Labels: 4.4, team-cypher-surface

#3704 [NOID] apoc.log docs update
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.log.debug.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.log.error.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.log.info.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.log.warn.adoc
Labels: cherry-picked, 4.4, team-cypher-surface
