Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2023-11, with the labels that each got.

#3827 [duCyJhIC] Update APOC and Neo4j versions to next release
  build.gradle
  docs/asciidoc/antora.yml
  extra-dependencies/build.gradle
  readme.adoc
Labels: 4.4, team-cypher-surface

#3829 Bump version 5.15.0 (#3456) (#3536) (#3726)
  build.gradle
  docs/asciidoc/antora.yml
  docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
  docs/build.gradle
  extra-dependencies/build.gradle
  readme.adoc
Labels: cherry-picked, extended-functionality, dev

#3830 Solve CI 5.15 compile error
  extended/src/main/java/apoc/monitor/Ids.java
Labels: extended-functionality, dev

#3689 [uXDd3S9j] Upgrade google-cloud-storage-version version to 2.29.1 to mitigate CVE-2023-2976
  core/build.gradle
  extra-dependencies/gcs/build.gradle
  extra-dependencies/hadoop/build.gradle
  full/build.gradle
Labels: 4.4, team-cypher-surface

#3839 [NOID] Bump Neo4j version to 4.4.29
  build.gradle
  readme.adoc
Labels: 4.4, team-cypher-surface

#3842 [gtjPFvMD] Fix coll support for lists coming from Nodes or Rels.
  LICENSES.txt
  NOTICE.txt
  core/src/main/java/apoc/coll/Coll.java
  core/src/main/java/apoc/convert/Convert.java
  core/src/test/java/apoc/coll/CollTest.java
Labels: cherry-picked, 4.4, team-cypher-surface

#3835 Update vertexai.adoc
  docs/asciidoc/modules/ROOT/pages/ml/vertexai.adoc
Labels: extended-functionality

#3838 Fixes #2612: Added MAPRESULT type to custom functions
  docs/asciidoc/modules/ROOT/pages/cypher-execution/cypher-based-procedures-functions.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.declareFunction.adoc
  extended/src/main/antlr/apoc/custom/Signature.g4
  extended/src/main/java/apoc/ExtendedSystemPropertyKeys.java
  extended/src/main/java/apoc/custom/CypherProcedures.java
  extended/src/main/java/apoc/custom/CypherProceduresHandler.java
  extended/src/main/java/apoc/custom/Signatures.java
  extended/src/test/java/apoc/custom/CypherProceduresStorageTest.java
Labels: extended-functionality, dev
