Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2023-01, with the labels that each got.

#3382 [4Bmcyc2U] Fix ignored S3 tests (neo4j/apoc#241)
  core/build.gradle
  core/src/test/java/apoc/export/ExportS3PerformanceTest.java
  core/src/test/java/apoc/export/csv/ExportCsvS3Test.java
  core/src/test/java/apoc/export/cypher/ExportCypherS3Test.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLS3Test.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTestUtil.java
  core/src/test/java/apoc/export/json/ExportJsonS3Test.java
  core/src/test/java/apoc/export/json/ExportJsonTest.java
  core/src/test/java/apoc/util/FileTestUtil.java
  core/src/test/java/apoc/util/s3/S3BaseTest.java
  core/src/test/java/apoc/util/s3/S3Container.java
  core/src/test/java/apoc/util/s3/S3ParamsExtractorTest.java
  core/src/test/java/apoc/util/s3/S3TestUtil.java
  test-utils/build.gradle
Labels: cherry-picked, 4.4

#3386 [BScFsD5y] Add missing images to vPattern and vPatternFull
  docs/asciidoc/modules/ROOT/images/apoc.create.vPattern.png
  docs/asciidoc/modules/ROOT/images/apoc.create.vPatternFull.png
Labels: docs, 4.4, team-cypher-surface

#3395 [Zl3h9sM8] apoc.schema.relationships return wrong output for relationship indexes
  core/src/main/java/apoc/result/IndexConstraintNodeInfo.java
  core/src/main/java/apoc/result/IndexConstraintRelationshipInfo.java
  core/src/main/java/apoc/schema/Schemas.java
  core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
  core/src/test/java/apoc/schema/SchemasTest.java
Labels: cherry-picked, 4.4, core-functionality

#3393 [gRNAet7B] Changes from neo4j/apoc#250
  core/src/main/java/apoc/trigger/Trigger.java
  core/src/main/java/apoc/trigger/TriggerHandlerNewProcedures.java
  core/src/main/java/apoc/trigger/TriggerInfo.java
  core/src/main/java/apoc/trigger/TriggerNewProcedures.java
  core/src/test/java/apoc/trigger/TriggerClusterRoutingTest.java
  core/src/test/java/apoc/trigger/TriggerEnterpriseFeaturesTest.java
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.add.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.pause.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.remove.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.removeAll.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.resume.adoc
Labels: cherry-picked, 4.4, core-functionality

#3404 [ADJvoENI] apoc.schema.properties.distinct(Count) can hang (neo4j/apoc#257)
  core/src/main/java/apoc/index/SchemaIndex.java
  core/src/test/java/apoc/index/SchemaIndexTest.java
Labels: cherry-picked, 4.4, core-functionality

#3361 [wokdlhX3] Extract code from APOC core which is only used in APOC extended
  extended/src/main/antlr/apoc/custom/Signature.g4
  extended/src/main/java/apoc/Description.java
  extended/src/main/java/apoc/ExtendedApocConfig.java
  extended/src/main/java/apoc/ExtendedSystemLabels.java
  extended/src/main/java/apoc/ExtendedSystemPropertyKeys.java
  extended/src/main/java/apoc/TTLConfig.java
  extended/src/main/java/apoc/config/Config.java
  extended/src/main/java/apoc/custom/CypherProceduresHandler.java
  extended/src/main/java/apoc/cypher/CypherExtended.java
  extended/src/main/java/apoc/dv/DataVirtualizationCatalog.java
  extended/src/main/java/apoc/dv/DataVirtualizationCatalogHandler.java
  extended/src/main/java/apoc/es/ElasticSearch.java
  extended/src/main/java/apoc/gephi/Gephi.java
  extended/src/main/java/apoc/load/LoadCsv.java
  extended/src/main/java/apoc/load/LoadDirectory.java
  extended/src/main/java/apoc/load/LoadDirectoryHandler.java
  extended/src/main/java/apoc/load/LoadXls.java
  extended/src/main/java/apoc/load/util/JdbcUtil.java
  extended/src/main/java/apoc/load/util/LoadCsvConfig.java
  extended/src/main/java/apoc/load/util/LoadJdbcConfig.java
  extended/src/main/java/apoc/metrics/Metrics.java
  extended/src/main/java/apoc/result/BooleanResult.java
  extended/src/main/java/apoc/result/IdsResult.java
  extended/src/main/java/apoc/result/KernelInfoResult.java
  extended/src/main/java/apoc/result/KeyValueResult.java
  extended/src/main/java/apoc/result/NodeValueErrorMapResult.java
  extended/src/main/java/apoc/result/NodeWithMapResult.java
  extended/src/main/java/apoc/result/StoreInfoResult.java
  extended/src/main/java/apoc/result/StringResult.java
  extended/src/main/java/apoc/result/TransactionInfoResult.java
  extended/src/main/java/apoc/systemdb/SystemDb.java
  extended/src/main/java/apoc/systemdb/metadata/ExportDataVirtualization.java
  extended/src/main/java/apoc/systemdb/metadata/ExportFunction.java
  extended/src/main/java/apoc/systemdb/metadata/ExportMetadata.java
  extended/src/main/java/apoc/systemdb/metadata/ExportProcedure.java
  extended/src/main/java/apoc/systemdb/metadata/ExportTrigger.java
  extended/src/main/java/apoc/systemdb/metadata/ExportUuid.java
  extended/src/main/java/apoc/util/ExtendedFileUtils.java
  extended/src/main/java/apoc/util/ExtendedUtil.java
  extended/src/main/java/apoc/util/UriResolver.java
  extended/src/main/java/apoc/util/UrlResolver.java
  extended/src/main/java/apoc/uuid/UuidConfig.java
  extended/src/main/java/apoc/uuid/UuidHandler.java
  extended/src/test/java/apoc/TTLConfigTest.java
  extended/src/test/java/apoc/custom/CypherProceduresClusterTest.java
  extended/src/test/java/apoc/custom/CypherProceduresTest.java
  extended/src/test/java/apoc/load/LoadGoogleCloudStorageTest.java
  extended/src/test/java/apoc/load/MySQLJdbcTest.java
  extended/src/test/java/apoc/metrics/MetricsTest.java
  extended/src/test/java/apoc/systemdb/SystemDbTest.java
  extended/src/test/java/apoc/trigger/TriggerClusterTest.java
  extended/src/test/java/apoc/ttl/TTLTest.java
  extended/src/test/java/apoc/util/ExtendedTestContainerUtil.java
  extended/src/test/java/apoc/util/s3/GoogleCloudStorageContainerExtension.java
  extended/src/test/java/apoc/util/s3/MySQLContainerExtension.java
Labels: team-cypher-surface

#3410 [VOpjI5JE] Try fixing cluster failing test (neo4j/apoc#177) (neo4j/ap…
  test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: cherry-picked, 4.4, core-functionality

#3409 [qZZ3O2uX] Updates jackson-databind to fix CVE-2020-36518, CVE-2022-42004, CVE-2022-42003
  core/build.gradle
  extra-dependencies/nlp/build.gradle
  full/build.gradle
Labels: dependencies, 4.4, team-cypher-surface

#3415 [21wxsujh] Try to fix APOC redirect test
  build.gradle
Labels: 4.4

#3036 [NOID] Fixes #2978: The apoc.custom.declareProcedure does not accept default string values
  core/src/main/antlr/apoc/custom/Signature.g4
  docs/asciidoc/modules/ROOT/pages/cypher-execution/cypher-based-procedures-functions.adoc
  full/src/main/java/apoc/custom/Signatures.java
  full/src/test/java/apoc/custom/CypherProceduresTest.java
Labels: extended-functionality

#3421 [hDJkPkOQ] Add QueryType validation in apoc.trigger.add
  core/src/main/java/apoc/trigger/TriggerNewProcedures.java
  core/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
Labels: 4.4, core-functionality

#3422 [xc2oVWgi] document warnings for dependencies excluded from APOC Core jar
  docs/asciidoc/modules/ROOT/nav.adoc
  docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
Labels: cherry-picked, 4.4

#3414 [LMyH0Fi7] apoc.systemdb.graph leaks passwords/hashes
  extended/src/main/java/apoc/systemdb/SystemDb.java
  extended/src/test/java/apoc/systemdb/SystemDbEnterpriseTest.java
Labels: extended-functionality, 5.5

#3407 [NOID] fixes #3349: Can not create custom procedure with void return type using apoc.custom.declareProcedure (#3356)
  extended/src/main/java/apoc/custom/CypherProcedures.java
  extended/src/main/java/apoc/custom/CypherProceduresHandler.java
  extended/src/test/java/apoc/custom/CypherProceduresTest.java
Labels: cherry-picked, 5.4

#3400 [PL7XdSMV] apoc.config.list and apoc.config.map leak evars
  docs/asciidoc/modules/ROOT/partials/usage/allowed.configs.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.config.list.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.config.map.adoc
  extended/src/main/java/apoc/config/Config.java
  extended/src/test/java/apoc/config/ConfigTest.java
Labels: to-cherry-pick, extended-functionality, 5.4

#3428 [LMyH0Fi7] apoc.systemdb.graph leaks passwords/hashes (#3414)
  extended/src/main/java/apoc/systemdb/SystemDb.java
  extended/src/test/java/apoc/systemdb/SystemDbEnterpriseTest.java
Labels: cherry-picked, 5.4

#3429 [NOID] Clean up APOC matrix list
  readme.adoc
Labels: docs, team-cypher-surface

#3431 [NOID] Update selenium extra-deps' webdrivermanager
  extra-dependencies/selenium/build.gradle
Labels: to-cherry-pick, 5.4

#3406 [NOID] fixes #3349: Can not create custom procedure with void return type using apoc.custom.declareProcedure (#3356)
  extended/src/main/java/apoc/custom/CypherProcedures.java
  extended/src/main/java/apoc/custom/CypherProceduresHandler.java
  extended/src/test/java/apoc/custom/CypherProceduresTest.java
Labels: cherry-picked, extended-functionality

#3430 [NOID] Bumps 4.4 version
  build.gradle
  docs/asciidoc/antora.yml
  docs/build.gradle
  extra-dependencies/build.gradle
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: 4.4, team-cypher-surface

#3435 [gcL5e77c] Fix edge cases in trigger methods (neo4j/apoc#288)
  core/src/main/java/apoc/trigger/TriggerHandlerNewProcedures.java
  core/src/main/java/apoc/trigger/TriggerNewProcedures.java
  core/src/test/java/apoc/trigger/TriggerClusterRoutingTest.java
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: cherry-picked, 4.4
