Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2023-02, with the labels that each got.

#3437 [4cnpX39y] Bump mockserver-netty version and org.apache.arrow version
  core/build.gradle
  full/build.gradle
  test-utils/build.gradle
Labels: cherry-picked, 4.4, team-cypher-surface

#3439 [HQABUD5U] Improve coverNodes speed
  core/src/main/java/apoc/algo/Cover.java
Labels: cherry-picked, 4.4, team-cypher-surface

#3440 [04b6IYYB] Fix sampling in apoc.meta procedures
  core/src/main/java/apoc/meta/Meta.java
  core/src/main/java/apoc/meta/MetaConfig.java
  core/src/main/java/apoc/meta/SampleMetaConfig.java
  core/src/test/java/apoc/meta/MetaTest.java
Labels: cherry-picked, 4.4, team-cypher-surface

#3441 [qh4YGSlZ] Add 'Security Guidelines' page
  docs/asciidoc/modules/ROOT/nav.adoc
  docs/asciidoc/modules/ROOT/pages/config/index.adoc
  docs/asciidoc/modules/ROOT/pages/index.adoc
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
  docs/asciidoc/modules/ROOT/pages/misc/spatial.adoc
  docs/asciidoc/modules/ROOT/pages/security-guidelines/index.adoc
  docs/asciidoc/modules/ROOT/partials/restricted.adoc
Labels: cherry-picked, 4.4

#3442 [04b6IYYB] Fix sampling documentation for apoc.meta.* procs
  docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.data.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.data.of.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.graph.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.graph.of.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.schema.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.subGraph.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.meta.nodes.count.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.meta.samplingDesc.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.data.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.graph.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.nodeTypeProperties.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.nodes.count.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.relTypeProperties.adoc
Labels: docs, cherry-picked, 4.4, team-cypher-surface

#3444 [mIPA5H7K] Avoids double DNS lookup in the load methods (#315)
  core/src/main/java/apoc/ApocConfig.java
  core/src/main/java/apoc/util/Util.java
Labels: cherry-picked, 4.4, team-cypher-surface

#3448 [0eSjZq6Q] Fix S3 failing flaky tests (neo4j/apoc#294)
  core/src/test/java/apoc/util/s3/S3TestUtil.java
Labels: cherry-picked, 4.4

#3452 [2yJwJP80] bump version for 4.4.0.14 release
  build.gradle
  docs/asciidoc/antora.yml
  docs/build.gradle
  extra-dependencies/build.gradle
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: 4.4

#3450 [TOQo1n9M] apoc-hadoop dependency is conflicting
  extra-dependencies/hadoop/build.gradle
  test-startup/src/test/java/StartupTest.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: 4.4

#3451 [wvzcpHQH] Add SSFR check for apoc.spatial procedures (neo4j/apoc#305)
  core/src/test/java/apoc/spatial/GeocodeTest.java
Labels: cherry-picked, 4.4

#3455 [NOID] Release 5.5.0
  .github/workflows/CI.yaml
  .gitmodules
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
  readme.adoc
Labels: extended-functionality, 5.5

#3413 [iREBdGuF] Stop recommending loading/unrestricting all procedures
  docs/asciidoc/modules/ROOT/nav.adoc
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
  docs/asciidoc/modules/ROOT/partials/restricted.adoc
  readme.adoc
Labels: extended-functionality, 5.5

#3453 [NOID] Fix wrong throttle config in Geocode.SupplierWithKey (#327)
  core/src/main/java/apoc/spatial/Geocode.java
Labels: cherry-picked, 4.4, core-functionality

#3459 [aNcPaEFK] Fix LoadLdapTest.testLoadLDAP
  extended/build.gradle
  extended/src/test/java/apoc/load/LoadLdapTest.java
  extended/src/test/resources/ldap/example.ldif
Labels: extended-functionality, dev

#3460 [NOID] Upgraded jsoup to v.1.15.3 to mitigate CVE-2022-36033 (#3305)
  extended/build.gradle
  extended/src/main/java/apoc/load/LoadHtml.java
  extended/src/test/java/apoc/load/LoadHtmlTest.java
Labels: cherry-picked, to-cherry-pick, extended-functionality, 5.5

#3465 Bump package.json antora 5.5
  docs/antora/package-lock.json
Labels: cherry-picked, extended-functionality, 5.5

#3466 [iREBdGuF] Stop recommending loading/unrestricting all procedures (#3413)
  docs/asciidoc/modules/ROOT/nav.adoc
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
  docs/asciidoc/modules/ROOT/partials/restricted.adoc
  readme.adoc
Labels: cherry-picked, 5.5

#3464 [aNcPaEFK] Fix LoadLdapTest.testLoadLDAP (#3459)
  extended/build.gradle
  extended/src/test/java/apoc/load/LoadLdapTest.java
  extended/src/test/resources/ldap/example.ldif
Labels: cherry-picked, 5.5

#3463 [NOID] Bump package.json antora
  docs/antora/package-lock.json
Labels: cherry-picked, extended-functionality, dev

#3462 [GE2QhC9X] Fix path traversal vulnerability (CVE-2022-23532) (#3457)
  extended/src/test/java/apoc/export/ExportExtendedSecurityTest.java
Labels: cherry-picked, extended-functionality, dev

#3461 [EHgXqsEW] Upgraded jsoup to v.1.15.3 to mitigate CVE-2022-36033 (#3305) (#3460)
  extended/build.gradle
  extended/src/main/java/apoc/load/LoadHtml.java
  extended/src/test/java/apoc/load/LoadHtmlTest.java
Labels: cherry-picked, extended-functionality, dev

#3418 Ignore git submodule from commits
  extended/build.gradle
  init.gradle
Labels: extended-functionality

#3467 [NOID] Excluded duplicated libs in extra-dependencies
  extra-dependencies/hadoop/build.gradle
  extra-dependencies/selenium/build.gradle
  extra-dependencies/xls/build.gradle
Labels: to-cherry-pick, 5.5

#3468 [NOID] Ignore git submodule (#3418)
  extended/build.gradle
  init.gradle
Labels: cherry-picked, extended-functionality, 5.5

#3474 [aNcPaEFK] Fix LoadLdapTest.testLoadLDAP (#3459)
  full/build.gradle
  full/src/test/java/apoc/load/LoadLdapTest.java
  full/src/test/resources/ldap/example.ldif
Labels: cherry-picked, 4.4, extended-functionality

#3472 [mcub3FQf] Improve triggers error messages (neo4j/apoc#302)
  core/src/main/java/apoc/trigger/TriggerNewProcedures.java
Labels: cherry-picked, 4.4

#3473 [Ci2sJ23z] apoc.trigger.show doesn't work in a system follower
  core/src/main/java/apoc/trigger/Trigger.java
  core/src/main/java/apoc/trigger/TriggerNewProcedures.java
  core/src/test/java/apoc/trigger/TriggerClusterRoutingTest.java
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
Labels: cherry-picked, 4.4

#3476 [NOID] Remove SnakeYaml as not used and vulnerable
  core/build.gradle
Labels: 4.4, team-cypher-surface

#3443 [vEqEKeNT] Fix wrongly labeled procedures
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.dv.catalog.add.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.dv.catalog.list.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.dv.catalog.remove.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.dv.query.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.dv.queryAndLink.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.nlp.azure.entities.graph.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.nlp.azure.entities.stream.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.nlp.azure.keyPhrases.graph.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.nlp.azure.keyPhrases.stream.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.nlp.azure.sentiment.graph.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.nlp.azure.sentiment.stream.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.bolt/apoc.bolt.execute.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.bolt/index.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.dv/apoc.dv.catalog.add.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.dv/apoc.dv.catalog.list.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.dv/apoc.dv.catalog.remove.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.dv/apoc.dv.query.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.dv/apoc.dv.queryAndLink.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.dv/index.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.nlp/apoc.nlp.azure.entities.graph.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.nlp/apoc.nlp.azure.entities.stream.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.nlp/apoc.nlp.azure.keyPhrases.graph.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.nlp/apoc.nlp.azure.keyPhrases.stream.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.nlp/apoc.nlp.azure.sentiment.graph.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.nlp/apoc.nlp.azure.sentiment.stream.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.nlp/index.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.systemdb/apoc.systemdb.export.metadata.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.systemdb/index.adoc
  docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
Labels: docs, 4.4, team-cypher-surface
