Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2023-05, with the labels that each got.

#3557 [NOID] removed unused import ConfigTest
  full/src/test/java/apoc/config/ConfigTest.java
Labels: 4.4

#3561 [NOID] Ignores flaky tests until they are fixed
  full/src/test/java/apoc/config/ConfigTest.java
  full/src/test/java/apoc/uuid/UUIDClusterRoutingTest.java
  test-startup/src/test/java/StartupTest.java
Labels: 4.4, team-cypher-surface

#3546 [Fb3ZFQbn] Fixes cypher initializer
  core/src/main/java/apoc/cypher/CypherInitializer.java
  test-startup/src/test/java/StartupTest.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: 4.4, team-cypher-surface

#3556 [qWQ33yT5] apoc.export.cypher.all rel indexes exported incorrectly
  core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
  core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java
  core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Labels: 4.4, core-functionality

#3559 [NOID] Fix flaky ConfigTest
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
  core/src/test/java/apoc/trigger/TriggerRestartTest.java
  full/src/test/java/apoc/config/ConfigTest.java
  full/src/test/java/apoc/trigger/TriggerNewProceduresExtendedTest.java
  full/src/test/java/apoc/util/DbmsTestUtil.java
  full/src/test/java/apoc/uuid/UUIDNewProceduresTest.java
  full/src/test/java/apoc/uuid/UUIDRestartTest.java
  full/src/test/java/apoc/uuid/UUIDTestUtils.java
Labels: 4.4

#3554 [l8BgbZYY] bump neo4j version to 4.4.20
  build.gradle
  docs/asciidoc/antora.yml
  docs/build.gradle
  extra-dependencies/build.gradle
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: 4.4

#3549 [hyxhNENW] remove antlr4 from core
  build.gradle
  core/build.gradle
  full/src/main/antlr/apoc/custom/Signature.g4
Labels: cherry-picked, 4.4, core-functionality

#3571 [ivaiMqVb] CALL apoc.export.cypher.schema(null, { stream: true }) returns nothing (neo4j/apoc#374)
  core/src/main/java/apoc/export/cypher/ExportCypher.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Labels: cherry-picked, 4.4

#3563 [mXBP8GqN] Bumps apoc version
  build.gradle
  docs/asciidoc/antora.yml
  docs/build.gradle
  extra-dependencies/build.gradle
Labels: 4.4, team-cypher-surface

#3572 [UNKBKte1] Redacts passwords in CypherInitializer
  core/src/main/java/apoc/cypher/CypherInitializer.java
  core/src/main/java/apoc/util/LogsUtil.java
  core/src/main/java/apoc/util/QueryUtil.java
  core/src/test/java/apoc/util/LogsUtilTest.java
  core/src/test/java/apoc/util/QueryUtilTest.java
  test-startup/src/test/java/StartupTest.java
Labels: bug, to-cherry-pick, 4.4, team-cypher-surface

#3577 [ZkSGN6PO] apoc.export.graphml.all doesn't accept absolute Windows paths (neo4j/apoc#381)
  core/src/main/java/apoc/util/FileUtils.java
  core/src/main/java/apoc/util/Util.java
Labels: cherry-picked, 4.4, core-functionality

#3576 [gULAAkri] apoc.periodic.repeat doesn't always work (neo4j/apoc#388)
  core/src/main/java/apoc/periodic/Periodic.java
  core/src/main/java/apoc/periodic/PeriodicUtils.java
  core/src/test/java/apoc/periodic/PeriodicTest.java
Labels: cherry-picked, 4.4, core-functionality

#3569 [VyGD3IoX] apoc.hashing.fingerprint lossy conversion (neo4j/apoc#378)
  core/src/main/java/apoc/hashing/Fingerprinting.java
Labels: cherry-picked, 4.4

#3551 [Q8q7GXdk] apoc.export.graphml imports unwanted nodes (neo4j/apoc#380)
  core/src/main/java/apoc/export/cypher/ExportCypher.java
  core/src/main/java/apoc/export/graphml/ExportGraphML.java
  core/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTestUtil.java
Labels: cherry-picked, 4.4, core-functionality

#3578 [rePYjknU] Fix flaky testExportQueryNodesJsonCount (neo4j/apoc#406)
  core/src/test/java/apoc/export/json/ExportJsonS3Test.java
  core/src/test/java/apoc/util/s3/S3TestUtil.java
Labels: cherry-picked, 4.4

#3579 Bump version 5.9.0 (#3456)
  build.gradle
  docs/asciidoc/antora.yml
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
  docs/build.gradle
  extra-dependencies/build.gradle
  readme.adoc
Labels: extended-functionality, dev

#3581 [9VPaH2ha] Bumps apoc version
  build.gradle
  docs/asciidoc/antora.yml
  docs/build.gradle
  extra-dependencies/build.gradle
Labels: 4.4, team-cypher-surface

#3548 [OfagjOnq] apoc.meta.subgraph returns wrong type when using includeLabels
  core/src/main/java/org/neo4j/cypher/export/DatabaseSubGraph.java
  core/src/test/java/apoc/meta/MetaTest.java
Labels: 4.4

#3580 [NOID] Release 5.8.0 (#3455)
  .github/workflows/CI.yaml
  .gitmodules
  docs/asciidoc/modules/ROOT/pages/installation/index.adoc
  readme.adoc
Labels: extended-functionality, 5.8

#3582 Add OpenAI (LLM) procedures (#3575)
  docs/asciidoc/modules/ROOT/nav.adoc
  docs/asciidoc/modules/ROOT/pages/ml/index.adoc
  docs/asciidoc/modules/ROOT/pages/ml/openai.adoc
  extended/src/main/java/apoc/ml/OpenAI.java
  extended/src/main/resources/extended.txt
  extended/src/test/java/apoc/ml/OpenAIIT.java
  extended/src/test/java/apoc/ml/OpenAITest.java
  extended/src/test/resources/chat/completions
  extended/src/test/resources/completions
  extended/src/test/resources/embeddings
Labels: cherry-picked, extended-functionality, 5.8

#3590 Updated extended.txt to fix checkCoreWithExtraDependenciesJars failure after Open AI procedures
  extended/src/main/resources/extended.txt
Labels: extended-functionality, dev

#3565 [NOID] fix time assertion GeocodeTest
  core/src/test/java/apoc/spatial/GeocodeTest.java
Labels: to-cherry-pick, 4.4, team-cypher-surface

#3595 [NOID] Fixes circular docker dependency in TeamCity
  build.gradle
Labels: bug, team-cypher-surface

#3568 [rF3PTDby] Fix shouldFindDifferencesInTheSameDb
  full/src/main/java/apoc/diff/DiffFull.java
Labels: 4.4, extended-functionality

#3592 [tW7Gyubn] Removed javafaker lib and replaced with a custom class
  extended/build.gradle
  extended/src/main/java/apoc/generate/node/SocialNetworkNodeCreator.java
  extended/src/main/java/apoc/util/Faker.java
Labels: extended-functionality, dev

#3600 [dITjfMpu] apoc.coll.indexOf unexpectedly treats collections differently than the same hardcoded list (neo4j/apoc#422)
  core/src/main/java/apoc/coll/Coll.java
  core/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/coll/CollTest.java
Labels: cherry-picked, 4.4

#3598 [bZQoGhFu] apoc.refactor.mergeNodes is not working with uniqueness index (neo4j/apoc#361)
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
Labels: cherry-picked, 4.4

#3599 [dLZ2xYwQ] Multiple CypherInitializer's per single DatabaseAvailabilityGuard (neo4j/apoc#413)
  core/src/main/java/apoc/ApocExtensionFactory.java
Labels: cherry-picked, 4.4

#3603 Adding Vertex-AI Integration (#3601)
  docs/asciidoc/modules/ROOT/nav.adoc
  docs/asciidoc/modules/ROOT/pages/ml/index.adoc
  docs/asciidoc/modules/ROOT/pages/ml/vertexai.adoc
  extended/src/main/java/apoc/ml/VertexAI.java
  extended/src/main/resources/extended.txt
  extended/src/test/java/apoc/ml/VertexAIIT.java
Labels: cherry-picked, 5.8
