Repository neo4j-contrib/neo4j-apoc-procedures, pull requests merged in 2024-09, with the labels that each got.

#4177 Fixes #4138: Add support for loading Gephi GEXF file format
  docs/asciidoc/modules/ROOT/nav.adoc
  docs/asciidoc/modules/ROOT/pages/import/gexf.adoc
  docs/asciidoc/modules/ROOT/pages/import/index.adoc
  extended/src/main/java/apoc/load/Gexf.java
  extended/src/main/java/apoc/load/util/XmlReadUtil.java
  extended/src/main/java/apoc/util/ExtendedUtil.java
  extended/src/main/resources/extended.txt
  extended/src/test/java/apoc/load/GexfTest.java
  extended/src/test/java/apoc/util/ExtendedTestUtil.java
  extended/src/test/resources/gexf/data.gexf
  extended/src/test/resources/gexf/malformed.gexf
  extended/src/test/resources/gexf/single-node.gexf
  extended/src/test/resources/gexf/single-rel.gexf
Labels: extended-functionality, 5.23

#4175 [NOID] Version Bump
  build.gradle
  docs/asciidoc/antora.yml
  extra-dependencies/build.gradle
  readme.adoc
Labels: 4.4, team-cypher-surface

#4176 [uRFsgcuC] Backport of 5.x ifNeeded quote fix
  core-it/src/test/java/apoc/core/it/ExportCsvS3Test.java
  core/src/main/java/apoc/export/csv/CsvFormat.java
  core/src/main/java/apoc/export/util/ExportConfig.java
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
Labels: 4.4, team-cypher-surface

#4180 [Io7UetI2] Update dependencies to mitigate vulnerabilities
  LICENSES.txt
  NOTICE.txt
  core-it/build.gradle
  core/build.gradle
  extra-dependencies/aws/build.gradle
  extra-dependencies/nlp/build.gradle
  full-it/build.gradle
  full/build.gradle
  test-utils/build.gradle
Labels: 4.4, team-cypher-surface

#4118 [NOID] NLP documentation into APOC pages (#4076)
  docs/asciidoc/modules/ROOT/examples/queries.cypher
  docs/asciidoc/modules/ROOT/images/1280px-Wikidata-logo-en.svg.png
  docs/asciidoc/modules/ROOT/images/apoc_gcp.jpg
  docs/asciidoc/modules/ROOT/images/copy-sparql-api.png
  docs/asciidoc/modules/ROOT/images/devto-screenshot.png
  docs/asciidoc/modules/ROOT/images/n10s.png
  docs/asciidoc/modules/ROOT/images/one-article-entities.svg
  docs/asciidoc/modules/ROOT/images/post-dev-to-import.png
  docs/asciidoc/modules/ROOT/images/similar-articles-1.png
  docs/asciidoc/modules/ROOT/images/stacks.svg
  docs/asciidoc/modules/ROOT/images/version-control.svg
  docs/asciidoc/modules/ROOT/images/wikidata-api.png
  docs/asciidoc/modules/ROOT/images/zookeeper-nosql.png
  docs/asciidoc/modules/ROOT/pages/nlp/build-knowledge-graph-nlp-ontologies.adoc
  docs/asciidoc/modules/ROOT/pages/nlp/entity-extraction.adoc
  docs/asciidoc/modules/ROOT/pages/nlp/index.adoc
Labels: cherry-picked, 4.4, extended-functionality

#4117 [NOID] Fixes #1596: Change key/secret to optional in apoc.nlp calls for AWS (#4062)
  full/src/main/kotlin/apoc/nlp/aws/AWSProcedures.kt
  full/src/main/kotlin/apoc/nlp/aws/RealAWSClient.kt
  full/src/test/kotlin/apoc/nlp/aws/AWSProceduresAPIWithEnvVarsTest.kt
  full/src/test/kotlin/apoc/nlp/aws/AWSProceduresErrorsTest.kt
Labels: cherry-picked, 4.4, extended-functionality

#4030 [NOID] Fixes #3401: APOC Custom Procedures/Function new procedures working with Cluster (#3943)
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.custom.dropAll.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.custom.dropFunction.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.custom.dropProcedure.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.custom.installFunction.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.custom.installProcedure.adoc
  docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.custom.show.adoc
  docs/asciidoc/modules/ROOT/pages/cypher-execution/cypher-based-procedures-functions.adoc
  docs/asciidoc/modules/ROOT/pages/deprecations-and-additions/index.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.declareFunction.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.declareProcedure.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.dropAll.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.dropFunction.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.dropProcedure.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.installFunction.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.installProcedure.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.removeFunction.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.removeProcedure.adoc
  docs/asciidoc/modules/ROOT/pages/overview/apoc.custom/apoc.custom.show.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.installFunction.adoc
  docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.installProcedure.adoc
  extended/src/main/java/apoc/systemdb/metadata/ExportFunction.java
  extended/src/main/java/apoc/systemdb/metadata/ExportProcedure.java
  extended/src/test/java/apoc/util/ExtendedTestContainerUtil.java
  full/src/main/java/apoc/custom/CustomProcedureInfo.java
  full/src/main/java/apoc/custom/CypherHandlerNewProcedure.java
  full/src/main/java/apoc/custom/CypherNewProcedures.java
  full/src/main/java/apoc/custom/CypherProcedures.java
  full/src/main/java/apoc/custom/CypherProceduresHandler.java
  full/src/main/java/apoc/custom/CypherProceduresUtil.java
  full/src/main/java/apoc/custom/Signatures.java
  full/src/main/java/apoc/util/SystemDbUtil.java
  full/src/main/resources/extended.txt
  full/src/test/java/apoc/custom/CustomNewProcedureStorageTest.java
  full/src/test/java/apoc/custom/CypherNewProceduresTest.java
  full/src/test/java/apoc/custom/CypherProcedureTestUtil.java
  full/src/test/java/apoc/util/ExtendedTestUtil.java
Labels: cherry-picked, 4.4, extended-functionality
